openapi: 3.0.1

servers:
  - url: http://localhost:4550/

info:
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
  version: ${version}
  title: Modernised DARTS

paths:
  /cases/{case_id}/annotations:
    get:
      tags:
        - Annotation
      summary: Admin / Judge view for annotations
      operationId: getYourAnnotations
      parameters:
        - in: path
          name: case_id
          schema:
            type: integer
          required: true
        - in: header
          name: user_id
          schema:
            type: integer
          description: The user_account primary key
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetYourAnnotationsResponse'
        '400':
          description: Bad Request Error
        '401':
          description: Unauthorised Error
        '403':
          description: Unauthorised Error
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "CASE_104"
                title: "The requested case cannot be found"
                status: 404


components:
  schemas:
    GetYourAnnotationsResponse:
      type: array
      items:
        $ref: '#/components/schemas/Annotation'
    Annotation:
      type: object
      properties:
        annotation_id:
          type: integer
        hearing_id:
          type: integer
        hearing_date:
          type: string
          format: date
        annotation_ts:
          type: string
          format: date-time
        annotation_text:
          type: string
        annotation_documents:
          type: array
          items:
            $ref: '#/components/schemas/AnnotationDocument'
    AnnotationDocument:
      type: object
      properties:
        annotation_document_id:
          type: int
        file_name:
          type: string
        file_type:
          type: string
        uploaded_by:
          type: string
        uploaded_ts:
          type: string
          format: date-time
