openapi: 3.0.1

info:

  version: ${version}
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/

paths:
  /annotations:
    post:
      tags:
        - Annotations
      summary: Create an annotation with file upload.
      operationId: postAnnotation
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - annotation
              properties:
                file:
                  type: string
                  format: binary
                annotation:
                  $ref: '#/components/schemas/annotation'
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post_annotation_response'
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
  /annotations/{annotation_id}:
    delete:
      tags:
        - Annotations
      summary: Deletes an annotation.
      operationId: deleteAnnotation
      parameters:
        - in: path
          name: annotation_id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Annotation has been deleted
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
        '404':
          description: Annotation does not exist
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /annotations/{annotation_id}/documents/{annotation_document_id}:
    get:
      tags:
        - Annotations
      summary: Download Annotation Document
      operationId: downloadAnnotation
      parameters:
        - in: path
          name: annotation_id
          schema:
            type: integer
          description: "annotation id."
          required: true
        - in: path
          name: annotation_document_id
          schema:
            type: integer
          description: "annotation document id."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/AnnotationErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_REQUESTS_103"
                title: "The requested transformed media cannot be found"
                status: 404
        '500':
          description: The requested data cannot be located
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_101"
                title: "The requested data cannot be located"
                status: 500

components:
  schemas:
    annotation:
      type: object
      required:
        - hearing_id
      properties:
        hearing_id:
          type: integer
        comment:
          type: string
    post_annotation_response:
      type: object
      required:
        - annotation_id
      properties:
        annotation_id:
          type: integer

    AnnotationErrorCode:
      type: string
      enum:
        - "ANNOTATION_100"
        - "ANNOTATION_101"
        - "ANNOTATION_102"
        - "ANNOTATION_103"
        - "ANNOTATION_104"
        - "ANNOTATION_105"
        - "ANNOTATION_106"
      x-enum-varnames: [ HEARING_NOT_FOUND, FAILED_TO_UPLOAD_ANNOTATION_DOCUMENT, USER_NOT_AUTHORISED_TO_DOWNLOAD, INVALID_ANNOTATIONID_OR_ANNOTATION_DOCUMENTID, INVALID_ANNOTATIONID_OR_ANNOTATION_DOCUMENTID_FOR_JUDGE, FAILED_TO_DOWNLOAD_ANNOTATION_DOCUMENT]

    AnnotationTitleErrors:
      type: string
      enum:
        - "The requested hearing cannot be found"
        - "The annotation failed to be uploaded"
        - "user is not authorised to download annotation documents"
        - "annotation ID or annotation document ID does not exist"
        - "invalid annotation id or annotation document id"
        - "invalid annotation id or annotation document id for judge"
        - "The annotation failed to be downloaded"
      x-enum-varnames: [ HEARING_NOT_FOUND, FAILED_TO_UPLOAD_ANNOTATION_DOCUMENT, USER_NOT_AUTHORISED_TO_DOWNLOAD, INVALID_ANNOTATIONID_OR_ANNOTATION_DOCUMENTID, INVALID_ANNOTATIONID_OR_ANNOTATION_DOCUMENTID_FOR_JUDGE, FAILED_TO_DOWNLOAD_ANNOTATION_DOCUMENT]
