openapi: 3.0.1

servers:
  - url: http://localhost:4550/

info:
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
  version: ${version}
  title: Modernised DARTS

paths:
  /audio-requests:
    post:
      tags:
        - Audio
      summary: Users can request audio for specific cases and date/time periods
      operationId: addAudioRequest
      description: Adds a user audio request for processing
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddAudioResponse'
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: audio request item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AudioRequestDetails'
        description: Audio Request item to add

  /audio/download:
    get:
      tags:
        - Audio
      summary: Download audio
      operationId: download
      description: Download audio
      parameters:
        - in: query
          name: audioRequestId
          required: true
          schema:
            $ref: '#/components/schemas/AudioRequestId'
      responses:
        200:
          description: OK
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
            application/zip:
              schema:
                type: string
                format: binary
        500:
          description: The requested data cannot be located
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_101"
                title: "The requested data cannot be located"
                status: 500

  /audio/hearings/{hearing_id}/audios:
    get:
      tags:
        - Audio
      summary: Media metadata for provided hearing
      operationId: getAudioMetadata
      description: Media metadata for provided hearing
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AudioMetadata'
              examples:
                media-found:
                  summary: Media metadata exists for the given hearing id
                  value:
                    - id: 1
                      media_start_timestamp: '2023-07-31T14:32:24.620Z'
                      media_end_timestamp: '2023-07-31T14:32:24.620Z'
                media-not-found:
                  summary: No media metadata exists for the given hearing id
                  value:
                    [ ]
  /audio/preview/{media_id}:
    get:
      tags:
        - Audio
      summary: Preview audio
      operationId: preview
      description: Preview audio
      parameters:
        - in: path
          name: media_id
          schema:
            type: integer
          required: true
          description: "Internal identifier for media"
          example: 1
      responses:
        200:
          description: OK
          content:
            audio/mp3:
              schema:
                type: string
                format: binary
        '400':
          description: A required parameter is invalid.
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
        500:
          description: The requested data cannot be located
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_101"
                title: "The requested data cannot be located"
                status: 500

components:
  schemas:
    AudioRequestType:
      type: string
      enum:
        - DOWNLOAD
        - PLAYBACK

    AudioRequestDetails:
      type: object
      required:
        - hearing_id
        - requestor
        - start_time
        - end_time
        - request_type
      properties:
        hearing_id:
          type: integer
          example: 12345
        requestor:
          type: integer
          example: 4656
        start_time:
          type: string
          format: date-time
          example: '2023-05-31T09:00:00Z'
        end_time:
          type: string
          format: date-time
          example: '2023-05-31T12:00:00Z'
        request_type:
          $ref: '#/components/schemas/AudioRequestType'

    AudioRequestId:
      type: integer
      example: 12345

    AudioMetadata:
      type: object
      properties:
        id:
          type: integer
          example: 1
        media_start_timestamp:
          type: string
          format: date-time
        media_end_timestamp:
          type: string
          format: date-time

    AddAudioResponse:
      type: object
      required:
        - request_id
        - case_id
        - courthouse_name
        - defendants
        - hearing_date
        - start_time
        - end_time
      properties:
        request_id:
          type: integer
          example: 1234
        case_id:
          type: string
          example: T4565443
        courthouse_name:
          type: string
          example: "Swansea"
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        hearing_date:
          type: string
          format: date
          example: '10-05-2023'
        start_time:
          type: string
          format: date-time
          example: '2023-05-31T09:00:00Z'
        end_time:
          type: string
          format: date-time
          example: '2023-05-31T10:00:00Z'

    defendant:
      type: string
      example: Joe Bloggs
