openapi: 3.0.1

servers:
  - url: http://localhost:4550/

info:
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
  version: ${version}
  title: Modernised DARTS

paths:
  /audio/hearings/{hearing_id}/audios:
    get:
      tags:
        - Audio
      summary: Media metadata for provided hearing
      operationId: getAudioMetadata
      description: Media metadata for provided hearing
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AudioMetadata'
              examples:
                media-found:
                  summary: Media metadata exists for the given hearing id
                  value:
                    - id: 1
                      media_start_timestamp: '2023-07-31T14:32:24.620Z'
                      media_end_timestamp: '2023-07-31T14:32:24.620Z'
                media-not-found:
                  summary: No media metadata exists for the given hearing id
                  value:
                    [ ]
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_102"
                title: "Failed to check authorisation for the hearing"
                status: 400
        '401':
          description: Unauthorised Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 401
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "HEARING_100"
                title: "The requested hearing cannot be found"
                status: 404
  /audio/preview/{media_id}:
    get:
      tags:
        - Audio
      summary: Preview audio
      operationId: preview
      description: Preview audio
      parameters:
        - in: path
          name: media_id
          schema:
            type: integer
          required: true
          description: "Internal identifier for media"
          example: 1
        - in: header
          name: range
          schema:
            type: string
          description: "Range header, required for streaming audio."
      responses:
        200:
          description: OK
          content:
            audio/mpeg:
              schema:
                type: string
                format: byte
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_104"
                title: "Failed to check authorisation for the media"
                status: 400
        '401':
          description: Unauthorised Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 401
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_102"
                title: "The requested media cannot be found"
                status: 404
        500:
          description: The requested data cannot be located
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_101"
                title: "The requested data cannot be located"
                status: 500
  /audios:
    post:
      tags:
        - Audio
      summary: Upload audio file and metadata
      operationId: addAudio
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                metadata:
                  $ref: '#/components/schemas/AddAudioMetadataRequest'
      responses:
        200:
          description: Audio file and metadata accepted
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

components:
  schemas:
    AudioMetadata:
      type: object
      properties:
        id:
          type: integer
          example: 1
        media_start_timestamp:
          type: string
          format: date-time
        media_end_timestamp:
          type: string
          format: date-time
    AddAudioMetadataRequest:
      type: object
      required:
        - started_at
        - ended_at
        - channel
        - total_channels
        - format
        - filename
        - courthouse
        - courtroom
        - cases
        - file_size
      properties:
        started_at:
          type: string
          format: date-time
          description: 'Start timestamp of the audio recording'
        ended_at:
          type: string
          format: date-time
          description: 'End timestamp of the audio recording'
        channel:
          type: integer
          format: int32
          description: 'Channel number of the audio recording'
        total_channels:
          type: integer
          format: int32
          description: 'Number of channels making up the complete audio that this recording is part of'
        format:
          type: string
          description: 'Media format of the audio recording'
          maxLength: 64
        filename:
          type: string
          description: 'Filename of the audio recording'
          maxLength: 255
        courthouse:
          type: string
          description: 'Courthouse the audio was recorded in'
          maxLength: 255
        courtroom:
          type: string
          description: 'Courtroom the audio was recorded in'
          maxLength: 64
        media_file:
          type: string
          description: 'The file for the audio'
          maxLength: 255
        file_size:
          type: integer
          format: int64
          description: 'The size of the file in bytes'
        checksum:
          type: string
          description: 'Checksum to ensure integrity of file'
          maxLength: 255
        cases:
          type: array
          items:
            type: string
          description: 'List of associated case numbers'
          minItems: 1
          maxLength: 255

