openapi: 3.0.1

servers:
  - url: http://localhost:4550/

info:
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
  version: ${version}
  title: Modernised DARTS

paths:
  /audio-requests:
    post:
      tags:
        - Audio
      summary: Users can request audio for specific cases and date/time periods
      operationId: addAudioRequest
      description: Adds a user audio request for processing
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddAudioResponse'
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: audio request item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AudioRequestDetails'
        description: Audio Request item to add

  /audio/download:
    get:
      tags:
        - Audio
      summary: Download audio
      operationId: download
      description: Download audio
      parameters:
        - in: query
          name: media_request_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_103"
                title: "Failed to check authorisation for the media request"
                status: 400
        '401':
          description: Unauthorised Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 401
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_REQUESTS_100"
                title: "The requested audio request cannot be found"
                status: 404
        '500':
          description: The requested data cannot be located
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_101"
                title: "The requested data cannot be located"
                status: 500

  /audio/hearings/{hearing_id}/audios:
    get:
      tags:
        - Audio
      summary: Media metadata for provided hearing
      operationId: getAudioMetadata
      description: Media metadata for provided hearing
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AudioMetadata'
              examples:
                media-found:
                  summary: Media metadata exists for the given hearing id
                  value:
                    - id: 1
                      media_start_timestamp: '2023-07-31T14:32:24.620Z'
                      media_end_timestamp: '2023-07-31T14:32:24.620Z'
                media-not-found:
                  summary: No media metadata exists for the given hearing id
                  value:
                    [ ]
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_102"
                title: "Failed to check authorisation for the hearing"
                status: 400
        '401':
          description: Unauthorised Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 401
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "HEARING_100"
                title: "The requested hearing cannot be found"
                status: 404
  /audio/preview/{media_id}:
    get:
      tags:
        - Audio
      summary: Preview audio
      operationId: preview
      description: Preview audio
      parameters:
        - in: path
          name: media_id
          schema:
            type: integer
          required: true
          description: "Internal identifier for media"
          example: 1
      responses:
        200:
          description: OK
          content:
            audio/mp3:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_104"
                title: "Failed to check authorisation for the media"
                status: 400
        '401':
          description: Unauthorised Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 401
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_102"
                title: "The requested media cannot be found"
                status: 404
        500:
          description: The requested data cannot be located
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_101"
                title: "The requested data cannot be located"
                status: 500
  /audios:
    post:
      tags:
        - audio
      summary: Upload audio metadata
      operationId: addAudioMetaData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddAudioMetadataRequest'
      responses:
        200:
          description: Audio metadata accepted
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

components:
  schemas:
    AudioRequestType:
      type: string
      enum:
        - DOWNLOAD
        - PLAYBACK
    AudioRequestDetails:
      type: object
      required:
        - hearing_id
        - requestor
        - start_time
        - end_time
        - request_type
      properties:
        hearing_id:
          type: integer
          example: 12345
        requestor:
          type: integer
          example: 4656
        start_time:
          type: string
          format: date-time
          example: '2023-05-31T09:00:00Z'
        end_time:
          type: string
          format: date-time
          example: '2023-05-31T12:00:00Z'
        request_type:
          $ref: '#/components/schemas/AudioRequestType'

    AudioMetadata:
      type: object
      properties:
        id:
          type: integer
          example: 1
        media_start_timestamp:
          type: string
          format: date-time
        media_end_timestamp:
          type: string
          format: date-time
    AddAudioResponse:
      type: object
      required:
        - request_id
        - case_id
        - courthouse_name
        - defendants
        - hearing_date
        - start_time
        - end_time
      properties:
        request_id:
          type: integer
          example: 1234
        case_id:
          type: integer
          example: 1
        case_number:
          type: string
          example: 'T4565443'
        courthouse_name:
          type: string
          example: "Swansea"
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        hearing_date:
          type: string
          format: date
          example: '10-05-2023'
        start_time:
          type: string
          format: date-time
          example: '2023-05-31T09:00:00Z'
        end_time:
          type: string
          format: date-time
          example: '2023-05-31T10:00:00Z'
    defendant:
      type: string
      example: Joe Bloggs
    AddAudioMetadataRequest:
      type: object
      required:
        - started_at
        - ended_at
        - channel
        - total_channels
        - format
        - filename
        - courthouse
        - courtroom
        - cases
      properties:
        started_at:
          type: string
          format: date-time
          description: 'Start timestamp of the audio recording'
        ended_at:
          type: string
          format: date-time
          description: 'End timestamp of the audio recording'
        channel:
          type: integer
          format: int32
          description: 'Channel number of the audio recording'
        total_channels:
          type: integer
          format: int32
          description: 'Number of channels making up the complete audio that this recording is part of'
        format:
          type: string
          description: 'Media format of the audio recording'
          maxLength: 64
        filename:
          type: string
          description: 'Filename of the audio recording'
          maxLength: 255
        courthouse:
          type: string
          description: 'Courthouse the audio was recorded in'
          maxLength: 255
        courtroom:
          type: string
          description: 'Courtroom the audio was recorded in'
          maxLength: 64
        cases:
          type: array
          items:
            type: string
          description: 'List of associated case numbers'
          minItems: 1
          maxLength: 255
