openapi: 3.0.1

servers:
  - url: http://localhost:4550/

info:
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
  version: ${version}
  title: Modernised DARTS

paths:
  /audio/hearings/{hearing_id}/audios:
    get:
      tags:
        - Audio
      summary: Media metadata for provided hearing
      operationId: getAudioMetadata
      description: Media metadata for provided hearing
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AudioMetadata'
              examples:
                media-found:
                  summary: Media metadata exists for the given hearing id
                  value:
                    - id: 1
                      media_start_timestamp: '2023-07-31T14:32:24.620Z'
                      media_end_timestamp: '2023-07-31T14:32:24.620Z'
                      is_archived: true
                      is_available: true
                media-not-found:
                  summary: No media metadata exists for the given hearing id
                  value:
                    [ ]
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_102"
                title: "Failed to check authorisation for the hearing"
                status: 400
        '401':
          description: Unauthorised Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 401
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "HEARING_100"
                title: "The requested hearing cannot be found"
                status: 404
  /audio/preview/{media_id}:
    get:
      tags:
        - Audio
      summary: Preview audio
      operationId: preview
      description: Preview audio. Use text/event-stream accept type to use send server events.
      parameters:
        - in: path
          name: media_id
          schema:
            type: integer
          required: true
          description: "Internal identifier for media"
          example: 1
        - in: header
          name: range
          schema:
            type: string
          description: "Range header, required for streaming audio."
      responses:
        200:
          description: OK
          content:
            audio/mpeg:
              schema:
                type: string
                format: byte
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_104"
                title: "Failed to check authorisation for the media"
                status: 400
        '401':
          description: Unauthorised Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 401
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_102"
                title: "The requested media cannot be found"
                status: 404
        500:
          description: The requested data cannot be located
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_101"
                title: "The requested data cannot be located"
                status: 500
  /audios:
    post:
      tags:
        - Audio
      summary: Upload audio file and metadata
      operationId: addAudio
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                metadata:
                  $ref: '#/components/schemas/AddAudioMetadataRequest'
      responses:
        200:
          description: Audio file and metadata accepted
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /admin/transformed-medias/{id}:
    get:
      tags:
        - Audio
      summary: Admin get transformed media
      operationId: adminGetTransformedMedia
      description: Returns a specific transformed media details
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransformedMediaResponse'
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_REQUESTS_103"
                title: "The requested transformed media cannot be found"
                status: 404
  /admin/medias:
    get:
      tags:
        - Audio
      summary: Search for Media
      operationId: getAdminMedias
      description: Returns a representation of the media table which match the supplied search criteria.
      parameters:
        - in: query
          name: transformed_media_id
          schema:
            type: integer
          description: "Return media associated with this transformed_media_id. <p>*Conditional Mandatory* Either this or transcription_document_id must be provided"
        - in: query
          name: transcription_document_id
          schema:
            type: integer
          description: "Return only media associated with the provided transcription document. <p>*Conditional Mandatory* Either this or transformed_media_id must be provided"

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdminMediaSearchResponseItem'
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUDIO_100"
                title: "Either media_request_id or transcription_document_id must be provided in the request."
                status: 400
        '401':
          description: Unauthorised Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 401
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "HEARING_100"
                title: "The requested hearing cannot be found"
                status: 404
components:
  schemas:
    AdminMediaSearchResponseItem:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: med_id
        channel:
          type: integer
          example: 1
        start_at:
          type: string
          format: date-time
        end_at:
          type: string
          format: date-time
        case:
          $ref: '#/components/schemas/AdminMediaSearchResponseCase'
        hearing:
          $ref: '#/components/schemas/AdminMediaSearchResponseHearing'
        courthouse:
          $ref: '#/components/schemas/AdminMediaSearchResponseCourthouse'
        courtroom:
          $ref: '#/components/schemas/AdminMediaSearchResponseCourtroom'

    AdminMediaSearchResponseCase:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: med_id
        case_number:
          type: string

    AdminMediaSearchResponseHearing:
      type: object
      properties:
        id:
          type: integer
          example: 1
        hearing_date:
          type: string
          format: date

    AdminMediaSearchResponseCourthouse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        display_name:
          type: string

    AdminMediaSearchResponseCourtroom:
      type: object
      properties:
        id:
          type: integer
          example: 1
        display_name:
          type: string

    AudioMetadata:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: med_id
        media_start_timestamp:
          type: string
          format: date-time
        media_end_timestamp:
          type: string
          format: date-time
        is_archived:
          type: boolean
        is_available:
          type: boolean
        file_size:
          type: integer
          format: int64
    AddAudioMetadataRequest:
      type: object
      required:
        - started_at
        - ended_at
        - channel
        - total_channels
        - format
        - filename
        - courthouse
        - courtroom
        - cases
        - file_size
      properties:
        started_at:
          type: string
          format: date-time
          description: 'Start timestamp of the audio recording'
        ended_at:
          type: string
          format: date-time
          description: 'End timestamp of the audio recording'
        channel:
          type: integer
          format: int32
          description: 'Channel number of the audio recording'
        total_channels:
          type: integer
          format: int32
          description: 'Number of channels making up the complete audio that this recording is part of'
        format:
          type: string
          description: 'Media format of the audio recording'
          maxLength: 64
        filename:
          type: string
          description: 'Filename of the audio recording'
          maxLength: 255
        courthouse:
          type: string
          description: 'Courthouse the audio was recorded in'
          maxLength: 255
        courtroom:
          type: string
          description: 'Courtroom the audio was recorded in'
          maxLength: 64
        media_file:
          type: string
          description: 'The file for the audio'
          maxLength: 255
        file_size:
          type: integer
          format: int64
          description: 'The size of the file in bytes'
        checksum:
          type: string
          description: 'Checksum to ensure integrity of file'
          maxLength: 255
        cases:
          type: array
          items:
            type: string
          description: 'List of associated case numbers'
          minItems: 1
          maxLength: 255
    GetTransformedMediaResponse:
      type: object
      properties:
        id:
          type: integer
        file_name:
          type: string
        file_format:
          type: string
        file_size_bytes:
          type: integer
        case_id:
          type: integer
        media_request_id:
          type: integer

    AddAudioErrorCode:
      type: string
      enum:
        - "AUDIO_100"
        - "AUDIO_101"
        - "AUDIO_102"
        - "AUDIO_103"
        - "AUDIO_104"
        - "AUDIO_105"
        - "AUDIO_106"
        - "AUDIO_107"
        - "AUDIO_108"
        - "AUDIO_109"
        - "AUDIO_110"
      x-enum-varnames: [ FAILED_TO_PROCESS_AUDIO_REQUEST, REQUESTED_DATA_CANNOT_BE_LOCATED, MEDIA_NOT_FOUND, FAILED_TO_UPLOAD_AUDIO_FILE,
                         MISSING_SYSTEM_USER, AUDIO_NOT_PROVIDED, UNEXPECTED_FILE_TYPE, FILE_DURATION_OUT_OF_BOUNDS, FILE_SIZE_OUT_OF_BOUNDS, ADMIN_SEARCH_CRITERIA_NOT_PROVIDED ]

    AddAudioTitleErrors:
      type: string
      enum:
        - "Failed to process audio request"
        - "The requested data cannot be located"
        - "The requested media cannot be found"
        - "Failed to store uploaded audio file"
        - "Failed to mark audio(s) for deletion as system user was not found"
        - "Audio not found"
        - "The file type is not acceptable"
        - "The duration of the audio exceeds maximum threshold"
        - "The audio metadata size exceeds maximum threshold"
        - "Either media_request_id or transcription_document_id must be provided in the request, but not both."
      x-enum-varnames: [ FAILED_TO_PROCESS_AUDIO_REQUEST, REQUESTED_DATA_CANNOT_BE_LOCATED,  MEDIA_NOT_FOUND,
                         FAILED_TO_UPLOAD_AUDIO_FILE, MISSING_SYSTEM_USER, AUDIO_NOT_PROVIDED, UNEXPECTED_FILE_TYPE,
                         FILE_DURATION_OUT_OF_BOUNDS, FILE_SIZE_OUT_OF_BOUNDS, ADMIN_SEARCH_CRITERIA_NOT_PROVIDED ]