openapi: 3.0.1

servers:
  - url: http://localhost:4550/

info:
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
  version: "0.0.1"
  title: Modernised DARTS

paths:
  /audio/request:
    post:
      tags:
        - AudioRequests
      summary: Users can request audio for specific cases and date/time periods
      operationId: addAudioRequest
      description: Adds a user audio request for processing
      responses:
        '201':
          description: audio request created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: audio request item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AudioRequestDetails'
        description: Audio Request item to add

components:
  schemas:
    AudioRequestType:
      type: string
      enum:
        - DOWNLOAD
        - PLAYBACK

    AudioRequestDetails:
      type: object
      required:
        - hearingId
        - requestor
        - startTime
        - endTime
        - requestType
      properties:
        hearingId:
          type: integer
          example: 12345
        requestor:
          type: integer
          example: 4656
        startTime:
          type: string
          format: date-time
          example: '2023-05-31T09:00:00Z'
        endTime:
          type: string
          format: date-time
          example: '2023-05-31T12:00:00Z'
        requestType:
          $ref: '#/components/schemas/AudioRequestType'
