openapi: 3.0.1

servers:
  - url: http://localhost:4550/
info:
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
  version: "0.0.1"
  title: Modernised DARTS

paths:
  /audit/search:
    get:
      tags:
        - Audit
      summary: User can search through audit logs using various filters.
      operationId: search
      description: Searches through the audit log based on the filters provided.
      parameters:
        - in: query
          name: from_date
          schema:
            type: string
            format: date-time
        - in: query
          name: to_date
          schema:
            type: string
            format: date-time
        - in: query
          name: case_id
          schema:
            type: integer
        - in: query
          name: event_id
          schema:
            type: integer
      responses:
        '200':
          description: Audit logs returned matching filters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          description: 'At least one filter parameter was not provided or an invalid datatype or value was provided for property.'
        '500':
          description: Internal Server Error
components:
  schemas:
    SearchResponse:
      type: array
      items:
        $ref: '#/components/schemas/SearchResult'
    SearchResult:
      type: object
      properties:
        id:
          type: integer
        case_id:
          type: integer
        created_at:
          type: string
          format: date-time
          example: '2023-05-31T09:00:00Z'
        event_id:
          type: integer
        user_id:
          type: integer
        application_server:
          type: string
        additional_data:
          type: string
    AuditSearchQuery:
      type: object
      properties:
        case_id:
          type: integer
        from_date:
          type: string
          format: date-time
          example: '2023-05-31T09:00:00Z'
        to_date:
          type: string
          format: date-time
          example: '2023-05-31T09:00:00Z'
        event_id:
          type: integer
