openapi: 3.0.1

info:

  version: 0.0.1
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/


paths:
  /cases:
    get:
      tags:
        - Cases
      summary: Allows the retrieval of all scheduled cases/hearings for a given courthouse, courtroom and date
      parameters:
        - in: query
          name: courthouse
          schema:
            type: string
          description: "The name of the courthouse"
          example: "SWANSEA"
          required: true
        - in: query
          name: courtroom
          schema:
            type: string
          description: "The name of the courtroom"
          example: "1"
          required: true
        - in: query
          name: date
          schema:
            type: string
            format: date
          description: "The date to get the cases for. Normally today"
          example: 2023-06-22
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cases'
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
    post:
      tags:
        - Cases
      summary: Allows user to add case or if the case exists update the details.
      description: |-
        Allows user to add case or if the case exists update the details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add_case_request'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post_case_response'
        '400':
          description: A required parameter is missing or an invalid datatype or value was provided for property.
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "COMMON_100"
                title: "Provided courthouse does not exist"
                status: 400
                detail: "Courthouse '' not found."
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /cases/{caseId}:
    get:
      tags:
        - Cases
      summary: Allows the retrieval of a single case using a given caseId
      description: |-
        Retrieves a single case for a given caseId
      parameters:
        - in: path
          name: caseId
          schema:
            type: integer
          description: "caseId is the internal cas_id of the case."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_case'
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /cases/{caseId}/hearings:
    get:
      tags:
        - Cases
      summary: Allows the retrieval of hearings for a given caseId
      description: |-
        Retrieves all hearings for a caseId.
      parameters:
        - in: path
          name: caseId
          schema:
            type: integer
          description: "caseId is the internal cas_id of the case."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hearings'
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /cases/search:
    get:
      tags:
        - Cases
      summary: Advanced Search
      description: |-
        Allows cases to be searched for using partial case numbers, defendant names, etc.
        All string can be partial matches, and case insensitive.
      parameters:
        - in: query
          name: case_number
          schema:
            type: string
            maxLength: 20
          description: "Full or partial Case Number"
          example: "C202305"
        - in: query
          name: courthouse
          schema:
            type: string
            maxLength: 30
          description: "Full or partial Courthouse name. If this is used, then at least 1 more criteria should be added."
          example: "Swansea"
        - in: query
          name: courtroom
          schema:
            type: string
            maxLength: 30
          description: "Full or partial Courtroom name. If this is used, then at least 1 more criteria should be added."
          example: "1"
        - in: query
          name: judge_name
          schema:
            type: string
            maxLength: 30
          description: "Full or partial Judge name"
          example: "Judy"
        - in: query
          name: defendant_name
          schema:
            type: string
            maxLength: 30
          description: "Full or partial Defendant name"
          example: "bloggs"
        - in: query
          name: date_from
          schema:
            type: string
            format: date
          description: "DateFrom to search for the hearings in."
          example: 2023-01-22
        - in: query
          name: date_to
          schema:
            type: string
            format: date
          description: "DateTo to search for the hearings in. This should be on or after the date_from if both have been provided."
          example: 2023-06-22
        - in: query
          name: event_text_contains
          schema:
            type: string
            maxLength: 100
          description: "Full or partial event_text"
          example: ""
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/advancedSearchResult'
        '400':
          description: A required parameter is missing or an invalid.
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "CASE_100"
                title: "Too many results have been returned. Please change search criteria."
                status: 400
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

components:
  schemas:
    add_case_request:
      type: object
      required:
        - courthouse
        - case_number
      properties:
        courthouse:
          type: string
          example: SWANSEA
        case_number:
          type: string
          example: CASE1001
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defence'
    cases:
      type: array
      items:
        $ref: '#/components/schemas/scheduled_case'
    scheduled_case:
      type: object
      required:
        - courthouse
      properties:
        courthouse:
          type: string
          example: SWANSEA
        courtroom:
          type: string
          example: 1
        hearing_date:
          type: string
          format: date
          example: 2023-06-23
        case_number:
          type: string
          example: CASE1001
        scheduled_start:
          type: string
          format: time
          example: 10:00
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defence'
    post_case_response:
      type: object
      properties:
        courthouse:
          type: string
          example: SWANSEA
        case_number:
          type: string
          example: CASE1001
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defence'
    single_case:
      type: object
      required:
        - courthouse
      properties:
        case_id:
          type: integer
          example: 1
        courthouse:
          type: string
          example: SWANSEA
        case_number:
          type: string
          example: CASE1001
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defence'
        retain_until:
          type: string
          format: date-time
    advancedSearchResult:
      type: object
      properties:
        caseID:
          type: integer
          example: 1
          description: Unique case identifier, used internally by DARTS.
        caseNumber:
          type: string
          example: C20220620001
          description: 'Case Number'
        courthouse:
          type: string
          example: SWANSEA
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        reportingRestriction:
          type: string
          example: "Section 4(2) of the Contempt of Court Act 1981"
          description: 'Any reporting restrictions associated with the case.'
        hearings:
          type: array
          items:
            $ref: '#/components/schemas/advancedSearchResultHearing'
    advancedSearchResultHearing:
      type: object
      properties:
        id:
          type: integer
          example: 1
        date:
          type: string
          format: date
          example: 2022-05-20
        courtroom:
          type: string
          example: 1
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
    defendant:
      type: string
      example: Joe Bloggs
    judge:
      type: string
      example: Mr Judge
    prosecutor:
      type: string
      example: Mrs Prosecutor
    defence:
      type: string
      example: Mr Defender
    hearings:
      type: array
      items:
        $ref: '#/components/schemas/hearing'
    hearing:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        courtroom:
          type: string
        transcriptCount:
          type: integer
