openapi: 3.0.1

info:

  version: ${version}
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/


paths:
  /cases:
    get:
      tags:
        - Cases
      summary: Allows the retrieval of all scheduled cases/hearings for a given courthouse, courtroom and date
      parameters:
        - in: query
          name: courthouse
          schema:
            type: string
          description: "The name of the courthouse"
          example: "SWANSEA"
          required: true
        - in: query
          name: courtroom
          schema:
            type: string
          description: "The name of the courtroom"
          example: "1"
          required: true
        - in: query
          name: date
          schema:
            type: string
            format: date
          description: "The date to get the cases for. Normally today"
          example: 2023-06-22
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cases'

        '400':
          description: A required parameter is missing or an invalid datatype or value was provided for property.
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "COMMON_100"
                title: "Provided courthouse does not exist"
                status: 400
                detail: "Courthouse '' not found."

        '404':
          description: Not Found
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
    post:
      tags:
        - Cases
      summary: Allows user to add case or if the case exists update the details.
      description: |-
        Allows user to add case or if the case exists update the details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add_case_request'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post_case_response'

        '400':
          description: Bad Request - Invalid XML Document
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

        '404':
          description: Not Found - Courthouse not found
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'


  /cases/{case_id}:
    get:
      tags:
        - Cases
      summary: Allows the retrieval of a single case using a given case_id
      description: |-
        Retrieves a single case for a given case_id
      parameters:
        - in: path
          name: case_id
          schema:
            type: integer
          description: "case_id is the internal cas_id of the case."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_case'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/CasesAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "CASE_104"
                title: "The requested case cannot be found"
                status: 404

    patch:
      tags:
        - Cases
      summary: Allows the update of a single case using a given case_id
      description: |-
        Patches a single case for a given case_id
      parameters:
        - in: path
          name: case_id
          schema:
            type: integer
          description: "case_id is the internal cas_id of the case."
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/patch_request_object'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_case'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/CasesAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /cases/{case_id}/hearings:
    get:
      tags:
        - Cases
      summary: Allows the retrieval of hearings for a given case_id
      description: |-
        Retrieves all hearings for a case_id.
      parameters:
        - in: path
          name: case_id
          schema:
            type: integer
          description: "case_id is the internal cas_id of the case."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hearings'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/CasesAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /cases/{case_id}/transcripts:
    get:
      tags:
        - Cases
      summary: Allows the retrieval of transcripts for a given case_id
      description: |-
        Retrieves all transcripts for a case_id.
      parameters:
        - in: path
          name: case_id
          schema:
            type: integer
          description: "case_id is the internal cas_id of the case."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transcripts'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/CasesAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "CASE_104"
                title: "The requested case cannot be found"
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /cases/search:
    post:
      tags:
        - Cases
      summary: |-
        Allows cases to be searched for using partial case numbers, defendant names, etc.
        All string can be partial matches, and case insensitive.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdvancedSearchDetails'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/advancedSearchResult'
        '400':
          description: A required parameter is missing or an invalid datatype or value was provided for property.
        '409':
          description: Resource already exists.
        '500':
          description: Internal Server Error
components:
  schemas:
    add_case_request:
      type: object
      required:
        - courthouse
        - case_number
      properties:
        courthouse:
          type: string
          example: SWANSEA
        case_number:
          type: string
          example: CASE1001
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defence'
    cases:
      type: array
      items:
        $ref: '#/components/schemas/scheduled_case'
    scheduled_case:
      type: object
      required:
        - courthouse
      properties:
        courthouse:
          type: string
          example: SWANSEA
        courtroom:
          type: string
          example: 1
        hearing_date:
          type: string
          format: date
          example: 2023-06-23
        case_number:
          type: string
          example: CASE1001
        scheduled_start:
          type: string
          format: time
          example: 10:00
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defence'
    post_case_response:
      type: object
      properties:
        case_id:
          type: integer
          example: 1001
        courthouse:
          type: string
          example: SWANSEA
        case_number:
          type: string
          example: CASE1001
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defence'
    patch_request_object:
      type: object
      properties:
        retain_until:
          type: string
          format: date-time
    single_case:
      type: object
      required:
        - courthouse
      properties:
        case_id:
          type: integer
          example: 1
        courthouse:
          type: string
          example: SWANSEA
        case_number:
          type: string
          example: CASE1001
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defence'
        reporting_restrictions:
          $ref: './common.yaml#/components/schemas/reporting_restrictions'
        retain_until_date_time:
          type: string
          format: date-time
          example: 2030-01-31T15:42:10.361Z
        case_closed_date_time:
          type: string
          format: date-time
          example: 2023-07-20T15:42:10.361Z
        retention_date_time_applied:
          type: string
          format: date-time
          example: 2023-07-20T15:42:10.361Z
        retention_policy_applied:
          type: string
          example: "MANUAL"
    advancedSearchResult:
      type: object
      properties:
        case_id:
          type: integer
          example: 1
          description: Unique case identifier, used internally by DARTS.
        case_number:
          type: string
          example: C20220620001
          description: 'Case Number'
        courthouse:
          type: string
          example: SWANSEA
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        reporting_restriction:
          type: string
          example: "Section 4(2) of the Contempt of Court Act 1981"
          description: 'Any reporting restrictions associated with the case.'
        hearings:
          type: array
          items:
            $ref: '#/components/schemas/advancedSearchResultHearing'
    advancedSearchResultHearing:
      type: object
      properties:
        id:
          type: integer
          example: 1
        date:
          type: string
          format: date
          example: 2022-05-20
        courtroom:
          type: string
          example: 1
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
    transcripts:
      type: array
      items:
        $ref: '#/components/schemas/transcript'
    transcript:
      type: object
      properties:
        transcription_id:
          type: integer
          example: 1
        hearing_id:
          type: integer
          example: 2
        hearing_date:
          type: string
          format: date
          example: 2022-05-20
        type:
          type: string
          example: "Sentencing remarks"
        requested_on:
          type: string
          format: date-time
          example: 2023-06-20T10:00:00Z
        requested_by_name:
          type: string
          example: "Joe Bloggs"
        status:
          type: string
          example: "Available"
    defendant:
      type: string
      example: Joe Bloggs
    judge:
      type: string
      example: Mr Judge
    prosecutor:
      type: string
      example: Mrs Prosecutor
    defence:
      type: string
      example: Mr Defender
    hearings:
      type: array
      items:
        $ref: '#/components/schemas/hearing'
    hearing:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        courtroom:
          type: string
        transcript_count:
          type: integer

    AdvancedSearchDetails:
      type: object
      properties:
        case_number:
          type: string
          example: 1234
          maxLength: 32
        courthouse:
          type: string
          example: Swansea
          maxLength: 255
        courtroom:
          type: string
          example: 2
          maxLength: 255
        judge_name:
          type: string
          example: Judge Walker
          maxLength: 255
        defendant_name:
          type: string
          example: 'David Defendant'
          maxLength: 255
        date_from:
          type: string
          format: date
        date_to:
          type: string
          format: date
        event_text_contains:
          type: string
          example: 'Event text'
          maxLength: 255

    PostCasesErrorCode:
      type: string
      enum:
        - "ADD_CASE_101"
        - "ADD_CASE_102"
      x-enum-varnames: [ CASE_COURT_HOUSE_NOT_FOUND, CASE_DOCUMENT_CANT_BE_PARSED ]

    GetCasesErrorCode:
      type: string
      enum:
        - "GET_CASE_101"
      x-enum-varnames: [ CASE_COURT_HOUSE_NOT_FOUND ]

    CasesAuthorisation403ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_100"
      x-enum-varnames: [ USER_NOT_AUTHORISED_FOR_COURTHOUSE ]
