openapi: 3.0.1

info:

  version: 0.0.1
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/


paths:
  /cases:
    get:
      tags:
        - Cases
      summary: Allows the retrieval of all cases for a given courthouse, courtroom and date
      description: |-
        Retrieves all cases for a given courthouse, courtroom and date
      parameters:
        - in: query
          name: courthouse
          schema:
            type: string
          description: "The name of the courthouse"
          example: "SWANSEA"
          required: true
        - in: query
          name: courtroom
          schema:
            type: string
          description: "The name of the courtroom"
          example: "1"
          required: true
        - in: query
          name: date
          schema:
            type: string
            format: date
          description: "The date to get the cases for. Normally today"
          example: 2023-06-22
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cases'

        '500':
          description: Internal Server Error

  /cases/search:
    get:
      tags:
        - Cases
      summary: Advanced Search
      description: |-
        Allows cases to be searched for using partial case numbers, defendant names, etc.
        All string can be partial matches, and case insensitive.
      parameters:
        - in: query
          name: case_number
          schema:
            type: string
          description: "Full or partial Case Number"
          example: "C202305"
        - in: query
          name: courthouse
          schema:
            type: string
          description: "Full or partial Courthouse name"
          example: "Swansea"
        - in: query
          name: courtroom
          schema:
            type: string
          description: "Full or partial Courtroom name"
          example: "1"
        - in: query
          name: judge_name
          schema:
            type: string
          description: "Full or partial Judge name"
          example: "Judy"
        - in: query
          name: defendant_name
          schema:
            type: string
          description: "Full or partial Defendant name"
          example: "bloggs"
        - in: query
          name: date_from
          schema:
            type: string
            format: date
          description: "DateFrom to search for the hearings in."
          example: 2023-01-22
        - in: query
          name: date_to
          schema:
            type: string
            format: date
          description: "DateTo to search for the hearings in."
          example: 2023-06-22
        - in: query
          name: keywords
          schema:
            type: string
          description: "Full or partial event_name and event_text"
          example: ""
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/advancedSearchResult'

        '500':
          description: Internal Server Error


components:

  #-----------------#
  #----------------------------------#
  #-----------------#

  schemas:
    cases:
      type: array
      items:
        $ref: '#/components/schemas/scheduled_case'
    scheduled_case:
      type: object
      properties:
        courthouse:
          type: string
          example: SWANSEA
        courtroom:
          type: string
          example: 1
        hearing_date:
          type: string
          format: date
          example: 2023-06-23
        case_number:
          type: string
          example: CASE1001
        scheduled_start:
          type: string
          format: time
          example: 10:00
        upload_priority:
          type: string
          example:
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        prosecutors:
          type: array
          items:
            $ref: '#/components/schemas/prosecutor'
        defenders:
          type: array
          items:
            $ref: '#/components/schemas/defender'

    advancedSearchResult:
      type: object
      properties:
        caseID:
          type: integer
          example: 1
          description: Unique case identifier, used internally by DARTS.
        caseNumber:
          type: string
          example: C20220620001
          description: 'Case Number'
        courthouse:
          type: string
          example: SWANSEA
        courtrooms:
          type: array
          items:
            type: string
          example: [1]
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        defendants:
          type: array
          items:
            $ref: '#/components/schemas/defendant'
        hearingDates:
          type: array
          items:
            type: string
            format: date
        reportingRestriction:
          type: string
          example: C20220620001
          description: 'Any reporting restrictions associated with the case.'

    defendant:
      type: string
      example: Joe Bloggs
    judge:
      type: string
      example: Mr Judge
    prosecutor:
      type: string
      example: Mrs Prosecutor
    defender:
      type: string
      example: Mr Defender

