openapi: 3.0.1
info:
  version: 0.0.1
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).
servers:
  - url: http://localhost:4550/
paths:
  /courthouses:
    post:
      tags:
        - Courthouses
      summary: Adds a courthouse record with supplied details.
      requestBody:
        $ref: '#/components/requestBodies/CourtHousePost'
      responses:
        '201':
          description: Created
        '500':
          description: Internal Server Error
    get:
      tags:
        - Courthouses
      summary: Gets all court house records..
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourtList'
        '500':
          description: Internal Server Error

  /courthouses/{courthouse_id}:
    put:
      tags:
        - Courthouses
      summary: Amends a court house record with supplied details.
      parameters:
        - in: path
          name: courthouse_id
          schema:
            type: integer
          required: true
      requestBody:
        $ref: '#/components/requestBodies/CourtHousePost'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourtList'
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Courthouses
      summary: Deletes the court house entery with the supplied id.
      parameters:
        - in: path
          name: courthouse_id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: OK
        '500':
          description: Internal Server Error


components:
  requestBodies:
    CourtHousePost:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CourtHouse'
  schemas:
    CourtHouse:
      type: object
      properties:
        courthouse_name:
          type: string
        code:
          type: integer
    ExtendedCourtHouse:
      allOf:
        - $ref: '#/components/schemas/CourtHouse'
        - type: object
          properties:
            id:
              type: integer
            created:
              type: string
            modified:
              type: string

    CourtList:
      type: array
      items:
        $ref: '#/components/schemas/ExtendedCourtHouse'
