openapi: 3.0.1

info:

  version: 0.0.1
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/


paths:
  /event/addDocument:
    post:
      tags:
        - Event
      summary: An Endpoint which allows users to request audio by case and hearing data
      description: |-
        Event data received from XHIBIT and CPP through a custom web service to add context to the audio recordings it stores, which allows users to request audio by case and hearing data without needing to know the time or physical location of where the audio was recorded.
      parameters:
        - in: query
          name: message_id
          schema:
            type: number
          description: "message id"
          required: true
        - in: query
          name: type
          schema:
            type: string
          description: "The type of Event"
          required: true
        - in: query
          name: sub_type
          schema:
            type: string
          description: "The subtype of Event"
          required: true
      requestBody:
        $ref: '#/components/requestBodies/AddDocumentBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddDocumentResponse'

        '500':
          description: Internal Server Error

components:
  requestBodies:
    AddDocumentBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DocumentXML'


    #-----------------#
    #----------------------------------#
    #-----------------#

  schemas:
    DocumentXML:
      type: string

    AddDocumentResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
