openapi: 3.0.1

info:

  version: ${version}
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/

paths:
  /events:
    post:
      tags:
        - Event
      summary: An Endpoint which allows users to request and submit events.
      description: |-
        Event data received from XHIBIT and CPP through a custom web service to add context to the audio recordings it stores.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DartsEvent'
            examples:
              example1:
                summary: Case called on
                value:
                  message_id: '18422'
                  type: '10100'
                  sub_type: '10100'
                  event_id: '001'
                  courthouse: SNARESBROOK
                  courtroom: '1'
                  case_numbers:
                    - A20230049
                  date_time: '2023-06-14T08:37:30.945Z'
              example2:
                summary: Freetext
                value:
                  message_id: '18422'
                  type: '21300'
                  sub_type: '21300'
                  event_id: '002'
                  courthouse: SNARESBROOK
                  courtroom: '1'
                  case_numbers:
                    - T20190441
                  event_text: 'test'
                  date_time: '2023-06-14T08:37:30.945Z'
              example3:
                summary: Life Imprisonment
                value:
                  message_id: '18422'
                  type: '40750'
                  sub_type: '11504'
                  event_id: '003'
                  courthouse: SNARESBROOK
                  courtroom: '1'
                  case_numbers:
                    - T20190441
                  event_text: '[Defendant: DEFENDANT ONE]'
                  date_time: '2023-06-14T08:37:30.945Z'
                  retention_policy:
                    CaseRetentionFixedPolicy: 4
                    CaseTotalSentence: 26Y0M0D

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsResponse'

        '400':
          description: Bad Request- Invalid XML Document
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

        '404':
          description: Not Found - Courthouse not found
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              examples:
                example1:
                  summary: Not in database
                  description: type+subType has not been found in the database
                  value:
                    type: EVENT_101
                    title: No event handler found in database
                    status: 404
                    detail: "No event handler could be found for messageId: 100 type: 407301 and subtype: 108081"

        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /courtlogs:
    get:
      tags:
        - Event
      summary: An Endpoint which allows users to request event courtlogs
      description: |-
        An Endpoint which allows users to request courtlogs using courthouse, casenumber, startdate and enddate
      parameters:
        - in: query
          name: courthouse
          schema:
            type: string
          required: true
        - in: query
          name: case_number
          schema:
            type: string
          required: true
        - in: query
          name: start_date_time
          schema:
            type: string
            format: date-time
          required: true
        - in: query
          name: end_date_time
          schema:
            type: string
            format: date-time
          required: true


      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourtLogs'

        '404':
          description: Not Found - Courthouse not found
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'


    post:
      tags:
        - Event
      summary: An Endpoint which allows users to create a court log event.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourtLogsPostRequestBody'
            examples:
              example1:
                summary: Request with single case
                value:
                  log_entry_date_time: '2023-05-23T09:15:25Z'
                  courthouse: CARDIFF
                  courtroom: '1'
                  case_numbers:
                    - CASE1001
                  text: 'System : Start Recording : Record: Case Code:0008, New Case'
              example2:
                summary: Request with multiple cases
                value:
                  log_entry_date_time: '2023-05-23T09:15:25Z'
                  courthouse: CARDIFF
                  courtroom: '1'
                  case_numbers:
                    - CASE1001
                    - CASE1002
                  text: 'System : Start Recording : Record: Case Code:0008, New Case'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsResponse'

        '400':
          description: Bad Request- Invalid XML Document
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

        '404':
          description: Not Found - Courthouse not found
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'


components:
  schemas:

    ###################################################################################################################
    # TOP-LEVEL MODELS
    ###################################################################################################################

    CourtLogsPostRequestBody:
      type: object
      properties:
        log_entry_date_time:
          type: string
          format: date-time
        courthouse:
          $ref: '#/components/schemas/Courthouse'
        courtroom:
          $ref: '#/components/schemas/Courtroom'
        case_numbers:
          type: array
          items:
            $ref: '#/components/schemas/CaseNumber'
          minItems: 1
        text:
          type: string
          maxLength: 256
      required:
        - log_entry_date_time
        - courthouse
        - courtroom
        - case_numbers
        - text

    CourtLog:
      type: object
      properties:
        courthouse:
          $ref: '#/components/schemas/Courthouse'
        caseNumber:
          type: string
        timestamp:
          type: string
          format: date-time
        eventText:
          type: string
      required:
        - courthouse
        - caseNumber
        - timestamp
        - eventText
    CourtLogs:
      type: array
      items:
        $ref: '#/components/schemas/CourtLog'


    DartsEvent:
      type: object
      properties:
        message_id:
          type: string
        type:
          type: string
        sub_type:
          type: string
        event_id:
          type: string
        courthouse:
          $ref: '#/components/schemas/Courthouse'
        courtroom:
          $ref: '#/components/schemas/Courtroom'
        case_numbers:
          type: array
          items:
            $ref: '#/components/schemas/CaseNumber'
        event_text:
          type: string
        date_time:
          type: string
          format: date-time
        retention_policy:
          type: object
          properties:
            case_retention_fixed_policy:
              type: string
            case_total_sentence:
              type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time

    EventsResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    ###################################################################################################################
    # PRIMITIVES
    ###################################################################################################################

    CaseNumber:
      type: string
      maxLength: 25

    Courthouse:
      type: string
      maxLength: 50

    Courtroom:
      type: string
      maxLength: 25

    GetCourtLogsErrorCode:
      type: string
      enum:
        - "GET_COURTLOG_101"
        - "GET_COURTLOG_102"
      x-enum-varnames: [COURTLOG_COURT_HOUSE_NOT_FOUND]

    PostCourtLogsErrorCode:
      type: string
      enum:
        - "ADD_COURTLOG_101"
        - "ADD_COURTLOG_102"
        - "ADD_COURTLOG_103"
      x-enum-varnames: [COURTLOG_COURT_HOUSE_NOT_FOUND, COURTLOG_DOCUMENT_CANT_BE_PARSED]

    EventErrorCode:
      type: string
      enum:
          - "100"
          - "101"
      x-enum-varnames: [ EVENT_DATA_NOT_FOUND, EVENT_HANDLER_NOT_FOUND_IN_DB]

    EventTitleErrors:
        type: string
        enum:
          - "Data on the event could not be reconciled with Darts records"
          - "No event handler found in database"
        x-enum-varnames: [ EVENT_DATA_NOT_FOUND, EVENT_HANDLER_NOT_FOUND_IN_DB]

