openapi: 3.0.1

info:

  version: 0.0.1
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/


paths:
  /events:
    post:
      tags:
        - Event
      summary: An Endpoint which allows users to request and submit events.
      description: |-
        Event data received from XHIBIT and CPP through a custom web service to add context to the audio recordings it stores.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DartsEvent'
            examples:
              example1:
                summary: Case called on
                value:
                  messageId: '18422'
                  type: '10100'
                  subType: '10100'
                  eventId: '001'
                  courthouse: SNARESBROOK
                  courtroom: '1'
                  caseNumbers:
                    - A20230049
                  dateTime: '2023-06-14T08:37:30.945Z'
              example2:
                summary: Freetext
                value:
                  messageId: '18422'
                  type: '21300'
                  subType: '21300'
                  eventId: '002'
                  courthouse: SNARESBROOK
                  courtroom: '1'
                  caseNumbers:
                    - T20190441
                  eventText: 'test'
                  dateTime: '2023-06-14T08:37:30.945Z'
              example3:
                summary: Life Imprisonment
                value:
                  messageId: '18422'
                  type: '40750'
                  subType: '11504'
                  eventId: '003'
                  courthouse: SNARESBROOK
                  courtroom: '1'
                  caseNumbers:
                    - T20190441
                  eventText: '[Defendant: DEFENDANT ONE]'
                  dateTime: '2023-06-14T08:37:30.945Z'
                  RetentionPolicy:
                    CaseRetentionFixedPolicy: 4
                    CaseTotalSentence: 26Y0M0D

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddDocumentResponse'

        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

  /courtlogs:
    post:
      tags:
        - Event
      summary: An Endpoint which allows users to create a court log event.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourtLogsPostRequestBody'
            examples:
              example1:
                summary: Request with single case
                value:
                  log_entry_date_time: '2023-05-23T09:15:25Z'
                  courthouse: CARDIFF
                  courtroom: '1'
                  case_numbers:
                    - CASE1001
                  text: 'System : Start Recording : Record: Case Code:0008, New Case'
              example2:
                summary: Request with multiple cases
                value:
                  log_entry_date_time: '2023-05-23T09:15:25Z'
                  courthouse: CARDIFF
                  courtroom: '1'
                  case_numbers:
                    - CASE1001
                    - CASE1002
                  text: 'System : Start Recording : Record: Case Code:0008, New Case'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourtLogsPostResponseBody'
              example:
                log_entry_date_time: '2023-05-23T09:15:25Z'
                courthouse: CARDIFF
                case_number: CASE1001

components:
  schemas:

    ###################################################################################################################
    # TOP-LEVEL MODELS
    ###################################################################################################################

    AddDocumentResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    CourtLogsPostRequestBody:
      type: object
      properties:
        log_entry_date_time:
          type: string
          format: date-time
        courthouse:
          $ref: '#/components/schemas/Courthouse'
        courtroom:
          $ref: '#/components/schemas/Courtroom'
        case_numbers:
          type: array
          items:
            $ref: '#/components/schemas/CaseNumber'
          minItems: 1
        text:
          type: string
          maxLength: 250
      required:
        - log_entry_date_time
        - courthouse
        - courtroom
        - case_numbers
        - text

    CourtLogsPostResponseBody:
      type: object
      properties:
        log_entry_date_time:
          type: string
          format: date-time
        courthouse:
          $ref: '#/components/schemas/Courthouse'
        case_number:
          $ref: '#/components/schemas/CaseNumber'
      required:
        - log_entry_date_time
        - courthouse
        - case_number

    DartsEvent:
      type: object
      properties:
        message_id:
          type: string
        type:
          type: string
        sub_type:
          type: string
        event_id:
          type: string
        courthouse:
          $ref: '#/components/schemas/Courthouse'
        courtroom:
          $ref: '#/components/schemas/Courtroom'
        case_numbers:
          type: array
          items:
            $ref: '#/components/schemas/CaseNumber'
        event_text:
          type: string
        date_time:
          type: string
          format: date-time
        retention_policy:
          type: object
          properties:
            case_retention_fixed_policy:
              type: string
            case_total_sentence:
              type: string

    ###################################################################################################################
    # PRIMITIVES
    ###################################################################################################################

    CaseNumber:
      type: string
      maxLength: 25

    Courthouse:
      type: string
      maxLength: 50

    Courtroom:
      type: string
      maxLength: 25
