openapi: 3.0.1

info:

  version: ${version}
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/


paths:
  /hearings/{hearing_id}:
    get:
      tags:
        - Hearings
      summary: Allows the retrieval of a hearing by ID.
      operationId: getHearing
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          description: "Internal hea_id of the hearing."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_hearing_response'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/HearingAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
  /hearings/{hearing_id}/annotations:
    get:
      tags:
        - Hearings
      summary: Allows the retrieval of annotations for a hearing.
      operationId: getHearingAnnotations
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          description: "Internal hea_id of the hearing."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/annotation'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/HearingAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
  /hearings/{hearing_id}/events:
    get:
      tags:
        - Hearings
      summary: Allows the retrieval of events for a given hearing_id
      operationId: getEvents
      description: |-
        Retrieves all events for a given hearing_id.
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          description: "hearing_id is the internal hea_id of the hearing."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events_response'
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
  /hearings/{hearing_id}/transcripts:
    get:
      tags:
        - Hearings
      summary: Allows the retrieval of transcripts for a given hearing_id
      description: |-
        Retrieves all transcripts for a hearing_id.
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          description: "hearing_id is the internal hea_id of the case."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'cases.yaml#/components/schemas/transcripts'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/HearingsAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "CASE_104"
                title: "The requested hearing cannot be found"
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
  /admin/hearings/search:
    post:
      tags:
        - Hearings
      summary: |-
        Search for hearings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HearingsSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HearingsSearchResponse'
        '400':
          description: Bad Request Error
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
  /admin/hearings/{id}:
    get:
      tags:
        - Hearings
      summary: |-
        Return details of a hearing
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HearingsResponse'
        '400':
          description: Bad Request Error
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
  /admin/hearings/{id}/audios:
    get:
      tags:
        - Hearings
      summary: |-
        Returns the audios associated with a specific hearing via the "hearing_media_ae" table, including current audios only but all channels.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HearingsAudiosResponse'
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "CASE_104"
                title: "The requested hearing cannot be found"
                status: 404

components:
  schemas:
    get_hearing_response:
      type: object
      properties:
        hearing_id:
          type: integer
          example: 1
        courthouse_id:
          type: integer
          example: 1001
        courthouse:
          type: string
          example: SWANSEA
        courtroom:
          type: string
          example: 1
        hearing_date:
          type: string
          format: date
          example: 2023-06-23
        case_id:
          type: integer
          example: 1
        case_number:
          type: string
          example: CASE1001
        judges:
          type: array
          items:
            $ref: '#/components/schemas/judge'
        transcription_count:
          type: integer
          example: 1
        case_reporting_restrictions:
          $ref: './common.yaml#/components/schemas/reporting_restrictions'

    judge:
      type: string
      example: Mr Judge

    events_response:
      type: array
      default: [ ]
      items:
        $ref: '#/components/schemas/event_response'
    event_response:
      type: object
      properties:
        id:
          type: integer
          example: 1
        timestamp:
          type: string
          format: date-time
          example: 2023-07-31T14:32:24.620Z
        name:
          type: string
          example: Case called on
        text:
          type: string
          example: Record:New Case
        is_data_anonymised:
          type: boolean
          example: false

    HearingsSearchRequest:
      type: object
      properties:
        courthouse_ids:
          type: array
          items:
            type: integer
        case_number:
          type: string
          example: C123
        courtroom_name:
          type: string
          example: some_courthouse
          maxLength: 64
        hearing_start_at:
          type: string
          format: date
          example: '2023-07-31'
        hearing_end_at:
          type: string
          format: date
          example: '2023-07-31'
    HearingsAudiosResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          start_at:
            type: string
            format: date-time
            example: 2023-07-31T14:32:24.620Z
          end_at:
            type: string
            format: date-time
            example: 2023-07-31T14:32:24.620Z
          filename:
            type: string
            example: "audio.mp3"
          channel:
            type: integer
            example: 1
          total_channels:
            type: integer
            example: 4
    HearingsResponse:
      type: object
      properties:
        id:
          type: integer
        hearing_date:
          type: string
          format: date
          example: '2023-07-31'
        scheduled_start_time:
          type: string
          format: time
          example: '10:00:00'
        hearing_is_actual:
          type: boolean
          example: true
        case:
          type: object
          properties:
            id:
              type: integer
              description: 'The case id'
            case_number:
              type: string
              description: 'The case number'
            courthouse:
              type: object
              properties:
                id:
                  type: integer
                  description: 'The court house id'
                display_name:
                  type: string
                  description: 'The court house display name'
            defendants:
              type: array
              items:
                type: string
                example: Joe Bloggs
            prosecutors:
              type: array
              items:
                type: string
                example: Joe Bloggs
            defenders:
              type: array
              items:
                type: string
                example: Joe Bloggs
            judges:
              type: array
              items:
                type: string
                example: Joe Bloggs
        courtroom:
          type: object
          properties:
            id:
              type: integer
              description: 'The court house id'
            name:
              type: string
              description: 'The court house display name'
        judges:
          type: array
          items:
            type: string
            example: Joe Bloggs
        created_at:
          type: string
          format: date-time
          example: '2023-07-31T14:32:24.620Z'
        created_by:
          type: integer
          example: 0
        last_modified_at:
          type: string
          format: date-time
          example: '2023-07-31T14:32:24.620Z'
        last_modified_by:
          type: integer
          example: 0
    HearingsSearchResponse:
      type: object
      properties:
        id:
          type: integer
        hearing_date:
          type: string
          format: date
          example: '2023-07-31'
        case:
          type: object
          description: 'The case related details'
          properties:
            id:
              type: integer
              description: 'The case id'
            case_number:
              type: string
              description: 'The case number'
        courthouse:
          type: object
          description: 'The courthouse related details'
          properties:
            id:
              type: integer
              description: 'The court house id'
            display_name:
              type: string
              description: 'The court house display name'
        courtroom:
          type: object
          description: 'The courtroom related details'
          properties:
            id:
              type: integer
              description: 'The court room id'
            name:
              type: string
              description: 'The court room display name'
    HearingAuthorisation403ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_100"
      x-enum-varnames: [ USER_NOT_AUTHORISED_FOR_COURTHOUSE ]
    transcripts:
      type: array
      items:
        $ref: '#/components/schemas/transcript'
    transcript:
      type: object
      properties:
        transcription_id:
          type: integer
          example: 1
        hearing_id:
          type: integer
          example: 2
        hearing_date:
          type: string
          format: date
          example: 2022-05-20
        type:
          type: string
          example: "Sentencing remarks"
        requested_on:
          type: string
          format: date-time
          example: 2023-06-20T10:00:00Z
        requested_by_name:
          type: string
          example: "Joe Bloggs"
        status:
          type: string
          example: "Available"
    annotation:
      type: object
      properties:
        annotation_id:
          type: integer
          example: 1
        hearing_id:
          type: integer
          example: 2
        hearing_date:
          type: string
          format: date
          example: 2022-05-20
        annotation_ts:
          type: string
          format: date-time
          example: 2023-06-20T10:00:00Z
        annotation_text:
          type: string
          example: "A summary notes of this annotation..."
        annotation_documents:
          type: array
          items:
            $ref: '#/components/schemas/annotation_document'
    annotation_document:
      type: object
      properties:
        annotation_document_id:
          type: integer
          example: 1
        file_name:
          type: string
          example: "Annotation.doc"
        file_type:
          type: string
          example: "DOC"
        uploaded_by:
          type: string
          example: "Mr User McUserFace"
        uploaded_ts:
          type: string
          format: date-time
          example: 2023-06-20T10:00:00Z
    HearingsAuthorisation403ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_100"
      x-enum-varnames: [ USER_NOT_AUTHORISED_FOR_COURTHOUSE ]

    HearingsErrorCode:
      type: string
      enum:
        - "HEARING_100"
        - "HEARING_101"
        - "HEARING_102"
        - "HEARING_103"
        - "HEARING_104"
      x-enum-varnames: [ HEARING_NOT_FOUND, TOO_MANY_RESULTS, HEARING_NOT_ACTUAL, CRITERIA_TOO_BROAD, INVALID_REQUEST ]

    HearingsTitleErrors:
      type: string
      enum:
        - "The requested hearing cannot be found"
        - "Too many results have been returned. Please change search criteria."
        - "The requested hearing is not an actual hearing."
        - "The search criteria is too broad. Please refine your search."
        - "The request is invalid. Please check the request and try again."
      x-enum-varnames: [ HEARING_NOT_FOUND, TOO_MANY_RESULTS, HEARING_NOT_ACTUAL, CRITERIA_TOO_BROAD, INVALID_REQUEST ]