openapi: 3.0.1

info:

  version: ${version}
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/


paths:
  /retentions:
    get:
      tags:
        - Retention
      summary: Get retention history
      parameters:
        - in: query
          name: case_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetCaseRetentionsResponse'
        '404':
          description: Not Found
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

    post:
      tags:
        - Retention
      summary: allow case retention changes to be applied.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRetentionRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostRetentionResponse'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/NoPermissionReduceRetentionError'
              example:
                type: "RETENTION_100"
                title: "User does not have permission to reduce the retention period."
                status: 403
        '422':
          description: Unprocessable Content
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      latest_automated_retention_date:
                        type: string
                        format: date
              example:
                type: "RETENTION_101"
                title: "The retention date being applied is too early."
                status: 422
                detail: caseId '26029' must have a retention date after the last completed automated retention date '2026-02-07'.
                latest_automated_retention_date: 2026-02-07
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
components:
  schemas:
    GetCaseRetentionsResponse:
      type: object
      properties:
        retention_last_changed_date:
          type: string
          format: date-time
        retention_date:
          type: string
          format: date
        amended_by:
          type: string
        retention_policy_applied:
          type: string
        status:
          type: string
        comments:
          type: string

    PostRetentionRequest:
      type: object
      required:
        - case_id
        - comments
      properties:
        case_id:
          type: integer
          example: 12345
        retention_date:
          type: string
          format: date
          example: 2022-05-20
          description: Conditional Mandatory. If is_permanent_retention is false, then this must be provided. Date must not be less that the current retention period of the last automated sentencing type.
        is_permanent_retention:
          type: boolean
        validate_only:
          type: boolean
          default: false
          description: Optional - If set to true, will not apply retention to database, but still do all the validation on the date provided.
        comments:
          type: string

    PostRetentionResponse:
      type: object
      properties:
        retention_date:
          type: string
          format: date

    NoPermissionReduceRetentionError:
      type: string
      enum:
        - "RETENTION_100"
      x-enum-varnames: [ NO_PERMISSION_REDUCE_RETENTION_ERROR ]
