openapi: 3.0.1

info:

  version: ${version}
  title: Modernised DARTS
  description: |-
    Modernised DARTS (Digital Audio Recording and Transcription Service).

servers:
  - url: http://localhost:4550/


paths:
  /retentions:
    get:
      tags:
        - Retention
      summary: Get retention history
      parameters:
        - in: query
          name: case_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetCaseRetentionsResponse'
        '404':
          description: Not Found
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'

    post:
      tags:
        - Retention
      summary: allow case retention changes to be applied.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post_retention_request'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/no_permission_reduce_retention_error'
              example:
                type: "RETENTION_100"
                title: "User does not have permission to reduce the retention period."
                status: 403
        '422':
          description: Unprocessable Content
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/retention_date_invalid_error'
              example:
                type: "RETENTION_101"
                title: "Retention date not valid."
                status: 422
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
components:
  schemas:
    GetCaseRetentionsResponse:
      type: object
      properties:
        retention_last_changed_date:
          type: string
          format: date-time
        retention_date:
          type: string
          format: date
        amended_by:
          type: string
        retention_policy_applied:
          type: string
        status:
          type: string
        comments:
          type: string

    post_retention_request:
      type: object
      required:
        - case_id
        - comments
      properties:
        case_id:
          type: integer
          example: 12345
        retention_date:
          type: string
          format: date
          example: 2022-05-20
          description: Conditional Mandatory. If is_permanent_retention is false, then this must be provided. Date must not be less that the current retention period of the last automated sentencing type.
        is_permanent_retention:
          type: boolean
        comments:
          type: string

    no_permission_reduce_retention_error:
      type: string
      enum:
        - "RETENTION_100"
      x-enum-varnames: [ NO_PERMISSION_REDUCE_RETENTION_ERROR ]

    retention_date_invalid_error:
      type: string
      enum:
        - "RETENTION_101"
      x-enum-varnames: [ RETENTION_DATE_INVALID_ERROR ]
