openapi: 3.0.1

info:
  title: 'Modernised DARTS'
  description: 'Modernised DARTS (Digital Audio Recording and Transcription Service).'
  version: '${version}'


########################################################################################################################
# PATH DEFINITIONS
########################################################################################################################

paths:
  /admin/automated-tasks:
    get:
      tags:
        - Tasks
      operationId: getAutomatedTasks
      responses:
        '200':
          $ref: '#/components/responses/AutomatedTasksResponse'

  /admin/automated-tasks/{task_id}:
    get:
      tags:
        - Tasks
      operationId: getAutomatedTaskById
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          $ref: '#/components/responses/AutomatedTaskResponse'
        '404':
          $ref: '#/components/responses/AutomatedTaskNotFound'
    patch:
      tags:
        - Tasks
      operationId: patchAutomatedTask
      parameters:
        - $ref: '#/components/parameters/TaskId'
      requestBody:
        $ref: '#/components/requestBodies/AutomatedTaskPatchRequest'
      responses:
        '200':
          $ref: '#/components/responses/AutomatedTaskResponse'
        '404':
          $ref: '#/components/responses/AutomatedTaskNotFound'


  /admin/automated-tasks/{task_id}/run:
    post:
      tags:
        - Tasks
      operationId: runAutomatedTask
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '202':
          description: ACCEPTED
        '404':
          $ref: '#/components/responses/AutomatedTaskNotFound'
        '409':
          $ref: '#/components/responses/AutomatedTaskAlreadyRunning'

########################################################################################################################
# COMPONENT DEFINITIONS
########################################################################################################################

components:

  requestBodies:
    AutomatedTaskPatchRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AutomatedTaskPatch'
  responses:
    AutomatedTasksResponse:
      description: 'Success'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AutomatedTaskSummary'
    AutomatedTaskResponse:
      description: 'Success'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DetailedAutomatedTask'
    AutomatedTaskNotFound:
      description: Automated task not found
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            type: "AUTOMATED_TASK_100"
            title: "Automated task not found"
            status: 404
    AutomatedTaskAlreadyRunning:
      description: Automated task already running
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            type: "AUTOMATED_TASK_101"
            title: "Automated task is already running"
            status: 409

  schemas:
    AutomatedTaskPatch:
      type: object
      properties:
        is_active:
          $ref: '#/components/schemas/IsActive'
        batch_size:
          type: integer

        rpo_csv_start_hour:
          type: integer
        rpo_csv_end_hour:
          type: integer
        arm_replay_start_ts:
          type: string
          format: date-time
        arm_replay_end_ts:
          type: string
          format: date-time


    AutomatedTaskSummary:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/AutomatedTaskId'
        name:
          $ref: '#/components/schemas/AutomatedTaskName'
        description:
          $ref: '#/components/schemas/AutomatedTaskDescription'
        cron_expression:
          $ref: '#/components/schemas/CronExpression'
        is_active:
          $ref: '#/components/schemas/IsActive'
    DetailedAutomatedTask:
      type: object
      properties:
        is_cron_editable:
          $ref: '#/components/schemas/IsCronEditable'
        batch_size:
          $ref: '#/components/schemas/BatchSize'
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        created_by:
          $ref: '#/components/schemas/CreatedBy'
        last_modified_at:
          $ref: '#/components/schemas/LastModifiedAt'
        last_modified_by:
          $ref: '#/components/schemas/LastModifiedBy'
      allOf:
        - $ref: '#/components/schemas/AutomatedTaskSummary'

    AutomatedTaskId:
      type: integer
    AutomatedTaskName:
      type: string
      minLength: 1
      maxLength: 256
    AutomatedTaskDescription:
      type: string
      minLength: 1
      maxLength: 256
    CronExpression:
      type: string
      minLength: 1
      maxLength: 256
    IsActive:
      type: boolean
    BatchSize:
      type: integer
    IsCronEditable:
      type: boolean
    CreatedAt:
      type: string
      format: date-time
    CreatedBy:
      type: integer
    LastModifiedAt:
      type: string
      format: date-time
    LastModifiedBy:
      type: integer

    AutomatedTaskErrorCode:
      type: string
      enum:
        - "AUTOMATED_TASK_100"
        - "AUTOMATED_TASK_101"
        - "AUTOMATED_TASK_102"
        - "AUTOMATED_TASK_103"
      x-enum-varnames: [ AUTOMATED_TASK_NOT_FOUND, AUTOMATED_TASK_ALREADY_RUNNING, AUTOMATED_TASK_NOT_CONFIGURED, INCORRECT_AUTOMATED_TASK_TYPE ]

    AutomatedTaskTitleErrors:
      type: string
      enum:
        - "The provided task_id does not exist"
        - "The automated task is already running"
        - "The automated task has not been initialized correctly on application start up and can not be run manually."
        - "The automated task type is incorrect"
      x-enum-varnames: [ AUTOMATED_TASK_NOT_FOUND, AUTOMATED_TASK_ALREADY_RUNNING, AUTOMATED_TASK_NOT_CONFIGURED, INCORRECT_AUTOMATED_TASK_TYPE ]
  parameters:
    TaskId:
      in: path
      name: task_id
      required: true
      schema:
        type: integer