openapi: 3.0.1

servers:
  - url: http://localhost:4550/

info:
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
  version: ${version}
  title: Modernised DARTS

paths:
  /transcriptions:
    post:
      tags:
        - Transcription
      summary: Requesters can request transcription
      operationId: requestTranscription
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestTranscriptionResponse'
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/RequestTranscription400ErrorCode'
        '401':
          description: Unauthorised Error
        '404':
          description: Not Found Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranscriptionRequestDetails'
  /transcriptions/{transcription_id}:
    patch:
      tags:
        - Transcription
      summary: Workflow actors can add a comment against the transcription status
      operationId: updateTranscription
      parameters:
        - in: path
          name: transcription_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTranscriptionResponse'
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/UpdateTranscription400ErrorCode'
              example:
                type: "TRANSCRIPTION_103"
                title: "The workflow comment is required for this transcription update"
                status: 400
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/TranscriptionAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/UpdateTranscription404ErrorCode'
              example:
                type: "TRANSCRIPTION_101"
                title: "The requested transcription cannot be found"
                status: 404
        '409':
          description: Transcription Workflow Action Not Permitted
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/UpdateTranscription409ErrorCode'
              example:
                type: "TRANSCRIPTION_105"
                title: "Transcription workflow action is not permitted"
                status: 409
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTranscription'

  /transcriptions/types:
    get:
      tags:
        - Transcription
      summary: Gets a list of the transcription types
      operationId: getTranscriptionTypes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranscriptionTypesResponse'
        '401':
          description: Unauthorised Error


  /transcripts/hearings/{hearing_id}:
    get:
      tags:
        - Transcription
      summary: Allows the retrieval of transcripts for a given hearing_id
      description: |-
        Retrieves all transcripts for a hearing_id.
      parameters:
        - in: path
          name: hearing_id
          schema:
            type: integer
          description: "hearing_id is the internal hea_id of the case."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transcripts'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/HearingsAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "CASE_104"
                title: "The requested case cannot be found"
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
  /transcripts/case/{case_id}:
    get:
      tags:
        - Transcription
      summary: Allows the retrieval of transcripts for a given case_id
      description: |-
        Retrieves all transcripts for a case_id.
      parameters:
        - in: path
          name: case_id
          schema:
            type: integer
          description: "case_id is the internal cas_id of the case."
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transcripts'
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/CasesAuthorisation403ErrorCode'
              example:
                type: "AUTHORISATION_100"
                title: "User is not authorised for the associated courthouse"
                status: 403
        '404':
          description: Not Found Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                type: "CASE_104"
                title: "The requested case cannot be found"
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'


components:
  schemas:
    TranscriptionRequestDetails:
      type: object
      required:
        - urgency_id
        - transcription_type_id
      properties:
        hearing_id:
          type: integer
          example: 1234
        case_id:
          type: integer
          example: 4567
        urgency_id:
          type: integer
          example: 2
        transcription_type_id:
          type: integer
          example: 3
        comment:
          type: string
          example: 'Please expedite my transcription request'
        start_date_time:
          type: string
          format: date-time
          example: '2023-07-31T14:32:24.000Z'
        end_date_time:
          type: string
          format: date-time
          example: '2023-07-31T14:32:24.000Z'
    RequestTranscription400ErrorCode:
      type: string
      enum:
        - "TRANSCRIPTION_100"
        - "TRANSCRIPTION_104"
        - "TRANSCRIPTION_106"
      x-enum-varnames: [ FAILED_TO_VALIDATE_TRANSCRIPTION_REQUEST, BAD_REQUEST_TRANSCRIPTION_TYPE, BAD_REQUEST_TRANSCRIPTION_URGENCY ]
    UpdateTranscription:
      type: object
      required:
        - transcription_status_id
      properties:
        transcription_status_id:
          type: integer
          example: 3
        workflow_comment:
          type: string
    RequestTranscriptionResponse:
      type: object
      required:
        - transcription_id
      properties:
        transcription_id:
          type: integer
    UpdateTranscriptionResponse:
      type: object
      required:
        - transcription_workflow_id
      properties:
        transcription_workflow_id:
          type: integer
    UpdateTranscription404ErrorCode:
      type: string
      enum:
        - "TRANSCRIPTION_101"
      x-enum-varnames: [ TRANSCRIPTION_NOT_FOUND ]
    UpdateTranscription400ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_105"
        - "TRANSCRIPTION_102"
        - "TRANSCRIPTION_103"
        - "TRANSCRIPTION_104"
      x-enum-varnames: [ BAD_REQUEST_TRANSCRIPTION_ID, BAD_REQUEST_TRANSCRIPTION_STATUS, BAD_REQUEST_WORKFLOW_COMMENT, BAD_REQUEST_TRANSCRIPTION_TYPE ]
    TranscriptionAuthorisation403ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_100"
      x-enum-varnames: [ USER_NOT_AUTHORISED_FOR_COURTHOUSE ]
    UpdateTranscription409ErrorCode:
      type: string
      enum:
        - "TRANSCRIPTION_105"
      x-enum-varnames: [ TRANSCRIPTION_WORKFLOW_ACTION_INVALID ]
    transcripts:
      type: array
      items:
        $ref: '#/components/schemas/transcript'
    transcript:
      type: object
      properties:
        tra_id:
          type: integer
          example: 1
        hea_id:
          type: integer
          example: 2
        hearing_date:
          type: string
          format: date
          example: 2022-05-20
        type:
          type: string
          example: "Sentencing remarks"
        requested_on:
          type: string
          format: date
          example: 2022-05-22
        requested_by_name:
          type: string
          example: "Joe Bloggs"
        status:
          type: string
          example: "Available"
    CasesAuthorisation403ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_100"
      x-enum-varnames: [ USER_NOT_AUTHORISED_FOR_COURTHOUSE ]
    HearingsAuthorisation403ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_100"
      x-enum-varnames: [ USER_NOT_AUTHORISED_FOR_COURTHOUSE ]

    TranscriptionTypesResponse:
      type: array
      items:
        $ref: '#/components/schemas/TranscriptionTypeResponse'
    TranscriptionTypeResponse:
      type: object
      properties:
        trt_id:
          type: integer
          example: 1
        description:
          type: string
          example: Sentencing remarks

