openapi: 3.0.1

info:
  title: 'Modernised DARTS'
  description: 'Modernised DARTS (Digital Audio Recording and Transcription Service).'
  version: '${version}'


########################################################################################################################
# PATH DEFINITIONS
########################################################################################################################

paths:
  /admin/users:
    get:
      tags:
        - User
      operationId: getUsers
      parameters:
        - in: query
          name: courthouse_id
          required: false
          schema:
            $ref: "#/components/schemas/CourthouseId"
        - in: header
          name: Email-Address
          required: false
          schema:
            $ref: '#/components/schemas/UserEmailAddress'
      responses:
        '200':
          $ref: '#/components/responses/UserArraySuccessResponseWithIdAndTimestamps'

    post:
      summary: Create new user
      tags:
        - User
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserRequest'
      responses:
        '201':
          $ref: '#/components/responses/UserSuccessResponseWithId'
        '400':
          $ref: '#/components/responses/BadUserRequest'
  /admin/users/{user_id}:
    get:
      tags:
        - User
      operationId: getUsersById
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          $ref: '#/components/responses/UserSuccessResponseWithIdAndTimestamps'
        '404':
          $ref: '#/components/responses/UserNotFound'

    patch:
      summary: Modify user by id
      tags:
        - User
      operationId: modifyUser
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        $ref: '#/components/requestBodies/UserPatchRequest'
      responses:
        '200':
          $ref: '#/components/responses/UserSuccessResponseWithIdAndTimestamps'
        '400':
          $ref: '#/components/responses/BadUserPatchRequest'
        '404':
          $ref: '#/components/responses/UserNotFound'

  /admin/users/search:
    post:
      summary: Get users by search criteria
      tags:
        - User
      operationId: search
      requestBody:
        $ref: '#/components/requestBodies/UserSearchRequest'
      responses:
        '200':
          $ref: '#/components/responses/UserArraySuccessResponseWithIdAndTimestamps'
        '400':
          description: Bad Request Error
          content:
            application/json+problem:
              schema:
                $ref: './problem.yaml'
              example:
                violations:
                  - field: emailAddress
                    message: size must be between 1 and 256
                type: https://zalando.github.io/problem/constraint-violation
                status: 400
                title: Constraint Violation
        '401':
          description: Unauthorised Error
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/UserAuthorisation403_107ErrorCode'
              example:
                type: AUTHORISATION_107
                title: Failed to check authorisation
                status: 403

  /admin/security-groups:
    get:
      summary: Get security groups
      parameters:
        - in: query
          name: role_ids
          description: Filter by list of role ids
          style: form
          explode: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/RoleId'
        - in: query
          name: courthouse_id
          description: Filter by Courthouse Id
          schema:
            $ref: '#/components/schemas/CourthouseId'
      tags:
        - SecurityGroup
      responses:
        '200':
          $ref: '#/components/responses/SecurityGroupArraySuccessResponse'
    post:
      summary: Create security group (transcriber groups only)
      tags:
        - SecurityGroup
      requestBody:
        $ref: '#/components/requestBodies/SecurityGroupsRequest'
      responses:
        '201':
          $ref: '#/components/responses/SecurityGroupSuccessResponse'
        '400':
          $ref: '#/components/responses/SecurityGroupBadRequest'

  /admin/security-roles:
    get:
      summary: Get roles
      tags:
        - SecurityRole
      responses:
        '200':
          $ref: '#/components/responses/RoleArraySuccessResponse'
        '403':
          description: Forbidden Error
          content:
            application/json+problem:
              schema:
                allOf:
                  - $ref: './problem.yaml'
                  - type: object
                    required:
                      - type
                    properties:
                      type:
                        $ref: '#/components/schemas/UserAuthorisation403_109ErrorCode'
              example:
                type: AUTHORISATION_109
                title: User is not authorised for this endpoint
                status: 403

########################################################################################################################
# COMPONENT DEFINITIONS
########################################################################################################################

components:
  requestBodies:
    UserRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    UserPatchRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserPatch'
    UserSearchRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserSearch'
    SecurityGroupsRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SecurityGroup'

  responses:
    UserSuccessResponseWithId:
      description: 'Success'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserWithId'
    UserSuccessResponseWithIdAndTimestamps:
      description: 'Success'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserWithIdAndTimestamps'
    UserArraySuccessResponseWithIdAndTimestamps:
      description: 'Success'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserWithIdAndTimestamps'
    SecurityGroupArraySuccessResponse:
      description: 'Success'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SecurityGroupWithIdAndRole'
    RoleArraySuccessResponse:
      description: 'Success'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Role'

    UserTransferSuccess:
      description: 'Success'
    SecurityGroupSuccessResponse:
      description: 'Success'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SecurityGroupWithIdAndRole'

    BadUserRequest:
      description: Bad Request
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            violations:
              - field: "emailAddress"
                message: "must not be null"
              - field: "state"
                message: "must not be null"
              - field: "fullName"
                message: "must not be null"
            type: "https://zalando.github.io/problem/constraint-violation"
            title: "Constraint Violation"
            status: 400
    BadUserPatchRequest:
      description: Bad Request
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            violations:
              - field: "fullName"
                message: "size must be between 1 and 256"
            type: "https://zalando.github.io/problem/constraint-violation"
            title: "Constraint Violation"
            status: 400
    UserNotFound:
      description: User not found
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            type: "USER_100"
            title: "User not found"
            status: 404
    SecurityGroupBadRequest:
      description: Bad Request
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            violations:
              - field: "name"
                message: "must not be null"
              - field: "display_name"
                message: "must not be null"
            type: "https://zalando.github.io/problem/constraint-violation"
            title: "Constraint Violation"
            status: 400

  parameters:
    UserId:
      in: path
      name: user_id
      required: true
      schema:
        type: integer

  schemas:
    UserId:
      type: integer
    UserName:
      minLength: 1
      maxLength: 256
      type: string
    UserEmailAddress:
      minLength: 1
      maxLength: 256
      type: string
    UserDescription:
      minLength: 0
      maxLength: 256
      type: string
    UserActive:
      type: boolean

    SecurityGroupId:
      type: integer
    SecurityGroupName:
      type: string
      minLength: 1
      maxLength: 256
    SecurityGroupDescription:
      type: string
      minLength: 1
      maxLength: 256
    SecurityGroupDisplayName:
      type: string
      minLength: 1
      maxLength: 256
    SecurityGroupGlobalAccess:
      type: boolean
    SecurityGroupDisplayState:
      type: boolean

    RoleId:
      type: integer
    RoleDisplayName:
      type: string
      minLength: 1
      maxLength: 256
    RoleDisplayState:
      type: boolean
    CourthouseId:
      type: integer

    User:
      type: object
      properties:
        full_name:
          $ref: '#/components/schemas/UserName'
        email_address:
          $ref: '#/components/schemas/UserEmailAddress'
        description:
          $ref: '#/components/schemas/UserDescription'
        active:
          $ref: '#/components/schemas/UserActive'
        security_group_ids:
          type: array
          items:
            $ref: '#/components/schemas/SecurityGroupId'
      required:
        - full_name
        - email_address
        - state
    UserPatch:
      type: object
      properties:
        full_name:
          $ref: '#/components/schemas/UserName'
        email_address:
          $ref: '#/components/schemas/UserEmailAddress'
        description:
          $ref: '#/components/schemas/UserDescription'
        active:
          $ref: '#/components/schemas/UserActive'
        security_group_ids:
          type: array
          items:
            $ref: '#/components/schemas/SecurityGroupId'
    UserSearch:
      type: object
      properties:
        full_name:
          $ref: '#/components/schemas/UserName'
        email_address:
          $ref: '#/components/schemas/UserEmailAddress'
        active:
          $ref: '#/components/schemas/UserActive'
    UserWithId:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UserId'
      allOf:
        - $ref: '#/components/schemas/User'
    UserWithIdAndTimestamps:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        last_login_at:
          type: string
          format: date-time
        last_modified_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
      allOf:
        - $ref: '#/components/schemas/User'
    UserAuthorisation403_107ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_107"
      x-enum-varnames: [ BAD_REQUEST_ANY_ID ]

    UserAuthorisation403_109ErrorCode:
      type: string
      enum:
        - "AUTHORISATION_109"
      x-enum-varnames: [ USER_NOT_AUTHORISED_FOR_ENDPOINT ]

    SecurityGroupWithIdAndRole:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/SecurityGroupId'
        security_role_id:
          $ref: '#/components/schemas/RoleId'
        global_access:
          $ref: '#/components/schemas/SecurityGroupGlobalAccess'
        display_state:
          $ref: '#/components/schemas/SecurityGroupDisplayState'
        courthouse_ids:
          type: array
          items:
            $ref: '#/components/schemas/CourthouseId'
      allOf:
        - $ref: '#/components/schemas/SecurityGroup'
    SecurityGroup:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/SecurityGroupName'
        display_name:
          $ref: '#/components/schemas/SecurityGroupDisplayName'
        description:
          $ref: '#/components/schemas/SecurityGroupDescription'
      required:
        - name
        - display_name

    UserManagementErrorCode:
      type: string
      enum:
        - "USER_MANAGEMENT_100"
        - "USER_MANAGEMENT_101"
        - "USER_NOT_TRANSCRIBER_110"
      x-enum-varnames: [ USER_NOT_FOUND, DUPLICATE_EMAIL, DUPLICATE_SECURITY_GROUP_NAME_NOT_PERMITTED ]

    UserManagementTitleErrors:
      type: string
      enum:
        - "The provided user does not exist"
        - "The provided email already exists"
        - "Duplicate security group names are not permitted"
      x-enum-varnames: [ USER_NOT_FOUND, DUPLICATE_EMAIL, DUPLICATE_SECURITY_GROUP_NAME_NOT_PERMITTED ]


    Role:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/RoleId'
        display_name:
          $ref: '#/components/schemas/RoleDisplayName'
        display_state:
          $ref: '#/components/schemas/RoleDisplayState'

        UserManagementsErrorCode:
            type: string
            enum:
              - "USER_100"
              - "USER_101"
              - "USER_110"
            x-enum-varnames: [ USER_NOT_FOUND, DUPLICATE_EMAIL, DUPLICATE_SECURITY_GROUP_NAME_NOT_PERMITTED]

        UserManagementsTitleErrors:
            type: string
            enum:
              - "The provided user does not exist"
              - "The provided email already exists"
              - "Duplicate security group names are not permitted"
            x-enum-varnames: [ USER_NOT_FOUND, DUPLICATE_EMAIL, DUPLICATE_SECURITY_GROUP_NAME_NOT_PERMITTED]
