openapi: 3.0.1

info:
  title: 'Modernised DARTS'
  description: 'Modernised DARTS (Digital Audio Recording and Transcription Service).'
  version: '${version}'


########################################################################################################################
# PATH DEFINITIONS
########################################################################################################################

paths:
  /users:
    get:
      tags:
        - User
      parameters:
        - in: query
          name: courthouse
          required: true
          schema:
            $ref: "#/components/schemas/CourthouseId"
      responses:
        '200':
          $ref: '#/components/responses/UserArraySuccessResponseWithIdAndLastLogin'
    post:
      summary: Create new user
      tags:
        - User
      requestBody:
        $ref: '#/components/requestBodies/UserRequest'
      responses:
        '201':
          $ref: '#/components/responses/UserSuccessResponseWithId'
        '400':
          $ref: '#/components/responses/BadUserRequest'
  /users/{id}:
    patch:
      summary: Modify user by id
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        $ref: '#/components/requestBodies/UserPatchRequest'
      responses:
        '200':
          $ref: '#/components/responses/UserSuccessResponseWithIdAndLastLogin'
        '400':
          $ref: '#/components/responses/BadUserPatchRequest'
        '404':
          $ref: '#/components/responses/UserNotFound'

  /users/search:
    post:
      summary: Get users by search criteria
      tags:
        - User
      requestBody:
        $ref: '#/components/requestBodies/UserSearchRequest'
      responses:
        '200':
          $ref: '#/components/responses/UserArraySuccessResponseWithIdAndLastLogin'

  /security-groups:
    get:
      summary: Get security groups
      parameters:
        - in: query
          name: courthouse
          schema:
            $ref: "#/components/schemas/CourthouseId"
      tags:
        - SecurityGroup
      responses:
        '200':
          $ref: '#/components/responses/SecurityGroupArraySuccessResponse'


########################################################################################################################
# COMPONENT DEFINITIONS
########################################################################################################################

components:
  requestBodies:
    UserRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    UserPatchRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserPatch'
    UserSearchRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserSearch'

  responses:
    UserSuccessResponseWithId:
      description: 'Success'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserWithId'
    UserSuccessResponseWithIdAndLastLogin:
      description: 'Success'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserWithIdAndLastLogin'
    UserArraySuccessResponseWithIdAndLastLogin:
      description: 'Success'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserWithIdAndLastLogin'
    SecurityGroupArraySuccessResponse:
      description: 'Success'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SecurityGroup'
    UserTransferSuccess:
      description: 'Success'

    BadUserRequest:
      description: Bad Request
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            violations:
              - field: "emailAddress"
                message: "must not be null"
              - field: "state"
                message: "must not be null"
              - field: "fullName"
                message: "must not be null"
            type: "https://zalando.github.io/problem/constraint-violation"
            title: "Constraint Violation"
            status: 400
    BadUserPatchRequest:
      description: Bad Request
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            violations:
              - field: "fullName"
                message: "size must be between 1 and 256"
            type: "https://zalando.github.io/problem/constraint-violation"
            title: "Constraint Violation"
            status: 400
    UserNotFound:
      description: User not found
      content:
        application/json+problem:
          schema:
            $ref: './problem.yaml'
          example:
            type: "USER_100"
            title: "User not found"
            status: 404

  parameters:
    UserId:
      in: path
      name: id
      required: true
      schema:
        type: integer
    CourthouseId:
      in: query
      name: courthouse
      required: true
      schema:
        $ref: "#/components/schemas/CourthouseId"

  schemas:
    UserId:
      type: integer
    UserName:
      minLength: 1
      maxLength: 256
      pattern: ^[^\s][a-zA-Z\s'-]+[^\s]$
      type: string
    UserEmailAddress:
      minLength: 1
      maxLength: 256
      type: string
    UserDescription:
      minLength: 1
      maxLength: 256
      type: string
    UserState:
      type: string
      enum:
        - ENABLED
        - DISABLED
      default: ENABLED

    SecurityGroupId:
      type: integer
    SecurityGroupName:
      type: string
    SecurityGroupDescription:
      type: string
    SecurityGroupDisplayName:
      type: string
    SecurityGroupRole:
      type: string

    CourthouseId:
      type: integer

    GenericSearchField:
      minLength: 3
      maxLength: 256
      type: string

    User:
      type: object
      properties:
        full_name:
          $ref: '#/components/schemas/UserName'
        email_address:
          $ref: '#/components/schemas/UserEmailAddress'
        description:
          $ref: '#/components/schemas/UserDescription'
        state:
          $ref: '#/components/schemas/UserState'
        security_groups:
          type: array
          items:
            $ref: '#/components/schemas/SecurityGroupId'
      required:
        - full_name
        - email_address
        - state
    UserPatch:
      type: object
      properties:
        full_name:
          $ref: '#/components/schemas/UserName'
        description:
          $ref: '#/components/schemas/UserDescription'
        state:
          $ref: '#/components/schemas/UserState'
        security_groups:
          type: array
          items:
            $ref: '#/components/schemas/SecurityGroupId'
    UserSearch:
      type: object
      properties:
        full_name:
          $ref: '#/components/schemas/GenericSearchField'
        email_address:
          $ref: '#/components/schemas/GenericSearchField'
    UserWithId:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UserId'
      allOf:
        - $ref: '#/components/schemas/User'
    UserWithIdAndLastLogin:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        last_login:
          type: string
          format: date-time
      allOf:
        - $ref: '#/components/schemas/User'

    SecurityGroup:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/SecurityGroupId'
        name:
          $ref: '#/components/schemas/SecurityGroupName'
        display_name:
          $ref: '#/components/schemas/SecurityGroupDisplayName'
        role:
          $ref: '#/components/schemas/SecurityGroupRole'
        description:
          $ref: '#/components/schemas/SecurityGroupDescription'
