//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressQualifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="AddressQualifierType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="residential"/>
 *     <enumeration value="correspondence"/>
 *     <enumeration value="self-employed-business"/>
 *     <enumeration value="business"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "AddressQualifierType")
@XmlEnum
public enum AddressQualifierType {

    @XmlEnumValue("residential")
    RESIDENTIAL("residential"),
    @XmlEnumValue("correspondence")
    CORRESPONDENCE("correspondence"),
    @XmlEnumValue("self-employed-business")
    SELF_EMPLOYED_BUSINESS("self-employed-business"),
    @XmlEnumValue("business")
    BUSINESS("business");
    private final String value;

    AddressQualifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AddressQualifierType fromValue(String v) {
        for (AddressQualifierType c: AddressQualifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
