//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmailStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="EmailStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="EmailAddress" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}RestrictedStringType"/>
 *       </sequence>
 *       <attribute name="EmailUsage" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}WorkHomeType" />
 *       <attribute name="EmailPreferred" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}YesNoType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmailStructure", propOrder = {
    "emailAddress"
})
public class EmailStructure {

    @XmlElement(name = "EmailAddress", required = true)
    protected String emailAddress;
    @XmlAttribute(name = "EmailUsage")
    protected WorkHomeType emailUsage;
    @XmlAttribute(name = "EmailPreferred")
    protected YesNoType emailPreferred;

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the emailUsage property.
     * 
     * @return
     *     possible object is
     *     {@link WorkHomeType }
     *     
     */
    public WorkHomeType getEmailUsage() {
        return emailUsage;
    }

    /**
     * Sets the value of the emailUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkHomeType }
     *     
     */
    public void setEmailUsage(WorkHomeType value) {
        this.emailUsage = value;
    }

    /**
     * Gets the value of the emailPreferred property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getEmailPreferred() {
        return emailPreferred;
    }

    /**
     * Sets the value of the emailPreferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setEmailPreferred(YesNoType value) {
        this.emailPreferred = value;
    }

}
