//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.bs7666.BSaddressStructure;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the uk.gov.govtalk.people.addressandpersonaldetails package.
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _UKAddressStructureBS7666Address_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "BS7666Address");
    private static final QName _UKAddressStructureA5LineAddress_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "A_5LineAddress");
    private static final QName _UKAddressStructureUniquePropertyReferenceNumber_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "UniquePropertyReferenceNumber");
    private static final QName _UKAddressStructureSortCode_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "SortCode");
    private static final QName _UKAddressStructureWalkSort_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "WalkSort");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.govtalk.people.addressandpersonaldetails
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InternationalAddressStructure }
     *
     * @return
     *     the new instance of {@link InternationalAddressStructure }
     */
    public InternationalAddressStructure createInternationalAddressStructure() {
        return new InternationalAddressStructure();
    }

    /**
     * Create an instance of {@link UKPostalAddressStructure }
     *
     * @return
     *     the new instance of {@link UKPostalAddressStructure }
     */
    public UKPostalAddressStructure createUKPostalAddressStructure() {
        return new UKPostalAddressStructure();
    }

    /**
     * Create an instance of {@link UKAddressStructure }
     *
     * @return
     *     the new instance of {@link UKAddressStructure }
     */
    public UKAddressStructure createUKAddressStructure() {
        return new UKAddressStructure();
    }

    /**
     * Create an instance of {@link TelephoneStructure }
     *
     * @return
     *     the new instance of {@link TelephoneStructure }
     */
    public TelephoneStructure createTelephoneStructure() {
        return new TelephoneStructure();
    }

    /**
     * Create an instance of {@link FaxStructure }
     *
     * @return
     *     the new instance of {@link FaxStructure }
     */
    public FaxStructure createFaxStructure() {
        return new FaxStructure();
    }

    /**
     * Create an instance of {@link EmailStructure }
     *
     * @return
     *     the new instance of {@link EmailStructure }
     */
    public EmailStructure createEmailStructure() {
        return new EmailStructure();
    }

    /**
     * Create an instance of {@link NHSnumberStructure }
     *
     * @return
     *     the new instance of {@link NHSnumberStructure }
     */
    public NHSnumberStructure createNHSnumberStructure() {
        return new NHSnumberStructure();
    }

    /**
     * Create an instance of {@link CitizenNameStructure }
     *
     * @return
     *     the new instance of {@link CitizenNameStructure }
     */
    public CitizenNameStructure createCitizenNameStructure() {
        return new CitizenNameStructure();
    }

    /**
     * Create an instance of {@link CitizenRegistrationStructure }
     *
     * @return
     *     the new instance of {@link CitizenRegistrationStructure }
     */
    public CitizenRegistrationStructure createCitizenRegistrationStructure() {
        return new CitizenRegistrationStructure();
    }

    /**
     * Create an instance of {@link CitizenDetailsStructure }
     *
     * @return
     *     the new instance of {@link CitizenDetailsStructure }
     */
    public CitizenDetailsStructure createCitizenDetailsStructure() {
        return new CitizenDetailsStructure();
    }

    /**
     * Create an instance of {@link CitizenContactDetailsStructure }
     *
     * @return
     *     the new instance of {@link CitizenContactDetailsStructure }
     */
    public CitizenContactDetailsStructure createCitizenContactDetailsStructure() {
        return new CitizenContactDetailsStructure();
    }

    /**
     * Create an instance of {@link CitizenBirthDateStructure }
     *
     * @return
     *     the new instance of {@link CitizenBirthDateStructure }
     */
    public CitizenBirthDateStructure createCitizenBirthDateStructure() {
        return new CitizenBirthDateStructure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BSaddressStructure }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BSaddressStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "BS7666Address", scope = UKAddressStructure.class)
    public JAXBElement<BSaddressStructure> createUKAddressStructureBS7666Address(BSaddressStructure value) {
        return new JAXBElement<>(_UKAddressStructureBS7666Address_QNAME, BSaddressStructure.class, UKAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UKPostalAddressStructure }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UKPostalAddressStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "A_5LineAddress", scope = UKAddressStructure.class)
    public JAXBElement<UKPostalAddressStructure> createUKAddressStructureA5LineAddress(UKPostalAddressStructure value) {
        return new JAXBElement<>(_UKAddressStructureA5LineAddress_QNAME, UKPostalAddressStructure.class, UKAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "UniquePropertyReferenceNumber", scope = UKAddressStructure.class)
    public JAXBElement<Long> createUKAddressStructureUniquePropertyReferenceNumber(Long value) {
        return new JAXBElement<>(_UKAddressStructureUniquePropertyReferenceNumber_QNAME, Long.class, UKAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "SortCode", scope = UKAddressStructure.class)
    public JAXBElement<String> createUKAddressStructureSortCode(String value) {
        return new JAXBElement<>(_UKAddressStructureSortCode_QNAME, String.class, UKAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "WalkSort", scope = UKAddressStructure.class)
    public JAXBElement<String> createUKAddressStructureWalkSort(String value) {
        return new JAXBElement<>(_UKAddressStructureWalkSort_QNAME, String.class, UKAddressStructure.class, value);
    }

}
