//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.bs7666.BSaddressStructure;

import java.util.ArrayList;
import java.util.List;


/**
 * Supports BS7666 address types.
 *
 * <p>Java class for UKAddressStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="UKAddressStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice>
 *           <element name="BS7666Address" type="{http://www.govtalk.gov.uk/people/bs7666}BSaddressStructure"/>
 *           <sequence>
 *             <element name="A_5LineAddress" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}UKPostalAddressStructure"/>
 *             <element name="BS7666Address" type="{http://www.govtalk.gov.uk/people/bs7666}BSaddressStructure" minOccurs="0"/>
 *           </sequence>
 *         </choice>
 *         <element name="UniquePropertyReferenceNumber" type="{http://www.govtalk.gov.uk/people/bs7666}UPRNtype" minOccurs="0"/>
 *         <choice>
 *           <element name="SortCode" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}MailSortCodeType" minOccurs="0"/>
 *           <element name="WalkSort" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}WalkSortCodeType" minOccurs="0"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UKAddressStructure", propOrder = {
    "content"
})
public class UKAddressStructure {

    @XmlElementRefs({
        @XmlElementRef(name = "BS7666Address", namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "A_5LineAddress", namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "UniquePropertyReferenceNumber", namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SortCode", namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "WalkSort", namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model.
     *
     * <p>
     * You are getting this "catch-all" property because of the following reason:
     * The field name "BS7666Address" is used by two different parts of a schema. See:
     * line 97 of file:/Users/chrismagowan/Documents/code/darts-gateway/src/main/resources/schemas/xhibit/AddressTypes.xsd
     * line 94 of file:/Users/chrismagowan/Documents/code/darts-gateway/src/main/resources/schemas/xhibit/AddressTypes.xsd
     * <p>
     * To get rid of this property, apply a property customization to one
     * of both of the following declarations to change their names:Gets the value of the content property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the content property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link UKPostalAddressStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link BSaddressStructure }{@code >}
     *
     *
     * @return
     *     The value of the content property.
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<>();
        }
        return this.content;
    }

}
