insert into security_group_courthouse_ae(grp_id, cth_id)
VALUES ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_ipswich_appr'), (SELECT cth_id FROM courthouse WHERE courthouse_name = 'IPSWICH')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_ipswich_staff'), (SELECT cth_id FROM courthouse WHERE courthouse_name = 'IPSWICH')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_kingston_upon_h_appr'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'KINGSTON UPON HULL')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_kingston_upon_h_staff'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'KINGSTON UPON HULL')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_linc_crown_sitt_appr'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'LINC CROWN SITTING AT LINC MAGS')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_linc_crown_sitt_staff'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'LINC CROWN SITTING AT LINC MAGS')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_rolls_building1_appr'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'RCJROLLSCH2')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_rolls_building1_staff'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'RCJROLLSCH2')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_rolls_building2_appr'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'RCJROLLSCH3')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_rolls_building2_staff'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'RCJROLLSCH3')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_rolls_building3_appr'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'RCJROLLSCH4')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_rolls_building3_staff'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'RCJROLLSCH4')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_rolls_building_appr'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'RCJROLLSCH1')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_rolls_building_staff'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'RCJROLLSCH1')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_west_midlands_c_appr'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'WEST MIDLANDS COURT CENTRE')),
       ((SELECT grp_id FROM security_group WHERE group_name = 'moj_ch_west_midlands_c_staff'),
        (SELECT cth_id FROM courthouse WHERE courthouse_name = 'WEST MIDLANDS COURT CENTRE'));