management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
spring:
  datasource:
    username: darts
    password: darts
  flyway:
    locations: classpath:db/migration/common,db/migration/postgres,db/migration/local
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
darts:
  event-obfuscation:
    enabled: true
  daily-list:
    housekeeping:
      enabled: false
  testing-support-endpoints:
    enabled: ${TESTING_SUPPORT_ENDPOINTS_ENABLED:true}
  redis:
    ssl-enabled: false
  storage:
    arm-api:
      url: ${ARM_URL:http://localhost:4551}
      arm-service-entitlement: "SRV-DARTS-RW-E" # Per the entitlements[*].name value specified in darts-stub-services getProfileEntitlements
      arm-storage-account-name: "local"
    blob:
      az-copy-log-level: "--log-level=INFO"
      az-copy-output-level: "--output-level=default"
logging:
  level:
    uk.gov.hmcts.darts: DEBUG
