management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
spring:
  datasource:
    username: darts
    password: darts
  flyway:
    locations: classpath:db/migration/common,db/migration/postgres,db/migration/local1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
darts:
  daily-list:
    housekeeping:
      enabled: false
  testing-support-endpoints:
    enabled: ${TESTING_SUPPORT_ENDPOINTS_ENABLED:true}
  redis:
    ssl-enabled: false
  storage:
    arm-api:
      url: ${ARM_URL:http://localhost:4551}

logging:
  level:
    uk.gov.hmcts.darts: DEBUG
