server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.darts

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/darts/"
  application:
    name: Darts Api
  security:
    oauth2:
      client:
        registration:
          external-azure-ad:
            client-id: 392deeb8-5557-4f96-ae71-ff8be62f0db8
            client-secret: hs~8Q~xpluVDuvP0FCvr1bUqfwT68HsDaPy5saRi
            scope: openid
            redirect-uri: https://darts-api.staging.platform.hmcts.net/external-user/handle-oauth-code
            authorization-grant-type: authorization_code
            response-type: code
            response-mode: form_post
            prompt: login
            issuer-uri: https://hmctsdartsb2csbox.b2clogin.com/89b8de2e-eb1b-42fb-a59c-813ea2b82a56/v2.0/
            provider: external-azure-ad-provider
        provider:
          external-azure-ad-provider:
            authorization-uri: https://hmctsdartsb2csbox.b2clogin.com/hmctsdartsb2csbox.onmicrosoft.com/B2C_1_darts_externaluser_signin/oauth2/v2.0/authorize
            token-uri: https://hmctsdartsb2csbox.b2clogin.com/hmctsdartsb2csbox.onmicrosoft.com/B2C_1_darts_externaluser_signin/oauth2/v2.0/token
            jwk-set-uri: https://hmctsdartsb2csbox.b2clogin.com/hmctsdartsb2csbox.onmicrosoft.com/B2C_1_darts_externaluser_signin/discovery/v2.0/keys


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DARTS_API_DB_HOST:localhost}:${DARTS_API_DB_PORT:6968}/${DARTS_API_DB_NAME:DARTS_API}${DARTS_API_DB_OPTIONS:}
    username: ${DARTS_API_DB_USERNAME:darts}
    password: ${DARTS_API_DB_PASSWORD:darts}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            store_data_at_delete: true

  flyway:
    out-of-order: true
    ignore-missing-migrations: true


# ATS
audiotransform:
  ffmpeg-executable: ${user.home}/audiotransform/ffmpeg
  concat-workspace: ${user.home}/audiotransform/concat

azure:
  application-insights:
    instrumentation-key: ${darts.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

darts:
  notification:
    max_retry_attempts: 3
    gov-notify:
      api-key: ${darts.GovNotifyApiKey:00000000-0000-0000-0000-000000000000}
      template-map:
        court_manager_approve_transcript: 2f9e18b5-5046-44c2-8abd-e4ff15008a60
        request_to_transcriber: 976bf288-705d-4cbb-b24f-c5529abf14cf
        requested_audio_is_available: 66a1864f-24a6-469a-ac55-66bc57c7e4f6
