server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.darts

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/darts/"
  application:
    name: Darts Api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${api_DB_HOST:localhost}:${api_DB_PORT:5432}/${api_DB_NAME:darts_api}${api_DB_OPTIONS:}
    username: ${api_DB_USERNAME:darts}
    password: ${api_DB_PASSWORD:darts}
    hikari:
      minimumIdle: ${api_DB_MIN_IDLE:2}
      maximumPoolSize: ${api_DB_MAX_POOL_SIZE:8}
      idleTimeout: ${api_DB_IDLE_TIMEOUT:300000}
      maxLifetime: ${api_DB_MAX_LIFTIME:7200000}
      connectionTimeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    generate-ddl: 'true'
    hibernate:
      # this ensures the db persists after spring boot connection drops.
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  # This is needed as locally, all tables are in a single schema. Flyway is only enabled on the clusters by default
  flyway:
    ignore-missing-migrations: 'true'
    baseline-version: '0001'
    out-of-order: 'true'
    baseline-on-migrate: 'true'

azure:
  application-insights:
    instrumentation-key: ${darts.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
