spring:
  datasource:
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    uk.gov.hmcts.darts: DEBUG
