spring:
  datasource:
    #see "PostgreSQL Compatibility Mode" https://h2database.com/html/features.html#compatibility
    url: jdbc:h2:mem:darts;TIME ZONE=UTC;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: ${ENABLE_DB_MIGRATE:true}
    locations: classpath:db/migration/common,db/migration/h2
