spring:
  datasource:
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    uk.gov.hmcts.darts: DEBUG
