spring:
  cloud:
    azure:
      active-directory:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DARTS_API_DB_HOST:darts-api-stg.postgres.database.azure.com}:${DARTS_API_DB_PORT:5432}/${DARTS_API_DB_NAME:darts}${DARTS_API_DB_OPTIONS:}
    username: ${DARTS_API_DB_USERNAME:pgadmin}
    password: ${DARTS_API_DB_PASSWORD:PQuEyVaUAxqu0UeNUo8(}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  autoconfigure:
    exclude:
      - "org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration"
      - "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration"

