spring:
  datasource:
    url: jdbc:h2:mem:darts;TIME ZONE=UTC;DATABASE_TO_UPPER=false;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: ${ENABLE_DB_MIGRATE:true}
    locations: classpath:db/migration/common,db/migration/h2
