server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.darts

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/darts/"
  application:
    name: Darts Api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${DB_PORT}/postgres
    username: ${DB_USER}
    password: ${DB_PASS}
   properties:
     charSet: UTF-8
   hikari:
     minimumIdle: 2
     maximumPoolSize: 10
     idleTimeout: 10000
     poolName: ConnectionPool
     maxLifetime: 7200000
     connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    generate-ddl: 'true'
    hibernate:
      # this ensures the db persists after spring boot connection drops.
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  # This is needed as locally, all tables are in a single schema. Flyway is only enabled on the clusters by default
  flyway:
    enabled: ${ENABLE_FLYWAY:false}

azure:
  application-insights:
    instrumentation-key: ${darts.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
