spring:
  datasource:
    #see "PostgreSQL Compatibility Mode" https://h2database.com/html/features.html#compatibility
    url: jdbc:postgresql://${DARTS_API_DB_HOST:localhost}:${spring.datasource.port}/${DARTS_API_DB_NAME:darts}${DARTS_API_DB_OPTIONS:}
    username: test
    password: test
    port:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    schema: ${DARTS_API_DB_SCHEMA:darts}
    hikari:
      maximum-pool-size: 50
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.datasource.schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
          time_zone: UTC
  flyway:
    enabled: ${ENABLE_DB_MIGRATE:true}
    locations: classpath:db/migration/common,db/migration/h2
    mixed: true