spring:
  datasource:
    username: darts
    password: darts
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
darts:
  daily-list:
    housekeeping:
      enabled: false
      cron: ${DAILY_LIST_HOUSEKEEPING_SCHEDULER_CRON:4 0/2 * * * MON-FRI}
  testing-support-endpoints:
    enabled: ${TESTING_SUPPORT_ENDPOINTS_ENABLED:true}

logging:
  level:
    uk.gov.hmcts.darts: DEBUG
