//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.bs7666;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BLPUpolygonStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="BLPUpolygonStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="PolygonID">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               <minInclusive value="1"/>
 *               <maxInclusive value="99"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PolygonType" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="H"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <choice>
 *           <element name="Vertices" type="{http://www.govtalk.gov.uk/people/bs7666}CoordinateStructure" maxOccurs="unbounded" minOccurs="3"/>
 *           <element name="ExternalRef" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BLPUpolygonStructure", propOrder = {
    "polygonID",
    "polygonType",
    "vertices",
    "externalRef"
})
public class BLPUpolygonStructure {

    @XmlElement(name = "PolygonID")
    protected int polygonID;
    @XmlElement(name = "PolygonType")
    protected String polygonType;
    @XmlElement(name = "Vertices")
    protected List<CoordinateStructure> vertices;
    @XmlElement(name = "ExternalRef")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger externalRef;

    /**
     * Gets the value of the polygonID property.
     *
     */
    public int getPolygonID() {
        return polygonID;
    }

    /**
     * Sets the value of the polygonID property.
     *
     */
    public void setPolygonID(int value) {
        this.polygonID = value;
    }

    /**
     * Gets the value of the polygonType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPolygonType() {
        return polygonType;
    }

    /**
     * Sets the value of the polygonType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPolygonType(String value) {
        this.polygonType = value;
    }

    /**
     * Gets the value of the vertices property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the vertices property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVertices().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinateStructure }
     *
     *
     * @return
     *     The value of the vertices property.
     */
    public List<CoordinateStructure> getVertices() {
        if (vertices == null) {
            vertices = new ArrayList<>();
        }
        return this.vertices;
    }

    /**
     * Gets the value of the externalRef property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getExternalRef() {
        return externalRef;
    }

    /**
     * Sets the value of the externalRef property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setExternalRef(BigInteger value) {
        this.externalRef = value;
    }

}
