//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.bs7666;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BSaddressStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="BSaddressStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="SAON" type="{http://www.govtalk.gov.uk/people/bs7666}SAONtype" minOccurs="0"/>
 *         <element name="PAON" type="{http://www.govtalk.gov.uk/people/bs7666}PAONtype"/>
 *         <sequence>
 *           <element name="StreetDescription" type="{http://www.govtalk.gov.uk/people/bs7666}StreetDescriptorType"/>
 *           <element name="UniqueStreetReferenceNumber" type="{http://www.govtalk.gov.uk/people/bs7666}USRNtype" minOccurs="0"/>
 *         </sequence>
 *         <choice>
 *           <sequence>
 *             <element ref="{http://www.govtalk.gov.uk/people/bs7666}Locality"/>
 *             <choice minOccurs="0">
 *               <sequence>
 *                 <element ref="{http://www.govtalk.gov.uk/people/bs7666}Town"/>
 *                 <element ref="{http://www.govtalk.gov.uk/people/bs7666}AdministrativeArea" minOccurs="0"/>
 *               </sequence>
 *               <element ref="{http://www.govtalk.gov.uk/people/bs7666}AdministrativeArea"/>
 *             </choice>
 *           </sequence>
 *           <sequence>
 *             <element ref="{http://www.govtalk.gov.uk/people/bs7666}Town"/>
 *             <element ref="{http://www.govtalk.gov.uk/people/bs7666}AdministrativeArea" minOccurs="0"/>
 *           </sequence>
 *           <element ref="{http://www.govtalk.gov.uk/people/bs7666}AdministrativeArea"/>
 *         </choice>
 *         <element name="PostTown" type="{http://www.govtalk.gov.uk/people/bs7666}PosttownType" minOccurs="0"/>
 *         <element name="Postcode" type="{http://www.govtalk.gov.uk/people/bs7666}PostcodeType" minOccurs="0"/>
 *         <element name="UniquePropertyReferenceNumber" type="{http://www.govtalk.gov.uk/people/bs7666}UPRNtype" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BSaddressStructure", propOrder = {
    "content"
})
public class BSaddressStructure {

    @XmlElementRefs({
        @XmlElementRef(name = "SAON", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PAON", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "StreetDescription", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "UniqueStreetReferenceNumber", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Locality", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Town", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AdministrativeArea", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PostTown", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Postcode", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "UniquePropertyReferenceNumber", namespace = "http://www.govtalk.gov.uk/people/bs7666", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> content;

    /**
     * Gets the rest of the content model.
     *
     * <p>
     * You are getting this "catch-all" property because of the following reason:
     * The field name "AdministrativeArea" is used by two different parts of a schema. See:
     * line 77 of file:/Users/chrismagowan/Documents/code/darts-gateway/src/main/resources/schemas/xhibit/BS7666.xsd
     * line 75 of file:/Users/chrismagowan/Documents/code/darts-gateway/src/main/resources/schemas/xhibit/BS7666.xsd
     * <p>
     * To get rid of this property, apply a property customization to one
     * of both of the following declarations to change their names:Gets the value of the content property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the content property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     *
     * @return
     *     The value of the content property.
     */
    public List<JAXBElement<? extends Serializable>> getContent() {
        if (content == null) {
            content = new ArrayList<>();
        }
        return this.content;
    }

}
