//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.bs7666;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the uk.gov.govtalk.people.bs7666 package.
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Town_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "Town");
    private static final QName _Locality_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "Locality");
    private static final QName _AdministrativeArea_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "AdministrativeArea");
    private static final QName _UniquePropertyReferenceNumber_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "UniquePropertyReferenceNumber");
    private static final QName _BS7666Address_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "BS7666Address");
    private static final QName _BS7666BLPU_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "BS7666BLPU");
    private static final QName _StreetDescriptiveIdentifierStructureStreetDescription_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "StreetDescription");
    private static final QName _BSaddressStructureSAON_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "SAON");
    private static final QName _BSaddressStructurePAON_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "PAON");
    private static final QName _BSaddressStructureUniqueStreetReferenceNumber_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "UniqueStreetReferenceNumber");
    private static final QName _BSaddressStructurePostTown_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "PostTown");
    private static final QName _BSaddressStructurePostcode_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "Postcode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.govtalk.people.bs7666
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StreetStructure }
     *
     * @return
     *     the new instance of {@link StreetStructure }
     */
    public StreetStructure createStreetStructure() {
        return new StreetStructure();
    }

    /**
     * Create an instance of {@link BSaddressStructure }
     *
     * @return
     *     the new instance of {@link BSaddressStructure }
     */
    public BSaddressStructure createBSaddressStructure() {
        return new BSaddressStructure();
    }

    /**
     * Create an instance of {@link BasicLandAndPropertyUnitStructure }
     *
     * @return
     *     the new instance of {@link BasicLandAndPropertyUnitStructure }
     */
    public BasicLandAndPropertyUnitStructure createBasicLandAndPropertyUnitStructure() {
        return new BasicLandAndPropertyUnitStructure();
    }

    /**
     * Create an instance of {@link StreetDescriptiveIdentifierStructure }
     *
     * @return
     *     the new instance of {@link StreetDescriptiveIdentifierStructure }
     */
    public StreetDescriptiveIdentifierStructure createStreetDescriptiveIdentifierStructure() {
        return new StreetDescriptiveIdentifierStructure();
    }

    /**
     * Create an instance of {@link ElementaryStreetUnitStructure }
     *
     * @return
     *     the new instance of {@link ElementaryStreetUnitStructure }
     */
    public ElementaryStreetUnitStructure createElementaryStreetUnitStructure() {
        return new ElementaryStreetUnitStructure();
    }

    /**
     * Create an instance of {@link CoordinateStructure }
     *
     * @return
     *     the new instance of {@link CoordinateStructure }
     */
    public CoordinateStructure createCoordinateStructure() {
        return new CoordinateStructure();
    }

    /**
     * Create an instance of {@link BLPUpolygonStructure }
     *
     * @return
     *     the new instance of {@link BLPUpolygonStructure }
     */
    public BLPUpolygonStructure createBLPUpolygonStructure() {
        return new BLPUpolygonStructure();
    }

    /**
     * Create an instance of {@link BLPUextentStructure }
     *
     * @return
     *     the new instance of {@link BLPUextentStructure }
     */
    public BLPUextentStructure createBLPUextentStructure() {
        return new BLPUextentStructure();
    }

    /**
     * Create an instance of {@link ProvenanceStructure }
     *
     * @return
     *     the new instance of {@link ProvenanceStructure }
     */
    public ProvenanceStructure createProvenanceStructure() {
        return new ProvenanceStructure();
    }

    /**
     * Create an instance of {@link LandAndPropertyIdentifierStructure }
     *
     * @return
     *     the new instance of {@link LandAndPropertyIdentifierStructure }
     */
    public LandAndPropertyIdentifierStructure createLandAndPropertyIdentifierStructure() {
        return new LandAndPropertyIdentifierStructure();
    }

    /**
     * Create an instance of {@link StreetStructure.StreetCrossReferences }
     *
     * @return
     *     the new instance of {@link StreetStructure.StreetCrossReferences }
     */
    public StreetStructure.StreetCrossReferences createStreetStructureStreetCrossReferences() {
        return new StreetStructure.StreetCrossReferences();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "Town")
    public JAXBElement<String> createTown(String value) {
        return new JAXBElement<>(_Town_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "Locality")
    public JAXBElement<String> createLocality(String value) {
        return new JAXBElement<>(_Locality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "AdministrativeArea")
    public JAXBElement<String> createAdministrativeArea(String value) {
        return new JAXBElement<>(_AdministrativeArea_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "UniquePropertyReferenceNumber")
    public JAXBElement<Long> createUniquePropertyReferenceNumber(Long value) {
        return new JAXBElement<>(_UniquePropertyReferenceNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BSaddressStructure }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BSaddressStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "BS7666Address")
    public JAXBElement<BSaddressStructure> createBS7666Address(BSaddressStructure value) {
        return new JAXBElement<>(_BS7666Address_QNAME, BSaddressStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicLandAndPropertyUnitStructure }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BasicLandAndPropertyUnitStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "BS7666BLPU")
    public JAXBElement<BasicLandAndPropertyUnitStructure> createBS7666BLPU(BasicLandAndPropertyUnitStructure value) {
        return new JAXBElement<>(_BS7666BLPU_QNAME, BasicLandAndPropertyUnitStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "StreetDescription", scope = StreetDescriptiveIdentifierStructure.class)
    public JAXBElement<String> createStreetDescriptiveIdentifierStructureStreetDescription(String value) {
        return new JAXBElement<>(_StreetDescriptiveIdentifierStructureStreetDescription_QNAME, String.class, StreetDescriptiveIdentifierStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "SAON", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructureSAON(String value) {
        return new JAXBElement<>(_BSaddressStructureSAON_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "PAON", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructurePAON(String value) {
        return new JAXBElement<>(_BSaddressStructurePAON_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "StreetDescription", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructureStreetDescription(String value) {
        return new JAXBElement<>(_StreetDescriptiveIdentifierStructureStreetDescription_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "UniqueStreetReferenceNumber", scope = BSaddressStructure.class)
    public JAXBElement<Integer> createBSaddressStructureUniqueStreetReferenceNumber(Integer value) {
        return new JAXBElement<>(_BSaddressStructureUniqueStreetReferenceNumber_QNAME, Integer.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "PostTown", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructurePostTown(String value) {
        return new JAXBElement<>(_BSaddressStructurePostTown_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "Postcode", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructurePostcode(String value) {
        return new JAXBElement<>(_BSaddressStructurePostcode_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "UniquePropertyReferenceNumber", scope = BSaddressStructure.class)
    public JAXBElement<Long> createBSaddressStructureUniquePropertyReferenceNumber(Long value) {
        return new JAXBElement<>(_UniquePropertyReferenceNumber_QNAME, Long.class, BSaddressStructure.class, value);
    }

}
