//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.bs7666;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProvenanceStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="ProvenanceStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ProvenanceCode" type="{http://www.govtalk.gov.uk/people/bs7666}ProvenanceCodeType"/>
 *         <element name="Annotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="ProvEntryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="ProvStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="ProvEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="ProvLastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="BLPUextent" type="{http://www.govtalk.gov.uk/people/bs7666}BLPUextentStructure" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProvenanceStructure", propOrder = {
    "provenanceCode",
    "annotation",
    "provEntryDate",
    "provStartDate",
    "provEndDate",
    "provLastUpdateDate",
    "blpUextent"
})
public class ProvenanceStructure {

    @XmlElement(name = "ProvenanceCode", required = true)
    @XmlSchemaType(name = "string")
    protected ProvenanceCodeType provenanceCode;
    @XmlElement(name = "Annotation", required = true)
    protected String annotation;
    @XmlElement(name = "ProvEntryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar provEntryDate;
    @XmlElement(name = "ProvStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar provStartDate;
    @XmlElement(name = "ProvEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar provEndDate;
    @XmlElement(name = "ProvLastUpdateDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar provLastUpdateDate;
    @XmlElement(name = "BLPUextent")
    protected BLPUextentStructure blpUextent;

    /**
     * Gets the value of the provenanceCode property.
     *
     * @return
     *     possible object is
     *     {@link ProvenanceCodeType }
     *
     */
    public ProvenanceCodeType getProvenanceCode() {
        return provenanceCode;
    }

    /**
     * Sets the value of the provenanceCode property.
     *
     * @param value
     *     allowed object is
     *     {@link ProvenanceCodeType }
     *
     */
    public void setProvenanceCode(ProvenanceCodeType value) {
        this.provenanceCode = value;
    }

    /**
     * Gets the value of the annotation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAnnotation(String value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the provEntryDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getProvEntryDate() {
        return provEntryDate;
    }

    /**
     * Sets the value of the provEntryDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setProvEntryDate(XMLGregorianCalendar value) {
        this.provEntryDate = value;
    }

    /**
     * Gets the value of the provStartDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getProvStartDate() {
        return provStartDate;
    }

    /**
     * Sets the value of the provStartDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setProvStartDate(XMLGregorianCalendar value) {
        this.provStartDate = value;
    }

    /**
     * Gets the value of the provEndDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getProvEndDate() {
        return provEndDate;
    }

    /**
     * Sets the value of the provEndDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setProvEndDate(XMLGregorianCalendar value) {
        this.provEndDate = value;
    }

    /**
     * Gets the value of the provLastUpdateDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getProvLastUpdateDate() {
        return provLastUpdateDate;
    }

    /**
     * Sets the value of the provLastUpdateDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setProvLastUpdateDate(XMLGregorianCalendar value) {
        this.provLastUpdateDate = value;
    }

    /**
     * Gets the value of the blpUextent property.
     *
     * @return
     *     possible object is
     *     {@link BLPUextentStructure }
     *
     */
    public BLPUextentStructure getBLPUextent() {
        return blpUextent;
    }

    /**
     * Sets the value of the blpUextent property.
     *
     * @param value
     *     allowed object is
     *     {@link BLPUextentStructure }
     *
     */
    public void setBLPUextent(BLPUextentStructure value) {
        this.blpUextent = value;
    }

}
