insert into retention_policy_type_heritage_mapping (rhm_id, heritage_policy_name, heritage_table, modernised_rpt_id)
values (1, 'DARTS - Rollover Policy', 'moj_rps_retention_policy', 11),
       (2, 'DARTS - 7 Years  Retention Policy', 'moj_rps_retention_policy', 11),
       (3, 'DARTS Rollover policy', 'moj_rps_retention_policy', 11),
       (4, 'DARTS V2 - Rollover Policy', 'moj_rps_retention_policy', 11),
       (5, 'DARTS - 30 Years Retention Policy', 'moj_rps_retention_policy', 10),
       (6, 'DARTS - Standard Retention Policy', 'moj_rps_retention_policy', 11),
       (7, 'DARTS -  Permanent Policy', 'moj_rps_retention_policy', 10),
       (8, 'DARTS Standard Retention', 'moj_rps_retention_policy', 11),
       (9, 'DARTS V2 - Standard Retention Policy', 'moj_rps_retention_policy', 11),
       (10, 'DARTS V2 - Permanent Retention Policy', 'moj_rps_retention_policy', 10),
       (11, 'DARTS Permanent Retention', 'moj_rps_retention_policy', 10),
       (12, 'DARTS Permanent Retention v3', 'moj_rps_retention_policy', 1),
       (13, 'DARTS Standard Retention v3', 'moj_rps_retention_policy', 2),
       (14, 'DARTS Not Guilty Policy', 'moj_rps_retention_policy', 3),
       (15, 'DARTS Custodial Policy', 'moj_rps_retention_policy', 5),
       (16, 'DARTS Non Custodial Policy', 'moj_rps_retention_policy', 4),
       (17, 'DARTS Life Policy', 'moj_rps_retention_policy', 6),
       (18, 'single space', 'moj_case', 7),
       (19, 'null', 'moj_case', 7),
       (20, 'NOT_GUILTY', 'moj_case', 3),
       (21, 'CUSTODIAL', 'moj_case', 5),
       (22, 'MANUAL', 'moj_case', 9),
       (23, 'NON_CUSTODIAL', 'moj_case', 4),
       (24, 'LIFE', 'moj_case', 6),
       (25, 'PERM', 'moj_case', 8),
       (26, 'single space', 'moj_case_retention_audit', 7),
       (27, 'NOT_GUILTY', 'moj_case_retention_audit', 3),
       (28, 'CUSTODIAL', 'moj_case_retention_audit', 5),
       (29, 'MANUAL', 'moj_case_retention_audit', 9),
       (30, 'NON_CUSTODIAL', 'moj_case_retention_audit', 4),
       (31, 'LIFE', 'moj_case_retention_audit', 6),
       (32, 'PERM', 'moj_case_retention_audit', 8);
