-- update courthouse theTable set created_by = 0 where created_by is null or not exists (select 1 from user_account ua where ua.usr_id = theTable.created_by);
-- ALTER TABLE courthouse ADD CONSTRAINT courthouse_created_by_fk FOREIGN KEY (created_by) REFERENCES user_account(usr_id);
-- ALTER TABLE courthouse ALTER COLUMN created_by SET NOT NULL;
--
-- update courthouse theTable set last_modified_by = 0 where last_modified_by is null or not exists (select 1 from user_account ua where ua.usr_id = theTable.last_modified_by);
-- ALTER TABLE courthouse ADD CONSTRAINT courthouse_modified_by_fk FOREIGN KEY (last_modified_by) REFERENCES user_account(usr_id);
-- ALTER TABLE courthouse ALTER COLUMN last_modified_by SET NOT NULL;
