apiVersion: v2
appVersion: "1.0"
description: A Helm chart for darts-darts-api App
name: darts-darts-darts-api
home: https://github.com/hmcts/darts-darts-api
version: 0.0.3
maintainers:
  - name: HMCTS darts team
dependencies:
  - name: java
    version: 4.0.12
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
