CREATE TABLE IF NOT EXISTS event_type (
  evt_id  INTEGER            NOT NULL
, evt_type        CHARACTER VARYING  NOT NULL
, sub_type    CHARACTER VARYING
, event_name  CHARACTER VARYING  NOT NULL
, handler     CHARACTER VARYING
, CONSTRAINT event_type_pkey PRIMARY KEY (evt_id)
);

CREATE SEQUENCE IF NOT EXISTS evt_seq;

INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (1, '1000', '1002', 'Proceedings in chambers', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (2, '1000', '1001', 'Offences put to defendant', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (3, '1000', '1062', 'Defendant sworn-in', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (4, '1000', '1063', 'Defendant examination in-chief', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (5, '1000', '1064', 'Defendant continued', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (6, '1000', '1065', 'Defendant cross-examined by Prosecution', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (7, '1000', '1066', 'Defendant cross-examined Defence', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (8, '1000', '1067', 'Re-examination', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (9, '1000', '1068', 'Defendant released', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (10, '1000', '1069', 'Defendant recalled', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (11, '1000', '1070', 'Defendant questioned by Judge', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (12, '1000', '1003', 'Prosecution opened', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (13, '1000', '1004', 'Voir dire', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (14, '1000', '1005', 'Prosecution closed case', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (15, '1000', '1006', 'Prosecution gave closing speech', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (16, '1000', '1007', 'Defence opened case', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (17, '1000', '1009', 'Defence closed case', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (18, '1000', '1010', 'Defence gave closing speech', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (19, '1000', '1011', 'Discussion on directions to be given to the jury', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (20, '1000', '1012', 'Discussion on juror irregularity', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (21, '1000', '1014', 'Discussion on contempt of court issues', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (22, '1000', '1022', 'Application: Goodyear indication', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (23, '1000', '1024', 'Application: No case to answer', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (24, '1000', '1027', 'Judge directed defendant', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (25, '1000', '1028', 'Judge directed jury', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (26, '1000', '1029', 'Judge gave a majority direction', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (27, '1000', '1026', 'Judge summing-up', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (28, '1000', '1052', 'Jury sworn-in', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (29, '1000', '1051', 'Jury in', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (30, '1000', '1053', 'Jury out', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (31, '1000', '1054', 'Jury retired', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (32, '1000', '1055', 'Jury returned', 'com.synapps.moj.dfs.handler.DARTSEventDARStartHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (33, '1000', '1056', 'Jury gave verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (34, '1000', '1057', 'Juror discharged', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (35, '1000', '1058', 'Jury discharged', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (36, '1000', '1059', 'Witness recalled', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (37, '1100', NULL, 'Hearing started', 'com.synapps.moj.dfs.handler.DARTSEventDARStartHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (38, '1200', NULL, 'Hearing ended', 'com.synapps.moj.dfs.handler.DARTSEventDARStopHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (39, '1400', NULL, 'Hearing paused', 'com.synapps.moj.dfs.handler.DARTSEventDARStopHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (40, '1500', NULL, 'Hearing resumed', 'com.synapps.moj.dfs.handler.DARTSEventDARStartHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (41, '2100', NULL, 'Defendant identified', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (42, '2198', '3900', 'Defendant arraigned', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (43, '2198', '3901', 'Defendant rearraigned', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (44, '2198', '3903', 'Prosecution responded', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (45, '2198', '3905', 'Defence responded', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (46, '2198', '3904', 'Mitigation', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (47, '2198', '3906', 'Discussion on ground rules', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (48, '2198', '3907', 'Discussion on basis of plea', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (49, '2198', '3918', 'Point of law raised', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (50, '2198', '3931', 'Prosecution application: Break fixture', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (51, '2198', '3932', 'Defence application: Break fixture', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (52, '2198', '3921', 'Prosecution application: Adjourn', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (53, '2198', '3986', 'Defence application: Adjourn', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (54, '2198', '3933', 'Judge directed on reporting restrictions', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (55, '2198', '3935', 'Judge directed Prosecution to obtain a report', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (56, '2198', '3936', 'Judge directed Defence to obtain a medical report', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (57, '2198', '3937', 'Judge directed Defence to obtain a psychiatric report', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (58, '2198', '3938', 'Judge directed Defence counsel to obtain a report', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (59, '2198', '3940', 'Judges ruling', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (60, '2198', '3934', 'Judge passed sentence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (61, '2199', NULL, 'Prosecution application', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (62, '2201', NULL, 'Defence application', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (63, '2902', '3964', 'Application: Fitness to plead', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (64, '2906', '3968', 'Witness gave pre-recorded evidence', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (65, '2907', '3969', 'Witness read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (66, '2908', '3970', 'Witness sworn-in', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (67, '2909', '3971', 'Witness examination in-chief', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (68, '2910', '3972', 'Witness continued', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (69, '2912', '3974', 'Re-examination', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (70, '2913', '3975', 'Witness released', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (71, '2914', '3976', 'Witness questioned by Judge', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (72, '2917', '3979', 'Interpreter sworn-in', 'com.synapps.moj.dfs.handler.DARTSEventInterpreterUsedHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (73, '2918', '3980', 'Intermediatory sworn-in', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (74, '2920', '3981', 'Probation gave oral PSR', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (75, '2933', '3982', 'Victim Personal Statement(s) read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (76, '2934', '3983', 'Unspecified event', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (77, '3000', NULL, 'Archive Case', 'com.synapps.moj.dfs.handler.DARTSEventStopAndCloseHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (78, '3010', NULL, 'Sentence Transcription Required', 'com.synapps.moj.dfs.handler.DARTSTranscriptionRequestHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (79, '4101', NULL, 'Witness cross-examined by Defence', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (80, '4102', NULL, 'Witness cross-examined by Prosecution', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (81, '10100', NULL, 'Case called on', 'com.synapps.moj.dfs.handler.DARTSEventDARStartHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (82, '10200', NULL, 'Defendant attendance', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (83, '10300', NULL, 'Prosecution addresses judge', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (84, '10400', NULL, 'Defence addresses judge', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (85, '10500', NULL, 'Resume', 'com.synapps.moj.dfs.handler.DARTSEventDARStartHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (86, '20100', NULL, 'Bench Warrant Issued', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (87, '20101', NULL, 'Bench Warrant Executed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (88, '20198', '13900', 'Acceptable guilty plea(s) entered late to some or all charges / counts on the charge sheet, offered for the first time by the defence.', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (89, '20198', '13901', 'Acceptable guilty plea(s) entered late to some or all charges / counts on the charge sheet, previously rejected by the prosecution.', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (90, '20198', '13902', 'Acceptable guilty plea(s) to alternative new charge (not previously on the charge sheet), first offered by defence.', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (91, '20198', '13903', 'Acceptable guilty plea(s) to alternative new charge (not previously on the charge sheet), previously rejected by the prosecution.', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (92, '20198', '13904', 'Defendant bound over, acceptable to prosecution - offered for the first by the defence.', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (93, '20198', '13905', 'Effective Trial.', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (94, '20198', '13906', 'Defendant bound over, now acceptable to prosecution - previously rejected by the prosecution', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (159, '20909', NULL, 'Defence closing speech', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (95, '20198', '13907', 'Unable to proceed with the trail because defendant incapable through alcohol/drugs', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (96, '20198', '13908', 'Defendant deceased', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (97, '20198', '13909', 'Prosecution end case: insufficient evidence', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (98, '20198', '13910', 'Prosecution end case: witness absent / withdrawn', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (99, '20198', '13911', 'Prosecution end case: public interest grounds', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (100, '20198', '13912', 'Prosecution end case: adjournment refused', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (101, '20198', '13913', 'Prosecution not ready: served late notice of additional evidence on defence', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (102, '20198', '13914', 'Prosecution not ready: specify in comments', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (103, '20198', '13915', 'Prosecution failed to disclose unused material', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (104, '20198', '13916', 'Prosecution witness adsent: police', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (105, '20198', '13917', 'Prosecution witness adsent: professional / expert', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (106, '20198', '13918', 'Prosecution witness adsent: other', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (107, '20198', '13919', 'Prosecution advocate engaged in another trial', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (108, '20198', '13920', 'Prosecution advocate failed to attend', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (109, '20198', '13921', 'Prosecution increased time estimate - insufficient time for trail to start', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (110, '20198', '13922', 'Defence not ready: disclosure problems', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (111, '20198', '13923', 'Defence not ready: specify in comments (inc. no instructions)', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (112, '20198', '13924', 'Defence asked for additional prosecution witness toattend', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (113, '20198', '13925', 'Defence witness absent', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (114, '20198', '13926', 'Defendant absent - did not proceed in absence (judicial discretion)', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (115, '20198', '13927', 'Defendant ill or otherwise unfit to proceed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (116, '20198', '13928', 'Defendant not produced by PECS', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (117, '20198', '13929', 'Defendant absent - unable to proceed as defendant not notified of place and time of hearing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (118, '20198', '13930', 'Defence increased time estimate - insufficient time to for trial to start', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (119, '20198', '13931', 'Defence advocate engaged in other trial', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (120, '20198', '13932', 'Defence advocate failed to attend', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (121, '20198', '13933', 'Defence dismissed advocate', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (122, '20198', '13934', 'Another case over-ran', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (123, '20198', '13935', 'Judge / magistrate availability', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (124, '20198', '13936', 'Case not reached / insufficient cases drop out / floater not reached', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (125, '20198', '13937', 'Equipment / accomodation failure', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (126, '20198', '13938', 'No interpreter available', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (127, '20198', '13939', 'Insufficient jurors available', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (128, '20198', '13940', 'Outstanding committals in a magistrates court', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (129, '20198', '13941', 'Outstanding committals in a Crown Court centre', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (130, '20200', NULL, 'Bail and custody', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (131, '20501', NULL, 'Indictment to be filed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (132, '20502', NULL, 'List from plea and direction hearing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (133, '20503', NULL, 'Certify readiness for trial', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (134, '20504', NULL, 'Directions form completed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (135, '20601', NULL, 'Appellant attendance', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (136, '20602', NULL, 'Respondant case opened', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (137, '20603', NULL, 'Appeal witness sworn in', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (138, '20604', NULL, 'Appeal witness released', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (139, '20605', NULL, 'Respondant case closed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (140, '20606', NULL, 'Appellant case opened', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (141, '20607', NULL, 'Appellant submissions', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (142, '20608', NULL, 'Appellant case closed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (143, '20609', NULL, 'Bench retires', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (144, '20612', NULL, 'Appeal interpreter sworn in', 'com.synapps.moj.dfs.handler.DARTSEventInterpreterUsedHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (145, '20613', NULL, 'Appeal witness continues', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (146, '20701', NULL, 'Application to stand out', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (147, '20702', NULL, 'Defence application', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (148, '20703', NULL, 'Judges ruling', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (149, '20704', NULL, 'Prosecution application', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (150, '20705', NULL, 'Other application', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (151, '20901', NULL, 'Time estimate', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (152, '20902', NULL, 'Jury sworn in', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (153, '20903', NULL, 'Prosecution opening', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (154, '20904', NULL, 'Witness sworn in', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (155, '20905', NULL, 'Witness released', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (156, '20906', NULL, 'Defence case opened', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (157, '20907', NULL, 'Prosecution closing speech', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (158, '20908', NULL, 'Prosecution case closed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (160, '20910', NULL, 'Defence case closed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (161, '20911', NULL, 'Summing up', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (162, '20912', NULL, 'Jury out', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (163, '20913', NULL, 'Jury returns', 'com.synapps.moj.dfs.handler.DARTSEventDARStartHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (164, '20914', NULL, 'Jury retire', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (165, '20915', NULL, 'Jury/Juror discharged', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (166, '20916', NULL, 'Judge addresses advocate', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (167, '20917', NULL, 'Interpretor sworn', 'com.synapps.moj.dfs.handler.DARTSEventInterpreterUsedHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (168, '20918', NULL, 'Cracked or ineffective trial', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (169, '20920', NULL, 'Witness continued', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (170, '20933', '10622', 'Judge sentences', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (171, '20934', '10623', 'Special measures application', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (172, '20935', '10630', 'Witness Read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (173, '20935', '10631', 'Defendant Read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (174, '20935', '10632', 'Interpreter Read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (175, '20935', '10633', 'Apellant Read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (176, '20936', '10630', 'Witness Read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (177, '20936', '10631', 'Defendant Read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (178, '20936', '10632', 'Interpreter Read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (179, '20936', '10633', 'Apellant Read', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (180, '21200', '10311', 'Bail Conditions Ceased - sentence deferred', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (181, '21200', '10312', 'Bail Conditions Ceased - defendant deceased', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (182, '21200', '10313', 'Bail Conditions Ceased - non-custodial sentence imposed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (183, '21200', '11000', 'Section 4(2) of the Contempt of Court Act 1981', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (184, '21200', '11001', 'Section 11 of the Contempt of Court Act 1981', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (185, '21200', '11002', 'Section 39 of the Children and Young Persons Act 1933', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (186, '21200', '11003', 'Section 4 of the Sexual Offenders (Amendment) Act 1976', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (187, '21200', '11004', 'Section 2 of the Sexual Offenders (Amendment) Act 1992', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (188, '21200', '11006', 'An order made under s45 of the Youth Justice and Criminal Evidence Act 1999', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (189, '21200', '11007', 'An order made under s45a of the Youth Justice and Criminal Evidence Act 1999', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (190, '21200', '11008', 'An order made under s46 of the Youth Justice and Criminal Evidence Act 1999', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (191, '21200', '11009', 'An order made under s49 of the Children and Young Persons Act 1933', 'com.synapps.moj.dfs.handler.DARTSEventSetReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (192, '21201', NULL, 'Restrictions lifted', 'com.synapps.moj.dfs.handler.DARTSEventClearReportingRestrictionHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (193, '21300', NULL, 'Freetext', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (194, '21400', '12414', 'Defendant disqualified from working with children for life (Defendant under 18)', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (195, '21400', '12415', 'Defendant disqualified from working with children for life (Defendant over 18)', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (196, '21500', '13700', 'Defendant ordered to be electronically monitored', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (197, '21500', '13701', 'Electronic monitoring requirement amended', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (198, '21500', '13702', 'Electronic monitoring/tag to be removed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (199, '21500', '13703', 'Defendant subject to a electronically monitored curfew', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (200, '21500', '13704', 'Terms of electronically monitored curfew amended', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (201, '21500', '13705', 'Requirement for an electronically monitored curfew removed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (202, '21600', '13600', 'Sex Offenders Register - victim under 18 years of age - for an indefinite period', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (203, '21600', '13601', 'Sex Offenders Register - victim under 18 years of age - for 10 years', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (204, '21600', '13602', 'Sex Offenders Register - victim under 18 years of age - for 3-7 years', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (205, '21600', '13603', 'Sex Offenders Register - victim under 18 years of age - period to be specified later', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (206, '21600', '13604', 'Sex Offenders Register - victim under 18 years of age - for another period', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (207, '21600', '13605', 'Sex Offenders Register - victim over 18 years of age - for an indefinite period', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (208, '21600', '13606', 'Sex Offenders Register - victim over 18 years of age - for 10 years', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (209, '21600', '13607', 'Sex Offenders Register - victim over 18 years of age - for 3-7 years', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (210, '21600', '13608', 'Sex Offenders Register - victim over 18 years of age - for another period', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (211, '21600', '13609', 'Sex Offenders Register - victim over 18 years of age - period to be specified later', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (212, '21800', '12310', 'Disqualification from driving removed (3076)', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (213, '30100', NULL, 'Short adjournment', 'com.synapps.moj.dfs.handler.DARTSEventDARStopHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (214, '30300', NULL, 'Case closed', 'com.synapps.moj.dfs.handler.DARTSEventDARStopHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (215, '30500', NULL, 'Hearing ended', 'com.synapps.moj.dfs.handler.DARTSEventStopAndCloseHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (216, '30600', NULL, 'Hearing ended', 'com.synapps.moj.dfs.handler.DARTSEventStopAndCloseHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (217, '30601', '11113', 'Delete end hearing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (218, '40203', NULL, 'Join indictments', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (219, '40410', NULL, 'Maintain charges', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (220, '40601', NULL, '7/14 day orders', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (221, '40706', '10305', 'Remanded in Custody', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (222, '40706', '10308', 'Bail as before', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (223, '40706', '10309', 'Bail varied', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (224, '40711', NULL, 'Time estimate supplied', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (225, '40720', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (226, '40721', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (227, '40722', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (228, '40725', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (229, '40726', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (230, '40727', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (231, '40730', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (232, '40730', '10808', 'Case Level Criminal Appeal Result', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (233, '40731', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (234, '40731', '10808', 'Offence Level Criminal Appeal Result', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (235, '40732', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (236, '40732', '10808', 'Offence Level Criminal Appeal Result with alt offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (237, '40733', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (238, '40733', '10808', 'Case Level Misc Appeal Result', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (239, '40735', '10808', 'Delete Offence Level Appeal Result', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (240, '40735', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (241, '40736', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (242, '40737', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (243, '40738', NULL, 'Verdict', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (244, '40750', '12309', 'Driving disqualification suspended pending appeal subsequent to imposition (3075)', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (245, '40750', NULL, 'Sentencing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (246, '40750', '11504', 'Life Imprisonment', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (247, '40750', '11505', 'Life Imprisonment (with minimum period)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (248, '40750', '11506', 'Custody for Life', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (249, '40750', '11507', 'Mandatory Life Sentence for Second Serious Offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (250, '40750', '11508', 'Mandatory Life Sentence for Second Serious Offence (Young Offender)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (251, '40750', '11509', 'Detained During Her Majestys Pleasure', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (252, '40750', '11521', 'INIMP: Indeterminate Sentence of Imprisonment for Public Protection', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (253, '40750', '11522', 'INDET: Indeterminate Sentence of Detention for Public Protection', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (254, '40750', '11523', 'Mandatory Life Sentence for Second Listed Offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (255, '40750', '11524', 'Mandatory Life Sentence for Second Listed Offence (Young Offender)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (256, '40750', '12400', 'Disqualification Order (from working with children) - ADULTS', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (257, '40750', '12401', 'Disqualification Order (from working with children) - JUVENILES', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (258, '40750', '13505', 'S226b Extended Discretional for under 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (259, '40750', '13506', 'S226b Extended Automatic for under 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (260, '40750', '13503', 'S226a Extended Discretional for over 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (261, '40750', '13504', 'S226a Extended Automatic for over 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (262, '40750', '11529', 'Detention for Life under s226 (u18)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (263, '40750', '11525', 'Imprisonment - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (264, '40750', '11526', 'Imprisonment - Minimum Imposed after 3 strikes (Young Offender) - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (265, '40750', '11527', 'Imprisonment - Minimum Imposed after 3 strikes - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (266, '40750', '11528', 'Detention in Y.O.I. - Extended under s235A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (267, '40750', '11533', 'Imprisonment for life (adult) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (268, '40750', '11534', 'Detention for life (youth) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (269, '40750', '13507', '(Extended Discretional 18 to 20)   Section 266', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (270, '40750', '13508', '(Extended Discretional over 21)', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (271, '40751', '11528', 'Detention in Y.O.I. - Extended under s235A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (272, '40751', NULL, 'Sentencing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (368, '407131', NULL, 'Case to be listed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (273, '40751', '11504', 'Life Imprisonment', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (274, '40751', '11505', 'Life Imprisonment (with minimum period)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (275, '40751', '11506', 'Custody for Life', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (276, '40751', '11507', 'Mandatory Life Sentence for Second Serious Offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (277, '40751', '11508', 'Mandatory Life Sentence for Second Serious Offence (Young Offender)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (278, '40751', '11509', 'Detained During Her Majestys Pleasure', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (279, '40751', '11521', 'INIMP: Indeterminate Sentence of Imprisonment for Public Protection', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (280, '40751', '11522', 'INDET: Indeterminate Sentence of Detention for Public Protection', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (281, '40751', '11523', 'Mandatory Life Sentence for Second Listed Offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (282, '40751', '11524', 'Mandatory Life Sentence for Second Listed Offence (Young Offender)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (283, '40751', '12400', 'Disqualification Order (from working with children) - ADULTS', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (284, '40751', '12401', 'Disqualification Order (from working with children) - JUVENILES', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (285, '40751', '13505', 'S226b Extended Discretional for under 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (286, '40751', '13506', 'S226b Extended Automatic for under 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (287, '40751', '13503', 'S226a Extended Discretional for over 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (288, '40751', '13504', 'S226a Extended Automatic for over 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (289, '40751', '11529', 'Detention for Life under s226 (u18)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (290, '40751', '11525', 'Imprisonment - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (291, '40751', '11526', 'Imprisonment - Minimum Imposed after 3 strikes (Young Offender) - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (292, '40751', '11527', 'Imprisonment - Minimum Imposed after 3 strikes - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (293, '40751', '11533', 'Imprisonment for life (adult) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (294, '40751', '11534', 'Detention for life (youth) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (295, '40751', '13507', '(Extended Discretional 18 to 20)   Section 266', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (296, '40751', '13508', '(Extended Discretional over 21)', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (297, '40752', '11528', 'Detention in Y.O.I. - Extended under s235A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (298, '40752', NULL, 'Sentencing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (299, '40752', '11504', 'Life Imprisonment', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (300, '40752', '11505', 'Life Imprisonment (with minimum period)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (301, '40752', '11506', 'Custody for Life', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (302, '40752', '11507', 'Mandatory Life Sentence for Second Serious Offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (303, '40752', '11508', 'Mandatory Life Sentence for Second Serious Offence (Young Offender)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (304, '40752', '11509', 'Detained During Her Majestys Pleasure', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (305, '40752', '11521', 'INIMP: Indeterminate Sentence of Imprisonment for Public Protection', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (306, '40752', '11522', 'INDET: Indeterminate Sentence of Detention for Public Protection', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (307, '40752', '11523', 'Mandatory Life Sentence for Second Listed Offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (308, '40752', '11524', 'Mandatory Life Sentence for Second Listed Offence (Young Offender)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (309, '40752', '12400', 'Disqualification Order (from working with children) - ADULTS', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (310, '40752', '12401', 'Disqualification Order (from working with children) - JUVENILES', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (311, '40752', '13505', 'S226b Extended Discretional for under 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (312, '40752', '13506', 'S226b Extended Automatic for under 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (313, '40752', '13503', 'S226a Extended Discretional for over 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (314, '40752', '13504', 'S226a Extended Automatic for over 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (315, '40752', '11529', 'Detention for Life under s226 (u18)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (316, '40752', '11525', 'Imprisonment - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (369, '407132', NULL, 'Case to be listed', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (317, '40752', '11526', 'Imprisonment - Minimum Imposed after 3 strikes (Young Offender) - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (318, '40752', '11527', 'Imprisonment - Minimum Imposed after 3 strikes - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (319, '40752', '11533', 'Imprisonment for life (adult) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (320, '40752', '11534', 'Detention for life (youth) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (321, '40752', '13507', '(Extended Discretional 18 to 20)   Section 266', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (322, '40752', '13508', '(Extended Discretional over 21)', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (323, '40753', '11528', 'Detention in Y.O.I. - Extended under s235A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (324, '40753', NULL, 'Sentencing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (325, '40753', '11504', 'Life Imprisonment', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (326, '40753', '11505', 'Life Imprisonment (with minimum period)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (327, '40753', '11506', 'Custody for Life', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (328, '40753', '11507', 'Mandatory Life Sentence for Second Serious Offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (329, '40753', '11508', 'Mandatory Life Sentence for Second Serious Offence (Young Offender)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (330, '40753', '11509', 'Detained During Her Majestys Pleasure', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (331, '40753', '11521', 'INIMP: Indeterminate Sentence of Imprisonment for Public Protection', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (332, '40753', '11522', 'INDET: Indeterminate Sentence of Detention for Public Protection', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (333, '40753', '11523', 'Mandatory Life Sentence for Second Listed Offence', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (334, '40753', '11524', 'Mandatory Life Sentence for Second Listed Offence (Young Offender)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (335, '40753', '12400', 'Disqualification Order (from working with children) - ADULTS', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (336, '40753', '12401', 'Disqualification Order (from working with children) - JUVENILES', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (337, '40753', '13505', 'S226b Extended Discretional for under 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (338, '40753', '13506', 'S226b Extended Automatic for under 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (339, '40753', '13503', 'S226a Extended Discretional for over 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (340, '40753', '13504', 'S226a Extended Automatic for over 18', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (341, '40753', '11529', 'Detention for Life under s226 (u18)', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (342, '40753', '11525', 'Imprisonment - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (343, '40753', '11526', 'Imprisonment - Minimum Imposed after 3 strikes (Young Offender) - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (344, '40753', '11527', 'Imprisonment - Minimum Imposed after 3 strikes - Extended under s236A CJA2003', 'com.synapps.moj.dfs.handler.eventtransrequest.SenencingRemarksAndRetentionPolicyHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (345, '40753', '11533', 'Imprisonment for life (adult) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (346, '40753', '11534', 'Detention for life (youth) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (347, '40753', '13507', '(Extended Discretional 18 to 20)   Section 266', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (348, '40753', '13508', '(Extended Discretional over 21)', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (349, '40754', NULL, 'Sentencing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (350, '40754', '11533', 'Imprisonment for life (adult) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (351, '40754', '11534', 'Detention for life (youth) for manslaughter of an emergency worker', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (352, '40754', '13507', '(Extended Discretional 18 to 20)   Section 266', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (353, '40754', '13508', '(Extended Discretional over 21)', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (354, '40755', NULL, 'Sentencing', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (355, '40756', NULL, 'Guilty', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (356, '40790', NULL, 'Results', 'com.synapps.moj.dfs.handler.DARTSEventNullHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (357, '40791', NULL, 'Recommended for Deportation', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (358, '60101', NULL, 'Plea', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (359, '60102', NULL, 'Plea', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (360, '60103', NULL, 'Plea', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (361, '60104', NULL, 'Plea', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (362, '60106', '11317', 'Admitted ( Bail Act Offence)', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (363, '60106', '11318', 'Not Admitted ( Bail Act Offence)', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (364, '302001', NULL, 'Long adjournment', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (365, '302002', NULL, 'Adjourned for pre-sentence report', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (366, '302003', NULL, 'Case reserved', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (367, '302004', NULL, 'Case not reserved', 'com.synapps.moj.dfs.handler.DARTSEventHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (370, 'CPPDL', 'CPPDL', 'CPP Daily List', 'com.synapps.moj.dfs.handler.DARTSDailyListFromCPPHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (371, 'DETTO', '11531', 'Special Sentence of Detention for Terrorist Offenders of Particular Concern', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (372, 'DL', NULL, 'Daily List', 'com.synapps.moj.dfs.handler.DARTSDailyListHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (373, 'NEWCASE', NULL, 'New Case', 'com.synapps.moj.dfs.handler.DARTSXHIBITNewCaseHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (374, 'STS', '11530', 'Serious Terrorism Sentence', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (375, 'STS1821', '11532', 'Serious Terrorism Sentence 18 to 21', 'com.synapps.moj.dfs.handler.eventtransrequest.SentencingRemarksHandler');
INSERT INTO event_type (evt_id, evt_type, sub_type, event_name, handler) VALUES (376, 'UPDCASE', NULL, 'Update Case', 'com.synapps.moj.dfs.handler.DARTSXHIBITUpdateCaseHandler');

ALTER SEQUENCE evt_seq RESTART WITH 377;

