# Attention: if you are changing values in here, please ensure you also update any corresponding files in the charts-dev-overrides directory
apiVersion: v2
appVersion: "1.0"
description: A Helm chart for darts-api App
name: darts-api
home: https://github.com/hmcts/darts-api
version: 0.0.113
maintainers:
  - name: HMCTS darts team
dependencies:
  - name: java
    version: 6.0.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
  - name: function
    version: 2.6.2
    repository: 'oci://hmctsprod.azurecr.io/helm'
  - name: postgresql
    version: 1.1.1
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: postgresql.enabled
  - name: darts-portal
    version: ~0.0.31
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: darts-portal.enabled
  - name: darts-gateway
    version: ~0.0.41
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: darts-gateway.enabled

