//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for AssociatedCaseStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="AssociatedCaseStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="AssociatedCase" type="{http://www.courtservice.gov.uk/schemas/courtservice}CaseNumberType" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedCaseStructure", propOrder = {
    "associatedCase"
})
public class AssociatedCaseStructure {

    @XmlElement(name = "AssociatedCase", required = true)
    protected List<String> associatedCase;

    /**
     * Gets the value of the associatedCase property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the associatedCase property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociatedCase().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     * @return
     *     The value of the associatedCase property.
     */
    public List<String> getAssociatedCase() {
        if (associatedCase == null) {
            associatedCase = new ArrayList<>();
        }
        return this.associatedCase;
    }

}
