//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BailStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="BailStatusType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="On bail"/>
 *     <enumeration value="On remand"/>
 *     <enumeration value="In care"/>
 *     <enumeration value="In custody"/>
 *     <enumeration value="Not applicable"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "BailStatusType")
@XmlEnum
public enum BailStatusType {

    @XmlEnumValue("On bail")
    ON_BAIL("On bail"),
    @XmlEnumValue("On remand")
    ON_REMAND("On remand"),
    @XmlEnumValue("In care")
    IN_CARE("In care"),
    @XmlEnumValue("In custody")
    IN_CUSTODY("In custody"),
    @XmlEnumValue("Not applicable")
    NOT_APPLICABLE("Not applicable");
    private final String value;

    BailStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BailStatusType fromValue(String v) {
        for (BailStatusType c: BailStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
