//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BailChangesStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="BailChangesStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ChangeType" type="{http://www.courtservice.gov.uk/schemas/courtservice}BailChangeType" minOccurs="0"/>
 *         <element name="AmendedVariedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BailChangesStructure", propOrder = {
    "changeType",
    "amendedVariedDate"
})
public class BailChangesStructure {

    @XmlElement(name = "ChangeType")
    @XmlSchemaType(name = "string")
    protected BailChangeType changeType;
    @XmlElement(name = "AmendedVariedDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar amendedVariedDate;

    /**
     * Gets the value of the changeType property.
     *
     * @return
     *     possible object is
     *     {@link BailChangeType }
     *
     */
    public BailChangeType getChangeType() {
        return changeType;
    }

    /**
     * Sets the value of the changeType property.
     *
     * @param value
     *     allowed object is
     *     {@link BailChangeType }
     *
     */
    public void setChangeType(BailChangeType value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the amendedVariedDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getAmendedVariedDate() {
        return amendedVariedDate;
    }

    /**
     * Sets the value of the amendedVariedDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setAmendedVariedDate(XMLGregorianCalendar value) {
        this.amendedVariedDate = value;
    }

}
