//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;


/**
 * <p>Java class for BreachStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="BreachStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="OriginatingCourt">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://www.courtservice.gov.uk/schemas/courtservice}OriginatingCourtStructure">
 *                 <sequence>
 *                   <element name="OriginalOrderType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="BreachCourt">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://www.courtservice.gov.uk/schemas/courtservice}OriginatingCourtStructure">
 *                 <sequence>
 *                   <element name="SentToCrownCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BreachStructure", propOrder = {
    "originatingCourt",
    "breachCourt"
})
public class BreachStructure {

    @XmlElement(name = "OriginatingCourt", required = true)
    protected OriginatingCourt originatingCourt;
    @XmlElement(name = "BreachCourt", required = true)
    protected BreachCourt breachCourt;

    /**
     * Gets the value of the originatingCourt property.
     *
     * @return
     *     possible object is
     *     {@link OriginatingCourt }
     *
     */
    public OriginatingCourt getOriginatingCourt() {
        return originatingCourt;
    }

    /**
     * Sets the value of the originatingCourt property.
     *
     * @param value
     *     allowed object is
     *     {@link OriginatingCourt }
     *
     */
    public void setOriginatingCourt(OriginatingCourt value) {
        this.originatingCourt = value;
    }

    /**
     * Gets the value of the breachCourt property.
     *
     * @return
     *     possible object is
     *     {@link BreachCourt }
     *
     */
    public BreachCourt getBreachCourt() {
        return breachCourt;
    }

    /**
     * Sets the value of the breachCourt property.
     *
     * @param value
     *     allowed object is
     *     {@link BreachCourt }
     *
     */
    public void setBreachCourt(BreachCourt value) {
        this.breachCourt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://www.courtservice.gov.uk/schemas/courtservice}OriginatingCourtStructure">
     *       <sequence>
     *         <element name="SentToCrownCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sentToCrownCourt"
    })
    public static class BreachCourt
        extends OriginatingCourtStructure
    {

        @XmlElement(name = "SentToCrownCourt", required = true)
        @XmlSchemaType(name = "string")
        protected YesNoType sentToCrownCourt;

        /**
         * Gets the value of the sentToCrownCourt property.
         *
         * @return
         *     possible object is
         *     {@link YesNoType }
         *
         */
        public YesNoType getSentToCrownCourt() {
            return sentToCrownCourt;
        }

        /**
         * Sets the value of the sentToCrownCourt property.
         *
         * @param value
         *     allowed object is
         *     {@link YesNoType }
         *
         */
        public void setSentToCrownCourt(YesNoType value) {
            this.sentToCrownCourt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://www.courtservice.gov.uk/schemas/courtservice}OriginatingCourtStructure">
     *       <sequence>
     *         <element name="OriginalOrderType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originalOrderType"
    })
    public static class OriginatingCourt
        extends OriginatingCourtStructure
    {

        @XmlElement(name = "OriginalOrderType", required = true)
        protected String originalOrderType;

        /**
         * Gets the value of the originalOrderType property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOriginalOrderType() {
            return originalOrderType;
        }

        /**
         * Sets the value of the originalOrderType property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOriginalOrderType(String value) {
            this.originalOrderType = value;
        }

    }

}
