//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CasesStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="CasesStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Case" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="CaseNumber" type="{http://www.courtservice.gov.uk/schemas/courtservice}CaseNumberType"/>
 *                   <element name="CaseArrivedFrom" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <choice>
 *                             <element name="OriginatingCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure"/>
 *                             <element name="Section53" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
 *                           </choice>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="Hearing" type="{http://www.courtservice.gov.uk/schemas/courtservice}HearingTypeStructure" minOccurs="0"/>
 *                   <element name="Defendants" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="Defendant" type="{http://www.courtservice.gov.uk/schemas/courtservice}DefendantStructure"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="Prosecution" type="{http://www.courtservice.gov.uk/schemas/courtservice}ProsecutionStructure" minOccurs="0"/>
 *                   <element name="AppealCaseDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   <element name="MethodOfInstigation" type="{http://www.courtservice.gov.uk/schemas/courtservice}MethodOfInstigationType" minOccurs="0"/>
 *                   <element name="DateOfInstigation" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   <element name="CaseClassNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CasesStructure", propOrder = {
    "_case"
})
public class CasesStructure {

    @XmlElement(name = "Case", required = true)
    protected List<Case> _case;

    /**
     * Gets the value of the case property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the case property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCase().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Case }
     *
     *
     * @return
     *     The value of the case property.
     */
    public List<Case> getCase() {
        if (_case == null) {
            _case = new ArrayList<>();
        }
        return this._case;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="CaseNumber" type="{http://www.courtservice.gov.uk/schemas/courtservice}CaseNumberType"/>
     *         <element name="CaseArrivedFrom" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <choice>
     *                   <element name="OriginatingCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure"/>
     *                   <element name="Section53" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
     *                 </choice>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="Hearing" type="{http://www.courtservice.gov.uk/schemas/courtservice}HearingTypeStructure" minOccurs="0"/>
     *         <element name="Defendants" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="Defendant" type="{http://www.courtservice.gov.uk/schemas/courtservice}DefendantStructure"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="Prosecution" type="{http://www.courtservice.gov.uk/schemas/courtservice}ProsecutionStructure" minOccurs="0"/>
     *         <element name="AppealCaseDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         <element name="MethodOfInstigation" type="{http://www.courtservice.gov.uk/schemas/courtservice}MethodOfInstigationType" minOccurs="0"/>
     *         <element name="DateOfInstigation" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         <element name="CaseClassNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caseNumber",
        "caseArrivedFrom",
        "hearing",
        "defendants",
        "prosecution",
        "appealCaseDescription",
        "methodOfInstigation",
        "dateOfInstigation",
        "caseClassNumber"
    })
    public static class Case {

        @XmlElement(name = "CaseNumber", required = true)
        protected String caseNumber;
        @XmlElement(name = "CaseArrivedFrom")
        protected CaseArrivedFrom caseArrivedFrom;
        @XmlElement(name = "Hearing")
        protected HearingTypeStructure hearing;
        @XmlElement(name = "Defendants", required = true)
        protected List<Defendants> defendants;
        @XmlElement(name = "Prosecution")
        protected ProsecutionStructure prosecution;
        @XmlElement(name = "AppealCaseDescription")
        protected String appealCaseDescription;
        @XmlElement(name = "MethodOfInstigation")
        @XmlSchemaType(name = "string")
        protected MethodOfInstigationType methodOfInstigation;
        @XmlElement(name = "DateOfInstigation")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateOfInstigation;
        @XmlElement(name = "CaseClassNumber")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger caseClassNumber;

        /**
         * Gets the value of the caseNumber property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCaseNumber() {
            return caseNumber;
        }

        /**
         * Sets the value of the caseNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCaseNumber(String value) {
            this.caseNumber = value;
        }

        /**
         * Gets the value of the caseArrivedFrom property.
         *
         * @return
         *     possible object is
         *     {@link CaseArrivedFrom }
         *
         */
        public CaseArrivedFrom getCaseArrivedFrom() {
            return caseArrivedFrom;
        }

        /**
         * Sets the value of the caseArrivedFrom property.
         *
         * @param value
         *     allowed object is
         *     {@link CaseArrivedFrom }
         *
         */
        public void setCaseArrivedFrom(CaseArrivedFrom value) {
            this.caseArrivedFrom = value;
        }

        /**
         * Gets the value of the hearing property.
         *
         * @return
         *     possible object is
         *     {@link HearingTypeStructure }
         *
         */
        public HearingTypeStructure getHearing() {
            return hearing;
        }

        /**
         * Sets the value of the hearing property.
         *
         * @param value
         *     allowed object is
         *     {@link HearingTypeStructure }
         *
         */
        public void setHearing(HearingTypeStructure value) {
            this.hearing = value;
        }

        /**
         * Gets the value of the defendants property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the defendants property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDefendants().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Defendants }
         *
         *
         * @return
         *     The value of the defendants property.
         */
        public List<Defendants> getDefendants() {
            if (defendants == null) {
                defendants = new ArrayList<>();
            }
            return this.defendants;
        }

        /**
         * Gets the value of the prosecution property.
         *
         * @return
         *     possible object is
         *     {@link ProsecutionStructure }
         *
         */
        public ProsecutionStructure getProsecution() {
            return prosecution;
        }

        /**
         * Sets the value of the prosecution property.
         *
         * @param value
         *     allowed object is
         *     {@link ProsecutionStructure }
         *
         */
        public void setProsecution(ProsecutionStructure value) {
            this.prosecution = value;
        }

        /**
         * Gets the value of the appealCaseDescription property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAppealCaseDescription() {
            return appealCaseDescription;
        }

        /**
         * Sets the value of the appealCaseDescription property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAppealCaseDescription(String value) {
            this.appealCaseDescription = value;
        }

        /**
         * Gets the value of the methodOfInstigation property.
         *
         * @return
         *     possible object is
         *     {@link MethodOfInstigationType }
         *
         */
        public MethodOfInstigationType getMethodOfInstigation() {
            return methodOfInstigation;
        }

        /**
         * Sets the value of the methodOfInstigation property.
         *
         * @param value
         *     allowed object is
         *     {@link MethodOfInstigationType }
         *
         */
        public void setMethodOfInstigation(MethodOfInstigationType value) {
            this.methodOfInstigation = value;
        }

        /**
         * Gets the value of the dateOfInstigation property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getDateOfInstigation() {
            return dateOfInstigation;
        }

        /**
         * Sets the value of the dateOfInstigation property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setDateOfInstigation(XMLGregorianCalendar value) {
            this.dateOfInstigation = value;
        }

        /**
         * Gets the value of the caseClassNumber property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getCaseClassNumber() {
            return caseClassNumber;
        }

        /**
         * Sets the value of the caseClassNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setCaseClassNumber(BigInteger value) {
            this.caseClassNumber = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <choice>
         *         <element name="OriginatingCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure"/>
         *         <element name="Section53" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
         *       </choice>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "originatingCourt",
            "section53"
        })
        public static class CaseArrivedFrom {

            @XmlElement(name = "OriginatingCourt")
            protected CourtHouseStructure originatingCourt;
            @XmlElement(name = "Section53", defaultValue = "yes")
            @XmlSchemaType(name = "string")
            protected YesNoType section53;

            /**
             * Gets the value of the originatingCourt property.
             *
             * @return
             *     possible object is
             *     {@link CourtHouseStructure }
             *
             */
            public CourtHouseStructure getOriginatingCourt() {
                return originatingCourt;
            }

            /**
             * Sets the value of the originatingCourt property.
             *
             * @param value
             *     allowed object is
             *     {@link CourtHouseStructure }
             *
             */
            public void setOriginatingCourt(CourtHouseStructure value) {
                this.originatingCourt = value;
            }

            /**
             * Gets the value of the section53 property.
             *
             * @return
             *     possible object is
             *     {@link YesNoType }
             *
             */
            public YesNoType getSection53() {
                return section53;
            }

            /**
             * Sets the value of the section53 property.
             *
             * @param value
             *     allowed object is
             *     {@link YesNoType }
             *
             */
            public void setSection53(YesNoType value) {
                this.section53 = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="Defendant" type="{http://www.courtservice.gov.uk/schemas/courtservice}DefendantStructure"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "defendant"
        })
        public static class Defendants {

            @XmlElement(name = "Defendant", required = true)
            protected DefendantStructure defendant;

            /**
             * Gets the value of the defendant property.
             *
             * @return
             *     possible object is
             *     {@link DefendantStructure }
             *
             */
            public DefendantStructure getDefendant() {
                return defendant;
            }

            /**
             * Sets the value of the defendant property.
             *
             * @param value
             *     allowed object is
             *     {@link DefendantStructure }
             *
             */
            public void setDefendant(DefendantStructure value) {
                this.defendant = value;
            }

        }

    }

}
