//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommunityOrderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="CommunityOrderType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="activity"/>
 *     <enumeration value="alcohol treatment"/>
 *     <enumeration value="attendance centre"/>
 *     <enumeration value="curfew"/>
 *     <enumeration value="drug rehabilitation"/>
 *     <enumeration value="exclusion"/>
 *     <enumeration value="mental health treatment"/>
 *     <enumeration value="programme"/>
 *     <enumeration value="prohibited activity"/>
 *     <enumeration value="residence"/>
 *     <enumeration value="supervision"/>
 *     <enumeration value="unpaid work"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CommunityOrderType")
@XmlEnum
public enum CommunityOrderType {

    @XmlEnumValue("activity")
    ACTIVITY("activity"),
    @XmlEnumValue("alcohol treatment")
    ALCOHOL_TREATMENT("alcohol treatment"),
    @XmlEnumValue("attendance centre")
    ATTENDANCE_CENTRE("attendance centre"),
    @XmlEnumValue("curfew")
    CURFEW("curfew"),
    @XmlEnumValue("drug rehabilitation")
    DRUG_REHABILITATION("drug rehabilitation"),
    @XmlEnumValue("exclusion")
    EXCLUSION("exclusion"),
    @XmlEnumValue("mental health treatment")
    MENTAL_HEALTH_TREATMENT("mental health treatment"),
    @XmlEnumValue("programme")
    PROGRAMME("programme"),
    @XmlEnumValue("prohibited activity")
    PROHIBITED_ACTIVITY("prohibited activity"),
    @XmlEnumValue("residence")
    RESIDENCE("residence"),
    @XmlEnumValue("supervision")
    SUPERVISION("supervision"),
    @XmlEnumValue("unpaid work")
    UNPAID_WORK("unpaid work");
    private final String value;

    CommunityOrderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommunityOrderType fromValue(String v) {
        for (CommunityOrderType c: CommunityOrderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
