//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for CommunityOrderStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="CommunityOrderStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DocumentID" type="{http://www.courtservice.gov.uk/schemas/courtservice}DocumentIDstructure"/>
 *         <element name="OrderHeader" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtOrderHeaderStructure"/>
 *         <element name="CommittingCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}OriginatingCourtStructure" minOccurs="0"/>
 *         <element name="Breach" type="{http://www.courtservice.gov.uk/schemas/courtservice}BreachStructure" minOccurs="0"/>
 *         <element name="OriginalOrderRevoked" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="BreachCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
 *                   <element name="CurrentCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="FailedToComply" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType" minOccurs="0"/>
 *         <element name="AfterHearingFrom" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType" minOccurs="0"/>
 *         <element name="PettySessionalArea" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure" minOccurs="0"/>
 *         <element name="CommunityPunishment" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Hours" minOccurs="0">
 *                     <complexType>
 *                       <simpleContent>
 *                         <extension base="<http://www.w3.org/2001/XMLSchema>int">
 *                           <attribute name="TermType" type="{http://www.courtservice.gov.uk/schemas/courtservice}TermTypeType" />
 *                         </extension>
 *                       </simpleContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="Period" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="RehabilitationPeriod" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         <element name="Conditions" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Condition" type="{http://www.courtservice.gov.uk/schemas/courtservice}ConditionStructure" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="AssociatedCases" type="{http://www.courtservice.gov.uk/schemas/courtservice}AssociatedCaseStructure" minOccurs="0"/>
 *         <element name="AdditionalNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommunityOrderStructure", propOrder = {
    "documentID",
    "orderHeader",
    "committingCourt",
    "breach",
    "originalOrderRevoked",
    "failedToComply",
    "afterHearingFrom",
    "pettySessionalArea",
    "communityPunishment",
    "rehabilitationPeriod",
    "conditions",
    "associatedCases",
    "additionalNotes"
})
public class CommunityOrderStructure {

    @XmlElement(name = "DocumentID", required = true)
    protected DocumentIDstructure documentID;
    @XmlElement(name = "OrderHeader", required = true)
    protected CourtOrderHeaderStructure orderHeader;
    @XmlElement(name = "CommittingCourt")
    protected OriginatingCourtStructure committingCourt;
    @XmlElement(name = "Breach")
    protected BreachStructure breach;
    @XmlElement(name = "OriginalOrderRevoked")
    protected OriginalOrderRevoked originalOrderRevoked;
    @XmlElement(name = "FailedToComply")
    @XmlSchemaType(name = "string")
    protected YesNoType failedToComply;
    @XmlElement(name = "AfterHearingFrom")
    @XmlSchemaType(name = "string")
    protected YesNoType afterHearingFrom;
    @XmlElement(name = "PettySessionalArea")
    protected CourtHouseStructure pettySessionalArea;
    @XmlElement(name = "CommunityPunishment")
    protected CommunityPunishment communityPunishment;
    @XmlElement(name = "RehabilitationPeriod")
    protected Duration rehabilitationPeriod;
    @XmlElement(name = "Conditions")
    protected Conditions conditions;
    @XmlElement(name = "AssociatedCases")
    protected AssociatedCaseStructure associatedCases;
    @XmlElement(name = "AdditionalNotes")
    protected String additionalNotes;

    /**
     * Gets the value of the documentID property.
     *
     * @return
     *     possible object is
     *     {@link DocumentIDstructure }
     *
     */
    public DocumentIDstructure getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     *
     * @param value
     *     allowed object is
     *     {@link DocumentIDstructure }
     *
     */
    public void setDocumentID(DocumentIDstructure value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the orderHeader property.
     *
     * @return
     *     possible object is
     *     {@link CourtOrderHeaderStructure }
     *
     */
    public CourtOrderHeaderStructure getOrderHeader() {
        return orderHeader;
    }

    /**
     * Sets the value of the orderHeader property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtOrderHeaderStructure }
     *
     */
    public void setOrderHeader(CourtOrderHeaderStructure value) {
        this.orderHeader = value;
    }

    /**
     * Gets the value of the committingCourt property.
     *
     * @return
     *     possible object is
     *     {@link OriginatingCourtStructure }
     *
     */
    public OriginatingCourtStructure getCommittingCourt() {
        return committingCourt;
    }

    /**
     * Sets the value of the committingCourt property.
     *
     * @param value
     *     allowed object is
     *     {@link OriginatingCourtStructure }
     *
     */
    public void setCommittingCourt(OriginatingCourtStructure value) {
        this.committingCourt = value;
    }

    /**
     * Gets the value of the breach property.
     *
     * @return
     *     possible object is
     *     {@link BreachStructure }
     *
     */
    public BreachStructure getBreach() {
        return breach;
    }

    /**
     * Sets the value of the breach property.
     *
     * @param value
     *     allowed object is
     *     {@link BreachStructure }
     *
     */
    public void setBreach(BreachStructure value) {
        this.breach = value;
    }

    /**
     * Gets the value of the originalOrderRevoked property.
     *
     * @return
     *     possible object is
     *     {@link OriginalOrderRevoked }
     *
     */
    public OriginalOrderRevoked getOriginalOrderRevoked() {
        return originalOrderRevoked;
    }

    /**
     * Sets the value of the originalOrderRevoked property.
     *
     * @param value
     *     allowed object is
     *     {@link OriginalOrderRevoked }
     *
     */
    public void setOriginalOrderRevoked(OriginalOrderRevoked value) {
        this.originalOrderRevoked = value;
    }

    /**
     * Gets the value of the failedToComply property.
     *
     * @return
     *     possible object is
     *     {@link YesNoType }
     *
     */
    public YesNoType getFailedToComply() {
        return failedToComply;
    }

    /**
     * Sets the value of the failedToComply property.
     *
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *
     */
    public void setFailedToComply(YesNoType value) {
        this.failedToComply = value;
    }

    /**
     * Gets the value of the afterHearingFrom property.
     *
     * @return
     *     possible object is
     *     {@link YesNoType }
     *
     */
    public YesNoType getAfterHearingFrom() {
        return afterHearingFrom;
    }

    /**
     * Sets the value of the afterHearingFrom property.
     *
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *
     */
    public void setAfterHearingFrom(YesNoType value) {
        this.afterHearingFrom = value;
    }

    /**
     * Gets the value of the pettySessionalArea property.
     *
     * @return
     *     possible object is
     *     {@link CourtHouseStructure }
     *
     */
    public CourtHouseStructure getPettySessionalArea() {
        return pettySessionalArea;
    }

    /**
     * Sets the value of the pettySessionalArea property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtHouseStructure }
     *
     */
    public void setPettySessionalArea(CourtHouseStructure value) {
        this.pettySessionalArea = value;
    }

    /**
     * Gets the value of the communityPunishment property.
     *
     * @return
     *     possible object is
     *     {@link CommunityPunishment }
     *
     */
    public CommunityPunishment getCommunityPunishment() {
        return communityPunishment;
    }

    /**
     * Sets the value of the communityPunishment property.
     *
     * @param value
     *     allowed object is
     *     {@link CommunityPunishment }
     *
     */
    public void setCommunityPunishment(CommunityPunishment value) {
        this.communityPunishment = value;
    }

    /**
     * Gets the value of the rehabilitationPeriod property.
     *
     * @return
     *     possible object is
     *     {@link Duration }
     *
     */
    public Duration getRehabilitationPeriod() {
        return rehabilitationPeriod;
    }

    /**
     * Sets the value of the rehabilitationPeriod property.
     *
     * @param value
     *     allowed object is
     *     {@link Duration }
     *
     */
    public void setRehabilitationPeriod(Duration value) {
        this.rehabilitationPeriod = value;
    }

    /**
     * Gets the value of the conditions property.
     *
     * @return
     *     possible object is
     *     {@link Conditions }
     *
     */
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     *
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *
     */
    public void setConditions(Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the associatedCases property.
     *
     * @return
     *     possible object is
     *     {@link AssociatedCaseStructure }
     *
     */
    public AssociatedCaseStructure getAssociatedCases() {
        return associatedCases;
    }

    /**
     * Sets the value of the associatedCases property.
     *
     * @param value
     *     allowed object is
     *     {@link AssociatedCaseStructure }
     *
     */
    public void setAssociatedCases(AssociatedCaseStructure value) {
        this.associatedCases = value;
    }

    /**
     * Gets the value of the additionalNotes property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdditionalNotes() {
        return additionalNotes;
    }

    /**
     * Sets the value of the additionalNotes property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdditionalNotes(String value) {
        this.additionalNotes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Hours" minOccurs="0">
     *           <complexType>
     *             <simpleContent>
     *               <extension base="<http://www.w3.org/2001/XMLSchema>int">
     *                 <attribute name="TermType" type="{http://www.courtservice.gov.uk/schemas/courtservice}TermTypeType" />
     *               </extension>
     *             </simpleContent>
     *           </complexType>
     *         </element>
     *         <element name="Period" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hours",
        "period"
    })
    public static class CommunityPunishment {

        @XmlElement(name = "Hours")
        protected Hours hours;
        @XmlElement(name = "Period")
        protected Duration period;

        /**
         * Gets the value of the hours property.
         *
         * @return
         *     possible object is
         *     {@link Hours }
         *
         */
        public Hours getHours() {
            return hours;
        }

        /**
         * Sets the value of the hours property.
         *
         * @param value
         *     allowed object is
         *     {@link Hours }
         *
         */
        public void setHours(Hours value) {
            this.hours = value;
        }

        /**
         * Gets the value of the period property.
         *
         * @return
         *     possible object is
         *     {@link Duration }
         *
         */
        public Duration getPeriod() {
            return period;
        }

        /**
         * Sets the value of the period property.
         *
         * @param value
         *     allowed object is
         *     {@link Duration }
         *
         */
        public void setPeriod(Duration value) {
            this.period = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>{@code
         * <complexType>
         *   <simpleContent>
         *     <extension base="<http://www.w3.org/2001/XMLSchema>int">
         *       <attribute name="TermType" type="{http://www.courtservice.gov.uk/schemas/courtservice}TermTypeType" />
         *     </extension>
         *   </simpleContent>
         * </complexType>
         * }</pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Hours {

            @XmlValue
            protected int value;
            @XmlAttribute(name = "TermType")
            protected TermTypeType termType;

            /**
             * Gets the value of the value property.
             *
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the termType property.
             *
             * @return
             *     possible object is
             *     {@link TermTypeType }
             *
             */
            public TermTypeType getTermType() {
                return termType;
            }

            /**
             * Sets the value of the termType property.
             *
             * @param value
             *     allowed object is
             *     {@link TermTypeType }
             *
             */
            public void setTermType(TermTypeType value) {
                this.termType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Condition" type="{http://www.courtservice.gov.uk/schemas/courtservice}ConditionStructure" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "condition"
    })
    public static class Conditions {

        @XmlElement(name = "Condition", required = true)
        protected List<ConditionStructure> condition;

        /**
         * Gets the value of the condition property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the condition property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCondition().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConditionStructure }
         *
         *
         * @return
         *     The value of the condition property.
         */
        public List<ConditionStructure> getCondition() {
            if (condition == null) {
                condition = new ArrayList<>();
            }
            return this.condition;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="BreachCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
     *         <element name="CurrentCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "breachCourt",
        "currentCourt"
    })
    public static class OriginalOrderRevoked {

        @XmlElement(name = "BreachCourt", defaultValue = "yes")
        @XmlSchemaType(name = "string")
        protected YesNoType breachCourt;
        @XmlElement(name = "CurrentCourt", defaultValue = "yes")
        @XmlSchemaType(name = "string")
        protected YesNoType currentCourt;

        /**
         * Gets the value of the breachCourt property.
         *
         * @return
         *     possible object is
         *     {@link YesNoType }
         *
         */
        public YesNoType getBreachCourt() {
            return breachCourt;
        }

        /**
         * Sets the value of the breachCourt property.
         *
         * @param value
         *     allowed object is
         *     {@link YesNoType }
         *
         */
        public void setBreachCourt(YesNoType value) {
            this.breachCourt = value;
        }

        /**
         * Gets the value of the currentCourt property.
         *
         * @return
         *     possible object is
         *     {@link YesNoType }
         *
         */
        public YesNoType getCurrentCourt() {
            return currentCourt;
        }

        /**
         * Sets the value of the currentCourt property.
         *
         * @param value
         *     allowed object is
         *     {@link YesNoType }
         *
         */
        public void setCurrentCourt(YesNoType value) {
            this.currentCourt = value;
        }

    }

}
