//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CourtAppearanceStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="CourtAppearanceStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="AppearanceCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure"/>
 *         <element name="AppearanceDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourtAppearanceStructure", propOrder = {
    "appearanceCourt",
    "appearanceDateTime"
})
public class CourtAppearanceStructure {

    @XmlElement(name = "AppearanceCourt", required = true)
    protected CourtHouseStructure appearanceCourt;
    @XmlElement(name = "AppearanceDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar appearanceDateTime;

    /**
     * Gets the value of the appearanceCourt property.
     *
     * @return
     *     possible object is
     *     {@link CourtHouseStructure }
     *
     */
    public CourtHouseStructure getAppearanceCourt() {
        return appearanceCourt;
    }

    /**
     * Sets the value of the appearanceCourt property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtHouseStructure }
     *
     */
    public void setAppearanceCourt(CourtHouseStructure value) {
        this.appearanceCourt = value;
    }

    /**
     * Gets the value of the appearanceDateTime property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getAppearanceDateTime() {
        return appearanceDateTime;
    }

    /**
     * Sets the value of the appearanceDateTime property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setAppearanceDateTime(XMLGregorianCalendar value) {
        this.appearanceDateTime = value;
    }

}
