//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.UKPostalAddressStructure;


/**
 * <p>Java class for CourtHouseStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="CourtHouseStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CourtHouseType" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtType"/>
 *         <element name="CourtHouseCode">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.courtservice.gov.uk/schemas/courtservice>CourtHouseCodeType">
 *                 <attribute name="CourtHouseShortName">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       <pattern value="[A-Z]{3,5}"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="CourtHouseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="CourtHouseAddress" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}UKPostalAddressStructure" minOccurs="0"/>
 *         <element name="CourtHouseDX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="CourtHouseTelephone" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}TelephoneNumberType" minOccurs="0"/>
 *         <element name="CourtHouseFax" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}TelephoneNumberType" minOccurs="0"/>
 *         <element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourtHouseStructure", propOrder = {
    "courtHouseType",
    "courtHouseCode",
    "courtHouseName",
    "courtHouseAddress",
    "courtHouseDX",
    "courtHouseTelephone",
    "courtHouseFax",
    "description"
})
@XmlSeeAlso({
    RecordSheetHeaderStructure.TransferInCourt.class
})
public class CourtHouseStructure {

    @XmlElement(name = "CourtHouseType", required = true)
    @XmlSchemaType(name = "string")
    protected CourtType courtHouseType;
    @XmlElement(name = "CourtHouseCode", required = true)
    protected CourtHouseCode courtHouseCode;
    @XmlElement(name = "CourtHouseName", required = true)
    protected String courtHouseName;
    @XmlElement(name = "CourtHouseAddress")
    protected UKPostalAddressStructure courtHouseAddress;
    @XmlElement(name = "CourtHouseDX")
    protected String courtHouseDX;
    @XmlElement(name = "CourtHouseTelephone")
    protected String courtHouseTelephone;
    @XmlElement(name = "CourtHouseFax")
    protected String courtHouseFax;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the courtHouseType property.
     *
     * @return
     *     possible object is
     *     {@link CourtType }
     *
     */
    public CourtType getCourtHouseType() {
        return courtHouseType;
    }

    /**
     * Sets the value of the courtHouseType property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtType }
     *
     */
    public void setCourtHouseType(CourtType value) {
        this.courtHouseType = value;
    }

    /**
     * Gets the value of the courtHouseCode property.
     *
     * @return
     *     possible object is
     *     {@link CourtHouseCode }
     *
     */
    public CourtHouseCode getCourtHouseCode() {
        return courtHouseCode;
    }

    /**
     * Sets the value of the courtHouseCode property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtHouseCode }
     *
     */
    public void setCourtHouseCode(CourtHouseCode value) {
        this.courtHouseCode = value;
    }

    /**
     * Gets the value of the courtHouseName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourtHouseName() {
        return courtHouseName;
    }

    /**
     * Sets the value of the courtHouseName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourtHouseName(String value) {
        this.courtHouseName = value;
    }

    /**
     * Gets the value of the courtHouseAddress property.
     *
     * @return
     *     possible object is
     *     {@link UKPostalAddressStructure }
     *
     */
    public UKPostalAddressStructure getCourtHouseAddress() {
        return courtHouseAddress;
    }

    /**
     * Sets the value of the courtHouseAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link UKPostalAddressStructure }
     *
     */
    public void setCourtHouseAddress(UKPostalAddressStructure value) {
        this.courtHouseAddress = value;
    }

    /**
     * Gets the value of the courtHouseDX property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourtHouseDX() {
        return courtHouseDX;
    }

    /**
     * Sets the value of the courtHouseDX property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourtHouseDX(String value) {
        this.courtHouseDX = value;
    }

    /**
     * Gets the value of the courtHouseTelephone property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourtHouseTelephone() {
        return courtHouseTelephone;
    }

    /**
     * Sets the value of the courtHouseTelephone property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourtHouseTelephone(String value) {
        this.courtHouseTelephone = value;
    }

    /**
     * Gets the value of the courtHouseFax property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourtHouseFax() {
        return courtHouseFax;
    }

    /**
     * Sets the value of the courtHouseFax property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourtHouseFax(String value) {
        this.courtHouseFax = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.courtservice.gov.uk/schemas/courtservice>CourtHouseCodeType">
     *       <attribute name="CourtHouseShortName">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             <pattern value="[A-Z]{3,5}"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CourtHouseCode {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "CourtHouseShortName")
        protected String courtHouseShortName;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the courtHouseShortName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCourtHouseShortName() {
            return courtHouseShortName;
        }

        /**
         * Sets the value of the courtHouseShortName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCourtHouseShortName(String value) {
            this.courtHouseShortName = value;
        }

    }

}
