//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.CitizenNameStructure;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CourtOrderHeaderStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="CourtOrderHeaderStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="OrderType" type="{http://www.courtservice.gov.uk/schemas/courtservice}OrderTypeType"/>
 *         <element name="CourtHouse" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure"/>
 *         <element name="Judiciary" type="{http://www.courtservice.gov.uk/schemas/courtservice}JudiciaryStructure" minOccurs="0"/>
 *         <element name="CaseNumber" type="{http://www.courtservice.gov.uk/schemas/courtservice}CaseNumberType"/>
 *         <element name="SubjectType" type="{http://www.courtservice.gov.uk/schemas/courtservice}SubjectTypeType" minOccurs="0"/>
 *         <element name="Defendant" type="{http://www.courtservice.gov.uk/schemas/courtservice}DefendantStructure"/>
 *         <element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="SignedBy">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="CourtOfficer" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}CitizenNameStructure"/>
 *                   <element name="Judiciary" type="{http://www.courtservice.gov.uk/schemas/courtservice}JudiciaryStructure"/>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="SignedDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="RevisionDetails" type="{http://www.courtservice.gov.uk/schemas/courtservice}RevisionDetailsStructure" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourtOrderHeaderStructure", propOrder = {
    "orderType",
    "courtHouse",
    "judiciary",
    "caseNumber",
    "subjectType",
    "defendant",
    "orderDate",
    "signedBy",
    "signedDate",
    "revisionDetails"
})
public class CourtOrderHeaderStructure {

    @XmlElement(name = "OrderType", required = true)
    protected String orderType;
    @XmlElement(name = "CourtHouse", required = true)
    protected CourtHouseStructure courtHouse;
    @XmlElement(name = "Judiciary")
    protected JudiciaryStructure judiciary;
    @XmlElement(name = "CaseNumber", required = true)
    protected String caseNumber;
    @XmlElement(name = "SubjectType")
    @XmlSchemaType(name = "string")
    protected SubjectTypeType subjectType;
    @XmlElement(name = "Defendant", required = true)
    protected DefendantStructure defendant;
    @XmlElement(name = "OrderDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar orderDate;
    @XmlElement(name = "SignedBy", required = true)
    protected SignedBy signedBy;
    @XmlElement(name = "SignedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar signedDate;
    @XmlElement(name = "RevisionDetails")
    protected RevisionDetailsStructure revisionDetails;

    /**
     * Gets the value of the orderType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the courtHouse property.
     *
     * @return
     *     possible object is
     *     {@link CourtHouseStructure }
     *
     */
    public CourtHouseStructure getCourtHouse() {
        return courtHouse;
    }

    /**
     * Sets the value of the courtHouse property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtHouseStructure }
     *
     */
    public void setCourtHouse(CourtHouseStructure value) {
        this.courtHouse = value;
    }

    /**
     * Gets the value of the judiciary property.
     *
     * @return
     *     possible object is
     *     {@link JudiciaryStructure }
     *
     */
    public JudiciaryStructure getJudiciary() {
        return judiciary;
    }

    /**
     * Sets the value of the judiciary property.
     *
     * @param value
     *     allowed object is
     *     {@link JudiciaryStructure }
     *
     */
    public void setJudiciary(JudiciaryStructure value) {
        this.judiciary = value;
    }

    /**
     * Gets the value of the caseNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCaseNumber() {
        return caseNumber;
    }

    /**
     * Sets the value of the caseNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCaseNumber(String value) {
        this.caseNumber = value;
    }

    /**
     * Gets the value of the subjectType property.
     *
     * @return
     *     possible object is
     *     {@link SubjectTypeType }
     *
     */
    public SubjectTypeType getSubjectType() {
        return subjectType;
    }

    /**
     * Sets the value of the subjectType property.
     *
     * @param value
     *     allowed object is
     *     {@link SubjectTypeType }
     *
     */
    public void setSubjectType(SubjectTypeType value) {
        this.subjectType = value;
    }

    /**
     * Gets the value of the defendant property.
     *
     * @return
     *     possible object is
     *     {@link DefendantStructure }
     *
     */
    public DefendantStructure getDefendant() {
        return defendant;
    }

    /**
     * Sets the value of the defendant property.
     *
     * @param value
     *     allowed object is
     *     {@link DefendantStructure }
     *
     */
    public void setDefendant(DefendantStructure value) {
        this.defendant = value;
    }

    /**
     * Gets the value of the orderDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setOrderDate(XMLGregorianCalendar value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the signedBy property.
     *
     * @return
     *     possible object is
     *     {@link SignedBy }
     *
     */
    public SignedBy getSignedBy() {
        return signedBy;
    }

    /**
     * Sets the value of the signedBy property.
     *
     * @param value
     *     allowed object is
     *     {@link SignedBy }
     *
     */
    public void setSignedBy(SignedBy value) {
        this.signedBy = value;
    }

    /**
     * Gets the value of the signedDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getSignedDate() {
        return signedDate;
    }

    /**
     * Sets the value of the signedDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setSignedDate(XMLGregorianCalendar value) {
        this.signedDate = value;
    }

    /**
     * Gets the value of the revisionDetails property.
     *
     * @return
     *     possible object is
     *     {@link RevisionDetailsStructure }
     *
     */
    public RevisionDetailsStructure getRevisionDetails() {
        return revisionDetails;
    }

    /**
     * Sets the value of the revisionDetails property.
     *
     * @param value
     *     allowed object is
     *     {@link RevisionDetailsStructure }
     *
     */
    public void setRevisionDetails(RevisionDetailsStructure value) {
        this.revisionDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="CourtOfficer" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}CitizenNameStructure"/>
     *         <element name="Judiciary" type="{http://www.courtservice.gov.uk/schemas/courtservice}JudiciaryStructure"/>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "courtOfficer",
        "judiciary"
    })
    public static class SignedBy {

        @XmlElement(name = "CourtOfficer")
        protected CitizenNameStructure courtOfficer;
        @XmlElement(name = "Judiciary")
        protected JudiciaryStructure judiciary;

        /**
         * Gets the value of the courtOfficer property.
         *
         * @return
         *     possible object is
         *     {@link CitizenNameStructure }
         *
         */
        public CitizenNameStructure getCourtOfficer() {
            return courtOfficer;
        }

        /**
         * Sets the value of the courtOfficer property.
         *
         * @param value
         *     allowed object is
         *     {@link CitizenNameStructure }
         *
         */
        public void setCourtOfficer(CitizenNameStructure value) {
            this.courtOfficer = value;
        }

        /**
         * Gets the value of the judiciary property.
         *
         * @return
         *     possible object is
         *     {@link JudiciaryStructure }
         *
         */
        public JudiciaryStructure getJudiciary() {
            return judiciary;
        }

        /**
         * Sets the value of the judiciary property.
         *
         * @param value
         *     allowed object is
         *     {@link JudiciaryStructure }
         *
         */
        public void setJudiciary(JudiciaryStructure value) {
            this.judiciary = value;
        }

    }

}
