//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

import java.math.BigInteger;


/**
 * <p>Java class for CreditForBailType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="CreditForBailType">
 *   <simpleContent>
 *     <extension base="<http://www.w3.org/2001/XMLSchema>positiveInteger">
 *       <attribute name="Section" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditForBailType", propOrder = {
    "value"
})
public class CreditForBailType {

    @XmlValue
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger value;
    @XmlAttribute(name = "Section")
    protected String section;

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setValue(BigInteger value) {
        this.value = value;
    }

    /**
     * Gets the value of the section property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSection(String value) {
        this.section = value;
    }

}
