//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for CRESTDisposalDataStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="CRESTDisposalDataStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DisposalCode">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                 <attribute name="TemplateVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="DisposalLine" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="DilSeqNo" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   <element name="Data" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRESTDisposalDataStructure", propOrder = {
    "disposalCode",
    "disposalLine"
})
public class CRESTDisposalDataStructure {

    @XmlElement(name = "DisposalCode", required = true)
    protected DisposalCode disposalCode;
    @XmlElement(name = "DisposalLine", required = true)
    protected List<DisposalLine> disposalLine;

    /**
     * Gets the value of the disposalCode property.
     *
     * @return
     *     possible object is
     *     {@link DisposalCode }
     *
     */
    public DisposalCode getDisposalCode() {
        return disposalCode;
    }

    /**
     * Sets the value of the disposalCode property.
     *
     * @param value
     *     allowed object is
     *     {@link DisposalCode }
     *
     */
    public void setDisposalCode(DisposalCode value) {
        this.disposalCode = value;
    }

    /**
     * Gets the value of the disposalLine property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the disposalLine property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisposalLine().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisposalLine }
     *
     *
     * @return
     *     The value of the disposalLine property.
     */
    public List<DisposalLine> getDisposalLine() {
        if (disposalLine == null) {
            disposalLine = new ArrayList<>();
        }
        return this.disposalLine;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *       <attribute name="TemplateVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DisposalCode {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "TemplateVersion", required = true)
        protected BigInteger templateVersion;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the templateVersion property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getTemplateVersion() {
            return templateVersion;
        }

        /**
         * Sets the value of the templateVersion property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setTemplateVersion(BigInteger value) {
            this.templateVersion = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="DilSeqNo" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         <element name="Data" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dilSeqNo",
        "data"
    })
    public static class DisposalLine {

        @XmlElement(name = "DilSeqNo", required = true)
        protected BigInteger dilSeqNo;
        @XmlElement(name = "Data", required = true)
        protected String data;

        /**
         * Gets the value of the dilSeqNo property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getDilSeqNo() {
            return dilSeqNo;
        }

        /**
         * Sets the value of the dilSeqNo property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setDilSeqNo(BigInteger value) {
            this.dilSeqNo = value;
        }

        /**
         * Gets the value of the data property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setData(String value) {
            this.data = value;
        }

    }

}
