//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for DailyListStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="DailyListStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DocumentID" type="{http://www.courtservice.gov.uk/schemas/courtservice}DocumentIDstructure"/>
 *         <element name="ListHeader" type="{http://www.courtservice.gov.uk/schemas/courtservice}ListHeaderStructure"/>
 *         <element name="CrownCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure"/>
 *         <element name="CourtLists">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="CourtList" type="{http://www.courtservice.gov.uk/schemas/courtservice}DailyCourtListStructure" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DailyListStructure", propOrder = {
    "documentID",
    "listHeader",
    "crownCourt",
    "courtLists"
})
@XmlRootElement(name = "DailyList")
public class DailyListStructure {

    @XmlElement(name = "DocumentID", required = true)
    protected DocumentIDstructure documentID;
    @XmlElement(name = "ListHeader", required = true)
    protected ListHeaderStructure listHeader;
    @XmlElement(name = "CrownCourt", required = true)
    protected CourtHouseStructure crownCourt;
    @XmlElement(name = "CourtLists", required = true)
    protected CourtLists courtLists;

    /**
     * Gets the value of the documentID property.
     *
     * @return
     *     possible object is
     *     {@link DocumentIDstructure }
     *
     */
    public DocumentIDstructure getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     *
     * @param value
     *     allowed object is
     *     {@link DocumentIDstructure }
     *
     */
    public void setDocumentID(DocumentIDstructure value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the listHeader property.
     *
     * @return
     *     possible object is
     *     {@link ListHeaderStructure }
     *
     */
    public ListHeaderStructure getListHeader() {
        return listHeader;
    }

    /**
     * Sets the value of the listHeader property.
     *
     * @param value
     *     allowed object is
     *     {@link ListHeaderStructure }
     *
     */
    public void setListHeader(ListHeaderStructure value) {
        this.listHeader = value;
    }

    /**
     * Gets the value of the crownCourt property.
     *
     * @return
     *     possible object is
     *     {@link CourtHouseStructure }
     *
     */
    public CourtHouseStructure getCrownCourt() {
        return crownCourt;
    }

    /**
     * Sets the value of the crownCourt property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtHouseStructure }
     *
     */
    public void setCrownCourt(CourtHouseStructure value) {
        this.crownCourt = value;
    }

    /**
     * Gets the value of the courtLists property.
     *
     * @return
     *     possible object is
     *     {@link CourtLists }
     *
     */
    public CourtLists getCourtLists() {
        return courtLists;
    }

    /**
     * Sets the value of the courtLists property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtLists }
     *
     */
    public void setCourtLists(CourtLists value) {
        this.courtLists = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="CourtList" type="{http://www.courtservice.gov.uk/schemas/courtservice}DailyCourtListStructure" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "courtList"
    })
    public static class CourtLists {

        @XmlElement(name = "CourtList", required = true)
        protected List<DailyCourtListStructure> courtList;

        /**
         * Gets the value of the courtList property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the courtList property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCourtList().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DailyCourtListStructure }
         *
         *
         * @return
         *     The value of the courtList property.
         */
        public List<DailyCourtListStructure> getCourtList() {
            if (courtList == null) {
                courtList = new ArrayList<>();
            }
            return this.courtList;
        }

    }

}
