//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DateQualifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="DateQualifierType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="before"/>
 *     <enumeration value="on or before"/>
 *     <enumeration value="on"/>
 *     <enumeration value="on or after"/>
 *     <enumeration value="after"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "DateQualifierType")
@XmlEnum
public enum DateQualifierType {

    @XmlEnumValue("before")
    BEFORE("before"),
    @XmlEnumValue("on or before")
    ON_OR_BEFORE("on or before"),
    @XmlEnumValue("on")
    ON("on"),
    @XmlEnumValue("on or after")
    ON_OR_AFTER("on or after"),
    @XmlEnumValue("after")
    AFTER("after");
    private final String value;

    DateQualifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DateQualifierType fromValue(String v) {
        for (DateQualifierType c: DateQualifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
