//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for DefendantStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="DefendantStructure">
 *   <complexContent>
 *     <extension base="{http://www.courtservice.gov.uk/schemas/courtservice}PersonStructure">
 *       <sequence>
 *         <element name="ASNs" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="ASN" type="{http://www.courtservice.gov.uk/schemas/courtservice}ASnumberType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="CRESTdefendantID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         <element name="PNCnumber" type="{http://www.courtservice.gov.uk/schemas/courtservice}PNCnumberType" minOccurs="0"/>
 *         <element name="URN" type="{http://www.courtservice.gov.uk/schemas/courtservice}URNtype" minOccurs="0"/>
 *         <element name="CROnumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="MagistratesCourtRefNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PrisonerID" type="{http://www.courtservice.gov.uk/schemas/courtservice}PrisonerIDtype" minOccurs="0"/>
 *         <element name="PrisonLocation" type="{http://www.courtservice.gov.uk/schemas/courtservice}PrisonLocationStructure" minOccurs="0"/>
 *         <element name="CustodyStatus" type="{http://www.courtservice.gov.uk/schemas/courtservice}BailStatusType" minOccurs="0"/>
 *         <element name="Counsel" type="{http://www.courtservice.gov.uk/schemas/courtservice}DefenceStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Charges" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Charge" type="{http://www.courtservice.gov.uk/schemas/courtservice}ChargeStructure" maxOccurs="unbounded"/>
 *                 </sequence>
 *                 <attribute name="NumberOfCharges" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="OriginalCharges" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="OriginalCharge" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="OriginalChargeSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             <element name="OriginalChargeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="AdditionalNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="DeportationReason" type="{http://www.courtservice.gov.uk/schemas/courtservice}DeportationReason" minOccurs="0"/>
 *         <element name="HateCrime" type="{http://www.courtservice.gov.uk/schemas/courtservice}HateCrimeStructure" minOccurs="0"/>
 *         <element name="DefendantNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefendantStructure", propOrder = {
    "asNs",
    "cresTdefendantID",
    "pnCnumber",
    "urn",
    "crOnumber",
    "magistratesCourtRefNumber",
    "prisonerID",
    "prisonLocation",
    "custodyStatus",
    "counsel",
    "charges",
    "originalCharges",
    "additionalNotes",
    "deportationReason",
    "hateCrime",
    "defendantNumber"
})
@XmlSeeAlso({
    RecordSheetHeaderStructure.Defendant.class
})
public class DefendantStructure
    extends PersonStructure
{

    @XmlElement(name = "ASNs")
    protected ASNs asNs;
    @XmlElement(name = "CRESTdefendantID")
    protected Integer cresTdefendantID;
    @XmlElement(name = "PNCnumber")
    protected String pnCnumber;
    @XmlElement(name = "URN")
    protected String urn;
    @XmlElement(name = "CROnumber")
    protected String crOnumber;
    @XmlElement(name = "MagistratesCourtRefNumber")
    protected String magistratesCourtRefNumber;
    @XmlElement(name = "PrisonerID")
    protected String prisonerID;
    @XmlElement(name = "PrisonLocation")
    protected PrisonLocationStructure prisonLocation;
    @XmlElement(name = "CustodyStatus")
    @XmlSchemaType(name = "string")
    protected BailStatusType custodyStatus;
    @XmlElement(name = "Counsel")
    protected List<DefenceStructure> counsel;
    @XmlElement(name = "Charges")
    protected Charges charges;
    @XmlElement(name = "OriginalCharges")
    protected OriginalCharges originalCharges;
    @XmlElement(name = "AdditionalNotes")
    protected String additionalNotes;
    @XmlElement(name = "DeportationReason")
    protected String deportationReason;
    @XmlElement(name = "HateCrime")
    protected HateCrimeStructure hateCrime;
    @XmlElement(name = "DefendantNumber")
    protected Integer defendantNumber;

    /**
     * Gets the value of the asNs property.
     *
     * @return
     *     possible object is
     *     {@link ASNs }
     *
     */
    public ASNs getASNs() {
        return asNs;
    }

    /**
     * Sets the value of the asNs property.
     *
     * @param value
     *     allowed object is
     *     {@link ASNs }
     *
     */
    public void setASNs(ASNs value) {
        this.asNs = value;
    }

    /**
     * Gets the value of the cresTdefendantID property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getCRESTdefendantID() {
        return cresTdefendantID;
    }

    /**
     * Sets the value of the cresTdefendantID property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setCRESTdefendantID(Integer value) {
        this.cresTdefendantID = value;
    }

    /**
     * Gets the value of the pnCnumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPNCnumber() {
        return pnCnumber;
    }

    /**
     * Sets the value of the pnCnumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPNCnumber(String value) {
        this.pnCnumber = value;
    }

    /**
     * Gets the value of the urn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getURN() {
        return urn;
    }

    /**
     * Sets the value of the urn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setURN(String value) {
        this.urn = value;
    }

    /**
     * Gets the value of the crOnumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCROnumber() {
        return crOnumber;
    }

    /**
     * Sets the value of the crOnumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCROnumber(String value) {
        this.crOnumber = value;
    }

    /**
     * Gets the value of the magistratesCourtRefNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMagistratesCourtRefNumber() {
        return magistratesCourtRefNumber;
    }

    /**
     * Sets the value of the magistratesCourtRefNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMagistratesCourtRefNumber(String value) {
        this.magistratesCourtRefNumber = value;
    }

    /**
     * Gets the value of the prisonerID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrisonerID() {
        return prisonerID;
    }

    /**
     * Sets the value of the prisonerID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrisonerID(String value) {
        this.prisonerID = value;
    }

    /**
     * Gets the value of the prisonLocation property.
     *
     * @return
     *     possible object is
     *     {@link PrisonLocationStructure }
     *
     */
    public PrisonLocationStructure getPrisonLocation() {
        return prisonLocation;
    }

    /**
     * Sets the value of the prisonLocation property.
     *
     * @param value
     *     allowed object is
     *     {@link PrisonLocationStructure }
     *
     */
    public void setPrisonLocation(PrisonLocationStructure value) {
        this.prisonLocation = value;
    }

    /**
     * Gets the value of the custodyStatus property.
     *
     * @return
     *     possible object is
     *     {@link BailStatusType }
     *
     */
    public BailStatusType getCustodyStatus() {
        return custodyStatus;
    }

    /**
     * Sets the value of the custodyStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link BailStatusType }
     *
     */
    public void setCustodyStatus(BailStatusType value) {
        this.custodyStatus = value;
    }

    /**
     * Gets the value of the counsel property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the counsel property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCounsel().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefenceStructure }
     *
     *
     * @return
     *     The value of the counsel property.
     */
    public List<DefenceStructure> getCounsel() {
        if (counsel == null) {
            counsel = new ArrayList<>();
        }
        return this.counsel;
    }

    /**
     * Gets the value of the charges property.
     *
     * @return
     *     possible object is
     *     {@link Charges }
     *
     */
    public Charges getCharges() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     *
     * @param value
     *     allowed object is
     *     {@link Charges }
     *
     */
    public void setCharges(Charges value) {
        this.charges = value;
    }

    /**
     * Gets the value of the originalCharges property.
     *
     * @return
     *     possible object is
     *     {@link OriginalCharges }
     *
     */
    public OriginalCharges getOriginalCharges() {
        return originalCharges;
    }

    /**
     * Sets the value of the originalCharges property.
     *
     * @param value
     *     allowed object is
     *     {@link OriginalCharges }
     *
     */
    public void setOriginalCharges(OriginalCharges value) {
        this.originalCharges = value;
    }

    /**
     * Gets the value of the additionalNotes property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdditionalNotes() {
        return additionalNotes;
    }

    /**
     * Sets the value of the additionalNotes property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdditionalNotes(String value) {
        this.additionalNotes = value;
    }

    /**
     * Gets the value of the deportationReason property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeportationReason() {
        return deportationReason;
    }

    /**
     * Sets the value of the deportationReason property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeportationReason(String value) {
        this.deportationReason = value;
    }

    /**
     * Gets the value of the hateCrime property.
     *
     * @return
     *     possible object is
     *     {@link HateCrimeStructure }
     *
     */
    public HateCrimeStructure getHateCrime() {
        return hateCrime;
    }

    /**
     * Sets the value of the hateCrime property.
     *
     * @param value
     *     allowed object is
     *     {@link HateCrimeStructure }
     *
     */
    public void setHateCrime(HateCrimeStructure value) {
        this.hateCrime = value;
    }

    /**
     * Gets the value of the defendantNumber property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getDefendantNumber() {
        return defendantNumber;
    }

    /**
     * Sets the value of the defendantNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setDefendantNumber(Integer value) {
        this.defendantNumber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="ASN" type="{http://www.courtservice.gov.uk/schemas/courtservice}ASnumberType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "asn"
    })
    public static class ASNs {

        @XmlElement(name = "ASN", required = true)
        protected List<String> asn;

        /**
         * Gets the value of the asn property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the asn property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getASN().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         * @return
         *     The value of the asn property.
         */
        public List<String> getASN() {
            if (asn == null) {
                asn = new ArrayList<>();
            }
            return this.asn;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Charge" type="{http://www.courtservice.gov.uk/schemas/courtservice}ChargeStructure" maxOccurs="unbounded"/>
     *       </sequence>
     *       <attribute name="NumberOfCharges" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "charge"
    })
    public static class Charges {

        @XmlElement(name = "Charge", required = true)
        protected List<ChargeStructure> charge;
        @XmlAttribute(name = "NumberOfCharges")
        protected BigInteger numberOfCharges;

        /**
         * Gets the value of the charge property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the charge property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCharge().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ChargeStructure }
         *
         *
         * @return
         *     The value of the charge property.
         */
        public List<ChargeStructure> getCharge() {
            if (charge == null) {
                charge = new ArrayList<>();
            }
            return this.charge;
        }

        /**
         * Gets the value of the numberOfCharges property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getNumberOfCharges() {
            return numberOfCharges;
        }

        /**
         * Sets the value of the numberOfCharges property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setNumberOfCharges(BigInteger value) {
            this.numberOfCharges = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="OriginalCharge" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="OriginalChargeSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   <element name="OriginalChargeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originalCharge"
    })
    public static class OriginalCharges {

        @XmlElement(name = "OriginalCharge", required = true)
        protected List<OriginalCharge> originalCharge;

        /**
         * Gets the value of the originalCharge property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the originalCharge property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOriginalCharge().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OriginalCharge }
         *
         *
         * @return
         *     The value of the originalCharge property.
         */
        public List<OriginalCharge> getOriginalCharge() {
            if (originalCharge == null) {
                originalCharge = new ArrayList<>();
            }
            return this.originalCharge;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="OriginalChargeSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         <element name="OriginalChargeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "originalChargeSequenceNumber",
            "originalChargeDescription"
        })
        public static class OriginalCharge {

            @XmlElement(name = "OriginalChargeSequenceNumber")
            protected int originalChargeSequenceNumber;
            @XmlElement(name = "OriginalChargeDescription", required = true)
            protected String originalChargeDescription;

            /**
             * Gets the value of the originalChargeSequenceNumber property.
             *
             */
            public int getOriginalChargeSequenceNumber() {
                return originalChargeSequenceNumber;
            }

            /**
             * Sets the value of the originalChargeSequenceNumber property.
             *
             */
            public void setOriginalChargeSequenceNumber(int value) {
                this.originalChargeSequenceNumber = value;
            }

            /**
             * Gets the value of the originalChargeDescription property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getOriginalChargeDescription() {
                return originalChargeDescription;
            }

            /**
             * Sets the value of the originalChargeDescription property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setOriginalChargeDescription(String value) {
                this.originalChargeDescription = value;
            }

        }

    }

}
