//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElectronicWhereaboutsStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ElectronicWhereaboutsStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="WhereaboutsDuration" type="{http://www.courtservice.gov.uk/schemas/courtservice}OrderDurationType" minOccurs="0"/>
 *         <element name="AdditionalInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElectronicWhereaboutsStructure", propOrder = {
    "whereaboutsDuration",
    "additionalInformation"
})
public class ElectronicWhereaboutsStructure {

    @XmlElement(name = "WhereaboutsDuration")
    protected OrderDurationType whereaboutsDuration;
    @XmlElement(name = "AdditionalInformation")
    protected String additionalInformation;

    /**
     * Gets the value of the whereaboutsDuration property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDurationType }
     *     
     */
    public OrderDurationType getWhereaboutsDuration() {
        return whereaboutsDuration;
    }

    /**
     * Sets the value of the whereaboutsDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDurationType }
     *     
     */
    public void setWhereaboutsDuration(OrderDurationType value) {
        this.whereaboutsDuration = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInformation(String value) {
        this.additionalInformation = value;
    }

}
