//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;


/**
 * <p>Java class for ExtendedActivityStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ExtendedActivityStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Activity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ActivityDuration" type="{http://www.courtservice.gov.uk/schemas/courtservice}OrderDurationType" minOccurs="0"/>
 *         <element name="ISSOption" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType" minOccurs="0"/>
 *         <element name="AdditionalInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedActivityStructure", propOrder = {
    "activity",
    "activityDuration",
    "issOption",
    "additionalInformation"
})
public class ExtendedActivityStructure {

    @XmlElement(name = "Activity")
    protected String activity;
    @XmlElement(name = "ActivityDuration")
    protected OrderDurationType activityDuration;
    @XmlElement(name = "ISSOption")
    @XmlSchemaType(name = "string")
    protected YesNoType issOption;
    @XmlElement(name = "AdditionalInformation")
    protected String additionalInformation;

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivity(String value) {
        this.activity = value;
    }

    /**
     * Gets the value of the activityDuration property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDurationType }
     *     
     */
    public OrderDurationType getActivityDuration() {
        return activityDuration;
    }

    /**
     * Sets the value of the activityDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDurationType }
     *     
     */
    public void setActivityDuration(OrderDurationType value) {
        this.activityDuration = value;
    }

    /**
     * Gets the value of the issOption property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getISSOption() {
        return issOption;
    }

    /**
     * Sets the value of the issOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setISSOption(YesNoType value) {
        this.issOption = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInformation(String value) {
        this.additionalInformation = value;
    }

}
