//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ForeignTravelProhibitionRequirementStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="ForeignTravelProhibitionRequirementStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Days" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="FromDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="ToDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="ProhibitedFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="Exception" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForeignTravelProhibitionRequirementStructure", propOrder = {
    "days",
    "fromDate",
    "toDate",
    "prohibitedFrom",
    "exception"
})
public class ForeignTravelProhibitionRequirementStructure {

    @XmlElement(name = "Days")
    protected String days;
    @XmlElement(name = "FromDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fromDate;
    @XmlElement(name = "ToDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar toDate;
    @XmlElement(name = "ProhibitedFrom", required = true)
    protected String prohibitedFrom;
    @XmlElement(name = "Exception")
    protected String exception;

    /**
     * Gets the value of the days property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDays() {
        return days;
    }

    /**
     * Sets the value of the days property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDays(String value) {
        this.days = value;
    }

    /**
     * Gets the value of the fromDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setToDate(XMLGregorianCalendar value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the prohibitedFrom property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getProhibitedFrom() {
        return prohibitedFrom;
    }

    /**
     * Sets the value of the prohibitedFrom property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setProhibitedFrom(String value) {
        this.prohibitedFrom = value;
    }

    /**
     * Gets the value of the exception property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getException() {
        return exception;
    }

    /**
     * Sets the value of the exception property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setException(String value) {
        this.exception = value;
    }

}
