//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FosteringStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="FosteringStructure">
 *   <complexContent>
 *     <extension base="{http://www.courtservice.gov.uk/schemas/courtservice}BaseOrderRequirementStructure">
 *       <sequence>
 *         <element name="LocalAuthority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="BeginDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FosteringStructure", propOrder = {
    "localAuthority",
    "beginDate"
})
public class FosteringStructure
    extends BaseOrderRequirementStructure
{

    @XmlElement(name = "LocalAuthority")
    protected String localAuthority;
    @XmlElement(name = "BeginDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar beginDate;

    /**
     * Gets the value of the localAuthority property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLocalAuthority() {
        return localAuthority;
    }

    /**
     * Sets the value of the localAuthority property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLocalAuthority(String value) {
        this.localAuthority = value;
    }

    /**
     * Gets the value of the beginDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getBeginDate() {
        return beginDate;
    }

    /**
     * Sets the value of the beginDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setBeginDate(XMLGregorianCalendar value) {
        this.beginDate = value;
    }

}
