//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for HearingStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="HearingStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="HearingSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="HearingDetails" type="{http://www.courtservice.gov.uk/schemas/courtservice}HearingTypeStructure"/>
 *         <element name="CRESThearingID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         <element name="TimeMarkingNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="CaseNumber" type="{http://www.courtservice.gov.uk/schemas/courtservice}CaseNumberType"/>
 *         <element name="Prosecution" type="{http://www.courtservice.gov.uk/schemas/courtservice}ProsecutionStructure" minOccurs="0"/>
 *         <element name="CommittingCourt" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure" minOccurs="0"/>
 *         <element name="ListNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="NumberOfDefendants" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         <element name="Defendants" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Defendant" type="{http://www.courtservice.gov.uk/schemas/courtservice}DefendantStructure" maxOccurs="unbounded" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Respondent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HearingStructure", propOrder = {
    "hearingSequenceNumber",
    "hearingDetails",
    "cresThearingID",
    "timeMarkingNote",
    "caseNumber",
    "prosecution",
    "committingCourt",
    "listNote",
    "numberOfDefendants",
    "defendants",
    "respondent"
})
public class HearingStructure {

    @XmlElement(name = "HearingSequenceNumber")
    protected int hearingSequenceNumber;
    @XmlElement(name = "HearingDetails", required = true)
    protected HearingTypeStructure hearingDetails;
    @XmlElement(name = "CRESThearingID")
    protected Integer cresThearingID;
    @XmlElement(name = "TimeMarkingNote")
    protected String timeMarkingNote;
    @XmlElement(name = "CaseNumber", required = true)
    protected String caseNumber;
    @XmlElement(name = "Prosecution")
    protected ProsecutionStructure prosecution;
    @XmlElement(name = "CommittingCourt")
    protected CourtHouseStructure committingCourt;
    @XmlElement(name = "ListNote")
    protected String listNote;
    @XmlElement(name = "NumberOfDefendants")
    protected Integer numberOfDefendants;
    @XmlElement(name = "Defendants")
    protected Defendants defendants;
    @XmlElement(name = "Respondent")
    protected String respondent;

    /**
     * Gets the value of the hearingSequenceNumber property.
     *
     */
    public int getHearingSequenceNumber() {
        return hearingSequenceNumber;
    }

    /**
     * Sets the value of the hearingSequenceNumber property.
     *
     */
    public void setHearingSequenceNumber(int value) {
        this.hearingSequenceNumber = value;
    }

    /**
     * Gets the value of the hearingDetails property.
     *
     * @return
     *     possible object is
     *     {@link HearingTypeStructure }
     *
     */
    public HearingTypeStructure getHearingDetails() {
        return hearingDetails;
    }

    /**
     * Sets the value of the hearingDetails property.
     *
     * @param value
     *     allowed object is
     *     {@link HearingTypeStructure }
     *
     */
    public void setHearingDetails(HearingTypeStructure value) {
        this.hearingDetails = value;
    }

    /**
     * Gets the value of the cresThearingID property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getCRESThearingID() {
        return cresThearingID;
    }

    /**
     * Sets the value of the cresThearingID property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setCRESThearingID(Integer value) {
        this.cresThearingID = value;
    }

    /**
     * Gets the value of the timeMarkingNote property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTimeMarkingNote() {
        return timeMarkingNote;
    }

    /**
     * Sets the value of the timeMarkingNote property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTimeMarkingNote(String value) {
        this.timeMarkingNote = value;
    }

    /**
     * Gets the value of the caseNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCaseNumber() {
        return caseNumber;
    }

    /**
     * Sets the value of the caseNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCaseNumber(String value) {
        this.caseNumber = value;
    }

    /**
     * Gets the value of the prosecution property.
     *
     * @return
     *     possible object is
     *     {@link ProsecutionStructure }
     *
     */
    public ProsecutionStructure getProsecution() {
        return prosecution;
    }

    /**
     * Sets the value of the prosecution property.
     *
     * @param value
     *     allowed object is
     *     {@link ProsecutionStructure }
     *
     */
    public void setProsecution(ProsecutionStructure value) {
        this.prosecution = value;
    }

    /**
     * Gets the value of the committingCourt property.
     *
     * @return
     *     possible object is
     *     {@link CourtHouseStructure }
     *
     */
    public CourtHouseStructure getCommittingCourt() {
        return committingCourt;
    }

    /**
     * Sets the value of the committingCourt property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtHouseStructure }
     *
     */
    public void setCommittingCourt(CourtHouseStructure value) {
        this.committingCourt = value;
    }

    /**
     * Gets the value of the listNote property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getListNote() {
        return listNote;
    }

    /**
     * Sets the value of the listNote property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setListNote(String value) {
        this.listNote = value;
    }

    /**
     * Gets the value of the numberOfDefendants property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getNumberOfDefendants() {
        return numberOfDefendants;
    }

    /**
     * Sets the value of the numberOfDefendants property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setNumberOfDefendants(Integer value) {
        this.numberOfDefendants = value;
    }

    /**
     * Gets the value of the defendants property.
     *
     * @return
     *     possible object is
     *     {@link Defendants }
     *
     */
    public Defendants getDefendants() {
        return defendants;
    }

    /**
     * Sets the value of the defendants property.
     *
     * @param value
     *     allowed object is
     *     {@link Defendants }
     *
     */
    public void setDefendants(Defendants value) {
        this.defendants = value;
    }

    /**
     * Gets the value of the respondent property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRespondent() {
        return respondent;
    }

    /**
     * Sets the value of the respondent property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRespondent(String value) {
        this.respondent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Defendant" type="{http://www.courtservice.gov.uk/schemas/courtservice}DefendantStructure" maxOccurs="unbounded" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "defendant"
    })
    public static class Defendants {

        @XmlElement(name = "Defendant")
        protected List<DefendantStructure> defendant;

        /**
         * Gets the value of the defendant property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the defendant property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDefendant().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DefendantStructure }
         *
         *
         * @return
         *     The value of the defendant property.
         */
        public List<DefendantStructure> getDefendant() {
            if (defendant == null) {
                defendant = new ArrayList<>();
            }
            return this.defendant;
        }

    }

}
