//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HearingTypeStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="HearingTypeStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="HearingDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="HearingDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="HearingEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="ListNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="HearingType" type="{http://www.courtservice.gov.uk/schemas/courtservice}HearingTypeType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HearingTypeStructure", propOrder = {
    "hearingDescription",
    "hearingDate",
    "hearingEndDate",
    "listNote"
})
public class HearingTypeStructure {

    @XmlElement(name = "HearingDescription", required = true)
    protected String hearingDescription;
    @XmlElement(name = "HearingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar hearingDate;
    @XmlElement(name = "HearingEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar hearingEndDate;
    @XmlElement(name = "ListNote")
    protected String listNote;
    @XmlAttribute(name = "HearingType")
    protected String hearingType;

    /**
     * Gets the value of the hearingDescription property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHearingDescription() {
        return hearingDescription;
    }

    /**
     * Sets the value of the hearingDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHearingDescription(String value) {
        this.hearingDescription = value;
    }

    /**
     * Gets the value of the hearingDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getHearingDate() {
        return hearingDate;
    }

    /**
     * Sets the value of the hearingDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setHearingDate(XMLGregorianCalendar value) {
        this.hearingDate = value;
    }

    /**
     * Gets the value of the hearingEndDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getHearingEndDate() {
        return hearingEndDate;
    }

    /**
     * Sets the value of the hearingEndDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setHearingEndDate(XMLGregorianCalendar value) {
        this.hearingEndDate = value;
    }

    /**
     * Gets the value of the listNote property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getListNote() {
        return listNote;
    }

    /**
     * Sets the value of the listNote property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setListNote(String value) {
        this.listNote = value;
    }

    /**
     * Gets the value of the hearingType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHearingType() {
        return hearingType;
    }

    /**
     * Sets the value of the hearingType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHearingType(String value) {
        this.hearingType = value;
    }

}
