//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.CitizenNameStructure;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for JudiciaryStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="JudiciaryStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Judge">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}CitizenNameStructure">
 *                 <sequence>
 *                   <element name="CRESTjudgeID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Justice" maxOccurs="4" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}CitizenNameStructure">
 *                 <sequence minOccurs="0">
 *                   <element name="CRESTjusticeID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JudiciaryStructure", propOrder = {
    "judge",
    "justice",
    "startDate",
    "endDate"
})
public class JudiciaryStructure {

    @XmlElement(name = "Judge", required = true)
    protected Judge judge;
    @XmlElement(name = "Justice")
    protected List<Justice> justice;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;

    /**
     * Gets the value of the judge property.
     *
     * @return
     *     possible object is
     *     {@link Judge }
     *
     */
    public Judge getJudge() {
        return judge;
    }

    /**
     * Sets the value of the judge property.
     *
     * @param value
     *     allowed object is
     *     {@link Judge }
     *
     */
    public void setJudge(Judge value) {
        this.judge = value;
    }

    /**
     * Gets the value of the justice property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the justice property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJustice().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Justice }
     *
     *
     * @return
     *     The value of the justice property.
     */
    public List<Justice> getJustice() {
        if (justice == null) {
            justice = new ArrayList<>();
        }
        return this.justice;
    }

    /**
     * Gets the value of the startDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}CitizenNameStructure">
     *       <sequence>
     *         <element name="CRESTjudgeID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cresTjudgeID"
    })
    public static class Judge
        extends CitizenNameStructure
    {

        @XmlElement(name = "CRESTjudgeID")
        protected Integer cresTjudgeID;

        /**
         * Gets the value of the cresTjudgeID property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getCRESTjudgeID() {
            return cresTjudgeID;
        }

        /**
         * Sets the value of the cresTjudgeID property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setCRESTjudgeID(Integer value) {
            this.cresTjudgeID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}CitizenNameStructure">
     *       <sequence minOccurs="0">
     *         <element name="CRESTjusticeID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cresTjusticeID"
    })
    public static class Justice
        extends CitizenNameStructure
    {

        @XmlElement(name = "CRESTjusticeID")
        protected Integer cresTjusticeID;

        /**
         * Gets the value of the cresTjusticeID property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getCRESTjusticeID() {
            return cresTjusticeID;
        }

        /**
         * Sets the value of the cresTjusticeID property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setCRESTjusticeID(Integer value) {
            this.cresTjusticeID = value;
        }

    }

}
