//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;


/**
 * <p>Java class for NBSSOrderStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="NBSSOrderStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="OriginalTermUnaltered" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType" minOccurs="0"/>
 *         <element name="LesserTerm" type="{http://www.courtservice.gov.uk/schemas/courtservice}ModifiedTermStructure" minOccurs="0"/>
 *         <element name="Fine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="Requirements" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="SupervisionPeriod" type="{http://www.courtservice.gov.uk/schemas/courtservice}ModifiedTermStructure" minOccurs="0"/>
 *         <element name="OperationalPeriod" type="{http://www.courtservice.gov.uk/schemas/courtservice}ModifiedTermStructure" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NBSSOrderStructure", propOrder = {
    "originalTermUnaltered",
    "lesserTerm",
    "fine",
    "requirements",
    "supervisionPeriod",
    "operationalPeriod"
})
public class NBSSOrderStructure {

    @XmlElement(name = "OriginalTermUnaltered")
    @XmlSchemaType(name = "string")
    protected YesNoType originalTermUnaltered;
    @XmlElement(name = "LesserTerm")
    protected ModifiedTermStructure lesserTerm;
    @XmlElement(name = "Fine")
    protected String fine;
    @XmlElement(name = "Requirements")
    protected String requirements;
    @XmlElement(name = "SupervisionPeriod")
    protected ModifiedTermStructure supervisionPeriod;
    @XmlElement(name = "OperationalPeriod")
    protected ModifiedTermStructure operationalPeriod;

    /**
     * Gets the value of the originalTermUnaltered property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getOriginalTermUnaltered() {
        return originalTermUnaltered;
    }

    /**
     * Sets the value of the originalTermUnaltered property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setOriginalTermUnaltered(YesNoType value) {
        this.originalTermUnaltered = value;
    }

    /**
     * Gets the value of the lesserTerm property.
     * 
     * @return
     *     possible object is
     *     {@link ModifiedTermStructure }
     *     
     */
    public ModifiedTermStructure getLesserTerm() {
        return lesserTerm;
    }

    /**
     * Sets the value of the lesserTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifiedTermStructure }
     *     
     */
    public void setLesserTerm(ModifiedTermStructure value) {
        this.lesserTerm = value;
    }

    /**
     * Gets the value of the fine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFine() {
        return fine;
    }

    /**
     * Sets the value of the fine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFine(String value) {
        this.fine = value;
    }

    /**
     * Gets the value of the requirements property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequirements() {
        return requirements;
    }

    /**
     * Sets the value of the requirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequirements(String value) {
        this.requirements = value;
    }

    /**
     * Gets the value of the supervisionPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ModifiedTermStructure }
     *     
     */
    public ModifiedTermStructure getSupervisionPeriod() {
        return supervisionPeriod;
    }

    /**
     * Sets the value of the supervisionPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifiedTermStructure }
     *     
     */
    public void setSupervisionPeriod(ModifiedTermStructure value) {
        this.supervisionPeriod = value;
    }

    /**
     * Gets the value of the operationalPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ModifiedTermStructure }
     *     
     */
    public ModifiedTermStructure getOperationalPeriod() {
        return operationalPeriod;
    }

    /**
     * Sets the value of the operationalPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifiedTermStructure }
     *     
     */
    public void setOperationalPeriod(ModifiedTermStructure value) {
        this.operationalPeriod = value;
    }

}
