//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;

import javax.xml.datatype.Duration;


/**
 * <p>Java class for OrderDurationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="OrderDurationType">
 *   <simpleContent>
 *     <extension base="<http://www.w3.org/2001/XMLSchema>duration">
 *       <attribute name="SpecifiedInWeeks" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderDurationType", propOrder = {
    "value"
})
public class OrderDurationType {

    @XmlValue
    protected Duration value;
    @XmlAttribute(name = "SpecifiedInWeeks")
    protected YesNoType specifiedInWeeks;

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link Duration }
     *
     */
    public Duration getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link Duration }
     *
     */
    public void setValue(Duration value) {
        this.value = value;
    }

    /**
     * Gets the value of the specifiedInWeeks property.
     *
     * @return
     *     possible object is
     *     {@link YesNoType }
     *
     */
    public YesNoType getSpecifiedInWeeks() {
        return specifiedInWeeks;
    }

    /**
     * Sets the value of the specifiedInWeeks property.
     *
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *
     */
    public void setSpecifiedInWeeks(YesNoType value) {
        this.specifiedInWeeks = value;
    }

}
