//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OrderReviewStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="OrderReviewStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Periodicity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="Location" type="{http://www.courtservice.gov.uk/schemas/courtservice}CourtHouseStructure" minOccurs="0"/>
 *         <element name="DateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         <element name="Telephone" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}TelephoneNumberType" minOccurs="0"/>
 *         <element name="CompulsoryAttendance" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderReviewStructure", propOrder = {
    "periodicity",
    "location",
    "dateTime",
    "telephone",
    "compulsoryAttendance"
})
public class OrderReviewStructure {

    @XmlElement(name = "Periodicity", required = true)
    protected String periodicity;
    @XmlElement(name = "Location")
    protected CourtHouseStructure location;
    @XmlElement(name = "DateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;
    @XmlElement(name = "Telephone")
    protected String telephone;
    @XmlElement(name = "CompulsoryAttendance")
    @XmlSchemaType(name = "string")
    protected YesNoType compulsoryAttendance;

    /**
     * Gets the value of the periodicity property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPeriodicity() {
        return periodicity;
    }

    /**
     * Sets the value of the periodicity property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPeriodicity(String value) {
        this.periodicity = value;
    }

    /**
     * Gets the value of the location property.
     *
     * @return
     *     possible object is
     *     {@link CourtHouseStructure }
     *
     */
    public CourtHouseStructure getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     *
     * @param value
     *     allowed object is
     *     {@link CourtHouseStructure }
     *
     */
    public void setLocation(CourtHouseStructure value) {
        this.location = value;
    }

    /**
     * Gets the value of the dateTime property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the telephone property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * Sets the value of the telephone property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTelephone(String value) {
        this.telephone = value;
    }

    /**
     * Gets the value of the compulsoryAttendance property.
     *
     * @return
     *     possible object is
     *     {@link YesNoType }
     *
     */
    public YesNoType getCompulsoryAttendance() {
        return compulsoryAttendance;
    }

    /**
     * Sets the value of the compulsoryAttendance property.
     *
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *
     */
    public void setCompulsoryAttendance(YesNoType value) {
        this.compulsoryAttendance = value;
    }

}
