//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtherReasonsStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="OtherReasonsStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Welfare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="OwnProtection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="LackOfPlacement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="BailISSNotAvailable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="BailInadequate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherReasonsStructure", propOrder = {
    "welfare",
    "ownProtection",
    "lackOfPlacement",
    "bailISSNotAvailable",
    "bailInadequate"
})
public class OtherReasonsStructure {

    @XmlElement(name = "Welfare")
    protected String welfare;
    @XmlElement(name = "OwnProtection")
    protected String ownProtection;
    @XmlElement(name = "LackOfPlacement")
    protected String lackOfPlacement;
    @XmlElement(name = "BailISSNotAvailable")
    protected String bailISSNotAvailable;
    @XmlElement(name = "BailInadequate")
    protected String bailInadequate;

    /**
     * Gets the value of the welfare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWelfare() {
        return welfare;
    }

    /**
     * Sets the value of the welfare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWelfare(String value) {
        this.welfare = value;
    }

    /**
     * Gets the value of the ownProtection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnProtection() {
        return ownProtection;
    }

    /**
     * Sets the value of the ownProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnProtection(String value) {
        this.ownProtection = value;
    }

    /**
     * Gets the value of the lackOfPlacement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLackOfPlacement() {
        return lackOfPlacement;
    }

    /**
     * Sets the value of the lackOfPlacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLackOfPlacement(String value) {
        this.lackOfPlacement = value;
    }

    /**
     * Gets the value of the bailISSNotAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBailISSNotAvailable() {
        return bailISSNotAvailable;
    }

    /**
     * Sets the value of the bailISSNotAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBailISSNotAvailable(String value) {
        this.bailISSNotAvailable = value;
    }

    /**
     * Gets the value of the bailInadequate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBailInadequate() {
        return bailInadequate;
    }

    /**
     * Sets the value of the bailInadequate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBailInadequate(String value) {
        this.bailInadequate = value;
    }

}
