//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.CitizenBirthDateStructure;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.CitizenNameStructure;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.SexType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.UKPostalAddressStructure;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;

import java.math.BigInteger;


/**
 * <p>Java class for PersonalDetailsStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="PersonalDetailsStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Name" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}CitizenNameStructure" minOccurs="0"/>
 *         <element name="MaskedName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="IsMasked" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
 *         <element name="DateOfBirth" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}CitizenBirthDateStructure" minOccurs="0"/>
 *         <element name="Age" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         <element name="Sex" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}SexType" minOccurs="0"/>
 *         <element name="Address" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}UKPostalAddressStructure" minOccurs="0"/>
 *         <element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalDetailsStructure", propOrder = {
    "name",
    "maskedName",
    "isMasked",
    "dateOfBirth",
    "age",
    "sex",
    "address",
    "nationality"
})
public class PersonalDetailsStructure {

    @XmlElement(name = "Name")
    protected CitizenNameStructure name;
    @XmlElement(name = "MaskedName")
    protected String maskedName;
    @XmlElement(name = "IsMasked", required = true)
    @XmlSchemaType(name = "string")
    protected YesNoType isMasked;
    @XmlElement(name = "DateOfBirth")
    protected CitizenBirthDateStructure dateOfBirth;
    @XmlElement(name = "Age")
    protected BigInteger age;
    @XmlElement(name = "Sex")
    @XmlSchemaType(name = "string")
    protected SexType sex;
    @XmlElement(name = "Address")
    protected UKPostalAddressStructure address;
    @XmlElement(name = "Nationality")
    protected String nationality;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link CitizenNameStructure }
     *
     */
    public CitizenNameStructure getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link CitizenNameStructure }
     *
     */
    public void setName(CitizenNameStructure value) {
        this.name = value;
    }

    /**
     * Gets the value of the maskedName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMaskedName() {
        return maskedName;
    }

    /**
     * Sets the value of the maskedName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMaskedName(String value) {
        this.maskedName = value;
    }

    /**
     * Gets the value of the isMasked property.
     *
     * @return
     *     possible object is
     *     {@link YesNoType }
     *
     */
    public YesNoType getIsMasked() {
        return isMasked;
    }

    /**
     * Sets the value of the isMasked property.
     *
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *
     */
    public void setIsMasked(YesNoType value) {
        this.isMasked = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     *
     * @return
     *     possible object is
     *     {@link CitizenBirthDateStructure }
     *
     */
    public CitizenBirthDateStructure getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     *
     * @param value
     *     allowed object is
     *     {@link CitizenBirthDateStructure }
     *
     */
    public void setDateOfBirth(CitizenBirthDateStructure value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the age property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setAge(BigInteger value) {
        this.age = value;
    }

    /**
     * Gets the value of the sex property.
     *
     * @return
     *     possible object is
     *     {@link SexType }
     *
     */
    public SexType getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     *
     * @param value
     *     allowed object is
     *     {@link SexType }
     *
     */
    public void setSex(SexType value) {
        this.sex = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return
     *     possible object is
     *     {@link UKPostalAddressStructure }
     *
     */
    public UKPostalAddressStructure getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value
     *     allowed object is
     *     {@link UKPostalAddressStructure }
     *
     */
    public void setAddress(UKPostalAddressStructure value) {
        this.address = value;
    }

    /**
     * Gets the value of the nationality property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

}
