//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonsForRemandStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ReasonsForRemandStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="SeriousnessOfOffence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="History" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="Necessity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="OtherReasons" type="{http://www.courtservice.gov.uk/schemas/courtservice}OtherReasonsStructure" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReasonsForRemandStructure", propOrder = {
    "seriousnessOfOffence",
    "history",
    "necessity",
    "otherReasons"
})
public class ReasonsForRemandStructure {

    @XmlElement(name = "SeriousnessOfOffence")
    protected String seriousnessOfOffence;
    @XmlElement(name = "History")
    protected String history;
    @XmlElement(name = "Necessity")
    protected String necessity;
    @XmlElement(name = "OtherReasons")
    protected OtherReasonsStructure otherReasons;

    /**
     * Gets the value of the seriousnessOfOffence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriousnessOfOffence() {
        return seriousnessOfOffence;
    }

    /**
     * Sets the value of the seriousnessOfOffence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriousnessOfOffence(String value) {
        this.seriousnessOfOffence = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHistory(String value) {
        this.history = value;
    }

    /**
     * Gets the value of the necessity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNecessity() {
        return necessity;
    }

    /**
     * Sets the value of the necessity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNecessity(String value) {
        this.necessity = value;
    }

    /**
     * Gets the value of the otherReasons property.
     * 
     * @return
     *     possible object is
     *     {@link OtherReasonsStructure }
     *     
     */
    public OtherReasonsStructure getOtherReasons() {
        return otherReasons;
    }

    /**
     * Sets the value of the otherReasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherReasonsStructure }
     *     
     */
    public void setOtherReasons(OtherReasonsStructure value) {
        this.otherReasons = value;
    }

}
