//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecordSheetTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RecordSheetTypeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Appeal Record Sheet"/>
 *     <enumeration value="Committal Record Sheet"/>
 *     <enumeration value="Trial Record Sheet"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RecordSheetTypeType")
@XmlEnum
public enum RecordSheetTypeType {

    @XmlEnumValue("Appeal Record Sheet")
    APPEAL_RECORD_SHEET("Appeal Record Sheet"),
    @XmlEnumValue("Committal Record Sheet")
    COMMITTAL_RECORD_SHEET("Committal Record Sheet"),
    @XmlEnumValue("Trial Record Sheet")
    TRIAL_RECORD_SHEET("Trial Record Sheet");
    private final String value;

    RecordSheetTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RecordSheetTypeType fromValue(String v) {
        for (RecordSheetTypeType c: RecordSheetTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
