//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RemandTypeStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="RemandTypeStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DesignatedLocalAuthority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="RequirementOnLocalAuthority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ConditionsOnDefendant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="RemandType" type="{http://www.courtservice.gov.uk/schemas/courtservice}RemandOrderTypeType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemandTypeStructure", propOrder = {
    "designatedLocalAuthority",
    "requirementOnLocalAuthority",
    "conditionsOnDefendant"
})
public class RemandTypeStructure {

    @XmlElement(name = "DesignatedLocalAuthority", required = true)
    protected String designatedLocalAuthority;
    @XmlElement(name = "RequirementOnLocalAuthority")
    protected String requirementOnLocalAuthority;
    @XmlElement(name = "ConditionsOnDefendant")
    protected String conditionsOnDefendant;
    @XmlAttribute(name = "RemandType")
    protected RemandOrderTypeType remandType;

    /**
     * Gets the value of the designatedLocalAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignatedLocalAuthority() {
        return designatedLocalAuthority;
    }

    /**
     * Sets the value of the designatedLocalAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignatedLocalAuthority(String value) {
        this.designatedLocalAuthority = value;
    }

    /**
     * Gets the value of the requirementOnLocalAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequirementOnLocalAuthority() {
        return requirementOnLocalAuthority;
    }

    /**
     * Sets the value of the requirementOnLocalAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequirementOnLocalAuthority(String value) {
        this.requirementOnLocalAuthority = value;
    }

    /**
     * Gets the value of the conditionsOnDefendant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionsOnDefendant() {
        return conditionsOnDefendant;
    }

    /**
     * Sets the value of the conditionsOnDefendant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionsOnDefendant(String value) {
        this.conditionsOnDefendant = value;
    }

    /**
     * Gets the value of the remandType property.
     * 
     * @return
     *     possible object is
     *     {@link RemandOrderTypeType }
     *     
     */
    public RemandOrderTypeType getRemandType() {
        return remandType;
    }

    /**
     * Sets the value of the remandType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemandOrderTypeType }
     *     
     */
    public void setRemandType(RemandOrderTypeType value) {
        this.remandType = value;
    }

}
