//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RemandOrderTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RemandOrderTypeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="LocalAuthority"/>
 *     <enumeration value="YouthDetention"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RemandOrderTypeType")
@XmlEnum
public enum RemandOrderTypeType {

    @XmlEnumValue("LocalAuthority")
    LOCAL_AUTHORITY("LocalAuthority"),
    @XmlEnumValue("YouthDetention")
    YOUTH_DETENTION("YouthDetention");
    private final String value;

    RemandOrderTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RemandOrderTypeType fromValue(String v) {
        for (RemandOrderTypeType c: RemandOrderTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
