//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RemandTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RemandTypeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Indicted"/>
 *     <enumeration value="Convicted"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RemandTypeType")
@XmlEnum
public enum RemandTypeType {

    @XmlEnumValue("Indicted")
    INDICTED("Indicted"),
    @XmlEnumValue("Convicted")
    CONVICTED("Convicted");
    private final String value;

    RemandTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RemandTypeType fromValue(String v) {
        for (RemandTypeType c: RemandTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
