//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Section85Structure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Section85Structure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TermType" type="{http://www.courtservice.gov.uk/schemas/courtservice}TermTypeType" minOccurs="0"/>
 *         <element name="Section85Total" type="{http://www.courtservice.gov.uk/schemas/courtservice}SentenceLengthType"/>
 *         <element name="Section85Custodial" type="{http://www.courtservice.gov.uk/schemas/courtservice}SentenceLengthType"/>
 *         <element name="Section85Extension" type="{http://www.courtservice.gov.uk/schemas/courtservice}SentenceLengthType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Section85Structure", propOrder = {
    "termType",
    "section85Total",
    "section85Custodial",
    "section85Extension"
})
public class Section85Structure {

    @XmlElement(name = "TermType")
    @XmlSchemaType(name = "string")
    protected TermTypeType termType;
    @XmlElement(name = "Section85Total", required = true)
    protected String section85Total;
    @XmlElement(name = "Section85Custodial", required = true)
    protected String section85Custodial;
    @XmlElement(name = "Section85Extension", required = true)
    protected String section85Extension;

    /**
     * Gets the value of the termType property.
     * 
     * @return
     *     possible object is
     *     {@link TermTypeType }
     *     
     */
    public TermTypeType getTermType() {
        return termType;
    }

    /**
     * Sets the value of the termType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermTypeType }
     *     
     */
    public void setTermType(TermTypeType value) {
        this.termType = value;
    }

    /**
     * Gets the value of the section85Total property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection85Total() {
        return section85Total;
    }

    /**
     * Sets the value of the section85Total property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection85Total(String value) {
        this.section85Total = value;
    }

    /**
     * Gets the value of the section85Custodial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection85Custodial() {
        return section85Custodial;
    }

    /**
     * Sets the value of the section85Custodial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection85Custodial(String value) {
        this.section85Custodial = value;
    }

    /**
     * Gets the value of the section85Extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection85Extension() {
        return section85Extension;
    }

    /**
     * Sets the value of the section85Extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection85Extension(String value) {
        this.section85Extension = value;
    }

}
