//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SittingStructure complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="SittingStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CourtRoomNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="SittingSequenceNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="SittingAt" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         <element name="SittingPriority">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="T"/>
 *               <enumeration value="F"/>
 *               <enumeration value="R"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="SittingNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="Judiciary" type="{http://www.courtservice.gov.uk/schemas/courtservice}JudiciaryStructure"/>
 *         <element name="Hearings">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Hearing" type="{http://www.courtservice.gov.uk/schemas/courtservice}HearingStructure" maxOccurs="unbounded" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SittingStructure", propOrder = {
    "courtRoomNumber",
    "sittingSequenceNo",
    "sittingAt",
    "sittingPriority",
    "sittingNote",
    "judiciary",
    "hearings"
})
public class SittingStructure {

    @XmlElement(name = "CourtRoomNumber")
    protected String courtRoomNumber;
    @XmlElement(name = "SittingSequenceNo", required = true)
    protected String sittingSequenceNo;
    @XmlElement(name = "SittingAt")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar sittingAt;
    @XmlElement(name = "SittingPriority", required = true)
    protected String sittingPriority;
    @XmlElement(name = "SittingNote")
    protected String sittingNote;
    @XmlElement(name = "Judiciary", required = true)
    protected JudiciaryStructure judiciary;
    @XmlElement(name = "Hearings", required = true)
    protected Hearings hearings;

    /**
     * Gets the value of the courtRoomNumber property.
     *
     */
    public String getCourtRoomNumber() {
        return courtRoomNumber;
    }

    /**
     * Sets the value of the courtRoomNumber property.
     *
     */
    public void setCourtRoomNumber(String value) {
        this.courtRoomNumber = value;
    }

    /**
     * Gets the value of the sittingSequenceNo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSittingSequenceNo() {
        return sittingSequenceNo;
    }

    /**
     * Sets the value of the sittingSequenceNo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSittingSequenceNo(String value) {
        this.sittingSequenceNo = value;
    }

    /**
     * Gets the value of the sittingAt property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getSittingAt() {
        return sittingAt;
    }

    /**
     * Sets the value of the sittingAt property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setSittingAt(XMLGregorianCalendar value) {
        this.sittingAt = value;
    }

    /**
     * Gets the value of the sittingPriority property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSittingPriority() {
        return sittingPriority;
    }

    /**
     * Sets the value of the sittingPriority property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSittingPriority(String value) {
        this.sittingPriority = value;
    }

    /**
     * Gets the value of the sittingNote property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSittingNote() {
        return sittingNote;
    }

    /**
     * Sets the value of the sittingNote property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSittingNote(String value) {
        this.sittingNote = value;
    }

    /**
     * Gets the value of the judiciary property.
     *
     * @return
     *     possible object is
     *     {@link JudiciaryStructure }
     *
     */
    public JudiciaryStructure getJudiciary() {
        return judiciary;
    }

    /**
     * Sets the value of the judiciary property.
     *
     * @param value
     *     allowed object is
     *     {@link JudiciaryStructure }
     *
     */
    public void setJudiciary(JudiciaryStructure value) {
        this.judiciary = value;
    }

    /**
     * Gets the value of the hearings property.
     *
     * @return
     *     possible object is
     *     {@link Hearings }
     *
     */
    public Hearings getHearings() {
        return hearings;
    }

    /**
     * Sets the value of the hearings property.
     *
     * @param value
     *     allowed object is
     *     {@link Hearings }
     *
     */
    public void setHearings(Hearings value) {
        this.hearings = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Hearing" type="{http://www.courtservice.gov.uk/schemas/courtservice}HearingStructure" maxOccurs="unbounded" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hearing"
    })
    public static class Hearings {

        @XmlElement(name = "Hearing")
        protected List<HearingStructure> hearing;

        /**
         * Gets the value of the hearing property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the hearing property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHearing().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HearingStructure }
         *
         *
         * @return
         *     The value of the hearing property.
         */
        public List<HearingStructure> getHearing() {
            if (hearing == null) {
                hearing = new ArrayList<>();
            }
            return this.hearing;
        }

    }

}
