//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubjectTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="SubjectTypeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Defendant"/>
 *     <enumeration value="Appellant"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "SubjectTypeType")
@XmlEnum
public enum SubjectTypeType {

    @XmlEnumValue("Defendant")
    DEFENDANT("Defendant"),
    @XmlEnumValue("Appellant")
    APPELLANT("Appellant");
    private final String value;

    SubjectTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubjectTypeType fromValue(String v) {
        for (SubjectTypeType c: SubjectTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
