//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SUSImprisonmentPeriod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="SUSImprisonmentPeriod">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Years" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               <minInclusive value="0"/>
 *               <maxInclusive value="99"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Months" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               <minInclusive value="0"/>
 *               <maxInclusive value="999"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Weeks" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               <minInclusive value="0"/>
 *               <maxInclusive value="999"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Days" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               <minInclusive value="0"/>
 *               <maxInclusive value="999"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SUSImprisonmentPeriod", propOrder = {
    "years",
    "months",
    "weeks",
    "days"
})
public class SUSImprisonmentPeriod {

    @XmlElement(name = "Years")
    protected Short years;
    @XmlElement(name = "Months")
    protected Short months;
    @XmlElement(name = "Weeks")
    protected Short weeks;
    @XmlElement(name = "Days")
    protected Short days;

    /**
     * Gets the value of the years property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getYears() {
        return years;
    }

    /**
     * Sets the value of the years property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setYears(Short value) {
        this.years = value;
    }

    /**
     * Gets the value of the months property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMonths() {
        return months;
    }

    /**
     * Sets the value of the months property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMonths(Short value) {
        this.months = value;
    }

    /**
     * Gets the value of the weeks property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getWeeks() {
        return weeks;
    }

    /**
     * Sets the value of the weeks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setWeeks(Short value) {
        this.weeks = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDays() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDays(Short value) {
        this.days = value;
    }

}
