//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import uk.gov.hmcts.darts.task.runner.dailylist.govtalk.people.addressandpersonaldetails.YesNoType;


/**
 * <p>Java class for TestingStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="TestingStructure">
 *   <complexContent>
 *     <extension base="{http://www.courtservice.gov.uk/schemas/courtservice}BaseOrderRequirementStructure">
 *       <choice>
 *         <element name="ResponsibleOfficerInstructions" type="{http://www.courtservice.gov.uk/schemas/courtservice}YesNoType"/>
 *         <element name="MinimumOccasions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="Requirements" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </choice>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestingStructure", propOrder = {
    "responsibleOfficerInstructions",
    "minimumOccasions",
    "requirements"
})
public class TestingStructure
    extends BaseOrderRequirementStructure
{

    @XmlElement(name = "ResponsibleOfficerInstructions", defaultValue = "yes")
    @XmlSchemaType(name = "string")
    protected YesNoType responsibleOfficerInstructions;
    @XmlElement(name = "MinimumOccasions")
    protected String minimumOccasions;
    @XmlElement(name = "Requirements")
    protected String requirements;

    /**
     * Gets the value of the responsibleOfficerInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getResponsibleOfficerInstructions() {
        return responsibleOfficerInstructions;
    }

    /**
     * Sets the value of the responsibleOfficerInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setResponsibleOfficerInstructions(YesNoType value) {
        this.responsibleOfficerInstructions = value;
    }

    /**
     * Gets the value of the minimumOccasions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumOccasions() {
        return minimumOccasions;
    }

    /**
     * Sets the value of the minimumOccasions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumOccasions(String value) {
        this.minimumOccasions = value;
    }

    /**
     * Gets the value of the requirements property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequirements() {
        return requirements;
    }

    /**
     * Sets the value of the requirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequirements(String value) {
        this.requirements = value;
    }

}
