//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package uk.gov.hmcts.darts.task.runner.dailylist.schemas.courtservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TreatmentStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="TreatmentStructure">
 *   <complexContent>
 *     <extension base="{http://www.courtservice.gov.uk/schemas/courtservice}BaseOrderRequirementStructure">
 *       <sequence>
 *         <element name="TreatmentDirector" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TreatmentLocation" type="{http://www.courtservice.gov.uk/schemas/courtservice}LocationStructure" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TreatmentStructure", propOrder = {
    "treatmentDirector",
    "treatmentLocation"
})
@XmlSeeAlso({
    DrugRehabilitationStructure.class
})
public class TreatmentStructure
    extends BaseOrderRequirementStructure
{

    @XmlElement(name = "TreatmentDirector")
    protected String treatmentDirector;
    @XmlElement(name = "TreatmentLocation")
    protected LocationStructure treatmentLocation;

    /**
     * Gets the value of the treatmentDirector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTreatmentDirector() {
        return treatmentDirector;
    }

    /**
     * Sets the value of the treatmentDirector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTreatmentDirector(String value) {
        this.treatmentDirector = value;
    }

    /**
     * Gets the value of the treatmentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getTreatmentLocation() {
        return treatmentLocation;
    }

    /**
     * Sets the value of the treatmentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setTreatmentLocation(LocationStructure value) {
        this.treatmentLocation = value;
    }

}
